-- =============================================================================
-- Harness del BUGFIX #4 — reproduce el caso 255/256 de la ruta 00L1
-- =============================================================================
-- Levanta solo las tablas CAI (con las columnas que agregaron los alters
-- 20260507/20260508) y stubs de las funciones que el SP llama. NO necesita la
-- base de produccion: corre en un cluster desechable.
--
--   initdb -D <tmp>\pgdata -U postgres -A trust
--   pg_ctl -D <tmp>\pgdata -o "-p 55432" start
--   createdb -h 127.0.0.1 -p 55432 -U postgres caitest
--
--   1) psql ... -d caitest -f Database/ddl_v3/tests/20260822_bug4_harness.sql
--   2) cargar las versiones vigentes de sp_adm_prepare_correlativo_cai_sync,
--      sp_adm_obtener_o_reservar_bloque_cai_ruta y
--      sp_adm_confirmar_correlativo_cai_sync (20260419 / 20260514 / 20260520)
--      -> el bloque reparte el correlativo 255, que ya esta tomado: el bug
--   3) psql ... -f Database/ddl_v3/20260822_bug4_prepare_avance_correlativo.sql
--   4) psql ... -f Database/ddl_v3/tests/20260822_bug4_verificacion.sql
-- =============================================================================

-- Guarda: este script borra el esquema public entero.
DO $$
BEGIN
    IF current_database() NOT IN ('caitest', 'siad_cai_test') THEN
        RAISE EXCEPTION 'Este harness borra el esquema public. Correlo en la base caitest, no en %.',
            current_database();
    END IF;
END $$;

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE TABLE public.cfg_company (company_id bigint PRIMARY KEY);

CREATE TABLE public.adm_cai_facturacion (
    cai_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES public.cfg_company (company_id),
    codigo_cai varchar(100) NOT NULL,
    prefijo_documento varchar(30) NOT NULL,
    rango_desde bigint NOT NULL,
    rango_hasta bigint NOT NULL,
    correlativo_actual bigint NOT NULL DEFAULT 0,
    vigencia_desde date NOT NULL,
    vigencia_hasta date,
    fecha_limite_emision date NOT NULL,
    estado_id smallint NOT NULL DEFAULT 1,
    tipo_documento_fiscal_id smallint NOT NULL DEFAULT 1,
    status_id smallint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),
    CONSTRAINT uq_adm_cai_facturacion_company UNIQUE (company_id, cai_id)
);

CREATE TABLE public.adm_cai_bloque_reservado (
    cai_bloque_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES public.cfg_company (company_id),
    cai_id bigint NOT NULL,
    usuario_asignado varchar(100),
    dispositivo_id varchar(100),
    ruta_codigo varchar(30),
    correlativo_desde bigint NOT NULL,
    correlativo_hasta bigint NOT NULL,
    correlativo_actual bigint NOT NULL,
    fecha_reserva date NOT NULL DEFAULT current_date,
    fecha_expiracion date,
    estado_codigo varchar(30) NOT NULL DEFAULT 'RESERVADO',
    status_id smallint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),
    CONSTRAINT fk_bloque_cai FOREIGN KEY (company_id, cai_id)
        REFERENCES public.adm_cai_facturacion (company_id, cai_id),
    CONSTRAINT uq_bloque UNIQUE (company_id, cai_bloque_id)
);

CREATE TABLE public.adm_cai_correlativo_emitido (
    cai_correlativo_emitido_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES public.cfg_company (company_id),
    cai_bloque_id bigint NOT NULL,
    cai_id bigint NOT NULL,
    correlativo bigint NOT NULL,
    numero_factura varchar(80) NOT NULL,
    cliente_id bigint,
    lectura_uuid varchar(100),
    factura_id bigint,
    estado_codigo varchar(30) NOT NULL DEFAULT 'PENDING_OFFLINE',
    fecha_emision timestamptz NOT NULL DEFAULT now(),
    fecha_confirmacion timestamptz,
    detalle_conflicto varchar(300),
    status_id smallint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),
    CONSTRAINT fk_emitido_bloque FOREIGN KEY (company_id, cai_bloque_id)
        REFERENCES public.adm_cai_bloque_reservado (company_id, cai_bloque_id),
    CONSTRAINT fk_emitido_cai FOREIGN KEY (company_id, cai_id)
        REFERENCES public.adm_cai_facturacion (company_id, cai_id),
    CONSTRAINT ck_emitido_status CHECK (status_id IN (0, 1))
);

-- Indices tal cual estan HOY en produccion (no parciales): el fix debe poder
-- reemplazarlos.
CREATE UNIQUE INDEX uq_adm_cai_correlativo_emitido_company_cai_corr
    ON public.adm_cai_correlativo_emitido (company_id, cai_id, correlativo);
CREATE UNIQUE INDEX uq_adm_cai_correlativo_emitido_company_numero
    ON public.adm_cai_correlativo_emitido (company_id, numero_factura);
CREATE UNIQUE INDEX uq_adm_cai_correlativo_emitido_company_lectura
    ON public.adm_cai_correlativo_emitido (company_id, lectura_uuid)
    WHERE lectura_uuid IS NOT NULL;

-- Stubs de lo que el SP llama y no forma parte de este fix.
CREATE FUNCTION public.sp_adm_actualizar_estado_cai(p_company_id bigint)
RETURNS integer LANGUAGE plpgsql AS $$
BEGIN
    RETURN 0;
END;
$$;

CREATE FUNCTION public.sp_adm_reservar_bloque_cai(
    p_company_id bigint,
    p_cai_id bigint,
    p_usuario_asignado varchar DEFAULT NULL,
    p_dispositivo_id varchar DEFAULT NULL,
    p_ruta_codigo varchar DEFAULT NULL,
    p_cantidad integer DEFAULT 100,
    p_fecha_expiracion date DEFAULT NULL,
    p_usuario varchar DEFAULT current_user
)
RETURNS TABLE (cai_bloque_id bigint) LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT 0::bigint WHERE false;
END;
$$;

-- ---------------------------------------------------------------------------
-- Datos del caso real: ruta 00L1, cai_id 7, bloque 251-500, contador en 254,
-- y los correlativos 255/256 reservados el 18-jul que nunca se confirmaron.
-- ---------------------------------------------------------------------------

INSERT INTO public.cfg_company (company_id) VALUES (2);

INSERT INTO public.adm_cai_facturacion
    (cai_id, company_id, codigo_cai, prefijo_documento, rango_desde, rango_hasta,
     correlativo_actual, vigencia_desde, fecha_limite_emision)
VALUES
    (7, 2, 'CAI-DEMO-7', '000-020-01', 1, 100000, 254, current_date - 200, current_date + 200);

INSERT INTO public.adm_cai_bloque_reservado
    (cai_bloque_id, company_id, cai_id, ruta_codigo, correlativo_desde,
     correlativo_hasta, correlativo_actual, fecha_reserva)
VALUES
    (18, 2, 7, '00L1', 251, 500, 254, current_date - 40);

INSERT INTO public.adm_cai_correlativo_emitido
    (cai_correlativo_emitido_id, company_id, cai_bloque_id, cai_id, correlativo,
     numero_factura, cliente_id, lectura_uuid, estado_codigo)
VALUES
    (149, 2, 18, 7, 255, '000-001-2000000255', 103100, 'uuid-julio-378', 'PENDING_SYNC'),
    (150, 2, 18, 7, 256, '000-001-2000000256', 103101, 'uuid-julio-218', 'PENDING_SYNC');
