-- =============================================================================
-- Integración Contable ↔ Comercial — Fase 2: asientos por módulo
-- Fecha: 2026-07-03 (v2: correcciones del code review del 2026-07-03)
-- Plan: docs/plans/2026-07-02-plan-integracion-contable-comercial.md §5 Fase 2
--       (pestaña "Asientos" de la pantalla Configuración de Integración
--       Contable: diario y tipo de partida por módulo).
--
-- Contenido:
--   1. AK tenant-safe en con_diario (company_id, journal_id) — prerequisito
--      para FK compuesta (mismo patrón que con_tipo_transaccion).
--   2. con_integracion_asiento — diario contable y tipo de partida que usará
--      cada módulo comercial al generar sus partidas (F3+). Complementa a
--      con_integracion_config (F1): los flags activo_* siguen en la cabecera.
--   3. Migración de instalaciones previas del script v1: FK de diario
--      tenant-safe y vocabulario de módulos alineado al motor de posteo.
--   4. con_integracion_config.activo_proveedores (módulo PROV).
--
-- Vocabulario de módulos (alineado con con_partida_hdr.module y con el
-- comentario de con_partida_pendiente.module de F1):
--   VENTAS      = lote de facturación (F3)
--   CAJA        = captación / abonos
--   BANCOS      = movimientos bancarios
--   NOTAS       = NC/ND (el motor hoy estampa module='VENTAS' en el hdr;
--                 la config por flujo permite diario/tipo propio)
--   MISCELANEOS = facturación misceláneos (ídem nota anterior)
--   PROV        = compromisos de proveedor (OrdenesPagoDirectoService)
--
-- Idempotente. Producción: aplicar SOLO en ventana de deploy acordada.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. AK tenant-safe en con_diario (necesaria para la FK compuesta)
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_con_diario_company_journal'
          AND conrelid = 'public.con_diario'::regclass
    ) THEN
        ALTER TABLE public.con_diario
            ADD CONSTRAINT uq_con_diario_company_journal UNIQUE (company_id, journal_id);
    END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 2. con_integracion_asiento
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.con_integracion_asiento (
    integracion_asiento_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,

    -- módulo comercial que genera la partida (espejo de los flags activo_*
    -- de con_integracion_config)
    module varchar(30) NOT NULL,

    -- diario y tipo de partida a usar al postear; NULL = aún sin configurar
    -- (el módulo no puede activarse hasta completarlos)
    journal_id bigint,
    type_id bigint,

    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),

    CONSTRAINT uq_con_integracion_asiento_company_module UNIQUE (company_id, module),
    CONSTRAINT fk_con_integracion_asiento_company
        FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    -- FKs compuestas tenant-safe: el diario y el tipo deben ser de la empresa
    CONSTRAINT fk_con_integracion_asiento_diario
        FOREIGN KEY (company_id, journal_id)
        REFERENCES public.con_diario (company_id, journal_id),
    CONSTRAINT fk_con_integracion_asiento_tipo
        FOREIGN KEY (company_id, type_id)
        REFERENCES public.con_tipo_transaccion (company_id, type_id),
    CONSTRAINT ck_con_integracion_asiento_module
        CHECK (module IN ('VENTAS', 'CAJA', 'BANCOS', 'NOTAS', 'MISCELANEOS', 'PROV'))
);

COMMENT ON TABLE public.con_integracion_asiento IS
'Diario contable y tipo de partida por módulo comercial (plan F2, pestaña Asientos). Una fila por empresa × módulo; los flags de activación viven en con_integracion_config. Módulos: VENTAS (lote facturación), CAJA, BANCOS, NOTAS, MISCELANEOS, PROV. Consumido por los posteos automáticos y el lote de facturación (F3+).';

-- -----------------------------------------------------------------------------
-- 3. Migración de instalaciones que aplicaron la v1 de este script
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_fk_single boolean;
BEGIN
    -- 3.1 FK de diario: si quedó la versión de una sola columna, reemplazarla
    SELECT EXISTS (
        SELECT 1
        FROM pg_constraint c
        WHERE c.conname = 'fk_con_integracion_asiento_diario'
          AND c.conrelid = 'public.con_integracion_asiento'::regclass
          AND array_length(c.conkey, 1) = 1
    ) INTO v_fk_single;

    IF v_fk_single THEN
        ALTER TABLE public.con_integracion_asiento
            DROP CONSTRAINT fk_con_integracion_asiento_diario;
        ALTER TABLE public.con_integracion_asiento
            ADD CONSTRAINT fk_con_integracion_asiento_diario
            FOREIGN KEY (company_id, journal_id)
            REFERENCES public.con_diario (company_id, journal_id);
    END IF;

    -- 3.2 Vocabulario: FACTURACION → VENTAS + CHECK con PROV
    IF EXISTS (
        SELECT 1
        FROM pg_constraint c
        WHERE c.conname = 'ck_con_integracion_asiento_module'
          AND c.conrelid = 'public.con_integracion_asiento'::regclass
          AND pg_get_constraintdef(c.oid) LIKE '%FACTURACION%'
    ) THEN
        ALTER TABLE public.con_integracion_asiento
            DROP CONSTRAINT ck_con_integracion_asiento_module;
        UPDATE public.con_integracion_asiento
            SET module = 'VENTAS', updated_at = now(), updated_by = 'ci-fase2-v2'
            WHERE module = 'FACTURACION';
        ALTER TABLE public.con_integracion_asiento
            ADD CONSTRAINT ck_con_integracion_asiento_module
            CHECK (module IN ('VENTAS', 'CAJA', 'BANCOS', 'NOTAS', 'MISCELANEOS', 'PROV'));
    END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 4. Flag de activación del módulo PROV en la cabecera F1
-- -----------------------------------------------------------------------------
ALTER TABLE public.con_integracion_config
    ADD COLUMN IF NOT EXISTS activo_proveedores boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.con_integracion_config.activo_proveedores IS
'Activa el posteo automático de compromisos de proveedor (módulo PROV) usando el diario/tipo de con_integracion_asiento.';
