-- =============================================================================
-- Integración Contable ↔ Comercial — Fase 3: lote manual de partidas de facturación
-- Fecha: 2026-07-03
-- Plan: docs/plans/2026-07-02-plan-integracion-contable-comercial.md §5 Fase 3
--       (D5: la sincronización de lecturas NUNCA postea; el contador genera el
--        lote después, desde la pantalla. D1: solo el motor único postea).
--
-- Contenido:
--   1. Snapshot dimensional en factura: categoria_servicio_id + con_medicion
--      (la categoría AL MOMENTO de facturar — requisito ERSAPS) + backfill.
--   2. Trigger BEFORE INSERT que llena el snapshot desde cliente_maestro.
--      NOTA DE DISEÑO (desvío consciente del plan): el plan pedía tocar
--      sp_lectura_v3; se usa un trigger para lograr el mismo efecto sin
--      redefinir el SP corazón del tarifario (menor riesgo, cubre además
--      cualquier otro flujo que emita facturas). sp_lectura_v3 NO se toca
--      y sigue sin postear.
--   3. con_lote_facturacion — historial de lotes generados.
--   4. con_partida_factura — tabla puente factura ↔ partida (idempotencia).
--   5. fn_con_preview_partidas_facturacion — preview agregado sin escribir.
--   6. sp_con_generar_partidas_facturacion — genera y postea vía motor único;
--      idempotente; encola en con_partida_pendiente si no hay período abierto.
--
-- Idempotente. Producción: aplicar SOLO en ventana de deploy acordada.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Snapshot dimensional en factura
-- -----------------------------------------------------------------------------
ALTER TABLE public.factura
    ADD COLUMN IF NOT EXISTS categoria_servicio_id integer,
    ADD COLUMN IF NOT EXISTS con_medicion boolean;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_factura_categoria_servicio'
          AND conrelid = 'public.factura'::regclass
    ) THEN
        ALTER TABLE public.factura
            ADD CONSTRAINT fk_factura_categoria_servicio
            FOREIGN KEY (categoria_servicio_id)
            REFERENCES public.categoria_servicio (categoria_servicio_id);
    END IF;
END $$;

COMMENT ON COLUMN public.factura.categoria_servicio_id IS
'Snapshot de la categoría del cliente AL MOMENTO de facturar (plan F3; los reportes por categoría ERSAPS usan este valor, no el actual del cliente).';
COMMENT ON COLUMN public.factura.con_medicion IS
'Snapshot de si el cliente tenía medidor al facturar (dimensión de la matriz de integración contable).';

-- Backfill de facturas existentes (solo las que no tienen snapshot).
UPDATE public.factura f
SET categoria_servicio_id = cm.categoria_servicio_id,
    con_medicion = cm.maestro_cliente_tiene_medidor
FROM public.cliente_maestro cm
WHERE cm.company_id = f.company_id
  AND cm.maestro_cliente_clave = f.clientecodigo
  AND f.categoria_servicio_id IS NULL;

-- -----------------------------------------------------------------------------
-- 2. Trigger de snapshot al emitir
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_factura_snapshot_dimensional()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.categoria_servicio_id IS NULL OR NEW.con_medicion IS NULL THEN
        SELECT COALESCE(NEW.categoria_servicio_id, cm.categoria_servicio_id),
               COALESCE(NEW.con_medicion, cm.maestro_cliente_tiene_medidor)
        INTO NEW.categoria_servicio_id, NEW.con_medicion
        FROM public.cliente_maestro cm
        WHERE cm.company_id = NEW.company_id
          AND cm.maestro_cliente_clave = NEW.clientecodigo
        LIMIT 1;
    END IF;
    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_factura_snapshot_dimensional ON public.factura;
CREATE TRIGGER trg_factura_snapshot_dimensional
    BEFORE INSERT ON public.factura
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_factura_snapshot_dimensional();

-- -----------------------------------------------------------------------------
-- 3. con_lote_facturacion — historial de lotes
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.con_lote_facturacion (
    lote_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,

    fecha_desde date NOT NULL,
    fecha_hasta date NOT NULL,
    modo_agrupacion varchar(20) NOT NULL DEFAULT 'DIA',

    facturas integer NOT NULL DEFAULT 0,
    polizas integer NOT NULL DEFAULT 0,
    encoladas integer NOT NULL DEFAULT 0,
    total numeric(18,2) NOT NULL DEFAULT 0,

    -- 1=GENERADO, 2=PARCIAL (algún grupo encolado), 3=ENCOLADO (todo sin período)
    status_id smallint NOT NULL DEFAULT 1,

    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,

    CONSTRAINT fk_con_lote_facturacion_company
        FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT ck_con_lote_facturacion_modo
        CHECK (modo_agrupacion IN ('DIA', 'PERIODO')),
    CONSTRAINT ck_con_lote_facturacion_status
        CHECK (status_id IN (1, 2, 3)),
    CONSTRAINT ck_con_lote_facturacion_rango
        CHECK (fecha_desde <= fecha_hasta)
);

CREATE INDEX IF NOT EXISTS ix_con_lote_facturacion_company
    ON public.con_lote_facturacion (company_id, created_at DESC);

COMMENT ON TABLE public.con_lote_facturacion IS
'Historial de lotes de partidas de facturación (plan F3). Cada corrida de sp_con_generar_partidas_facturacion que encuentra facturas crea un lote. Estados: 1=GENERADO, 2=PARCIAL, 3=ENCOLADO.';

-- -----------------------------------------------------------------------------
-- 4. con_partida_factura — puente factura ↔ partida (idempotencia del lote)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.con_partida_factura (
    partida_factura_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    factura_id integer NOT NULL,
    lote_id bigint NOT NULL,
    poliza_id bigint NOT NULL,

    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,

    CONSTRAINT uq_con_partida_factura_factura UNIQUE (company_id, factura_id),
    CONSTRAINT fk_con_partida_factura_company
        FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_con_partida_factura_factura
        FOREIGN KEY (factura_id) REFERENCES public.factura (id),
    CONSTRAINT fk_con_partida_factura_lote
        FOREIGN KEY (lote_id) REFERENCES public.con_lote_facturacion (lote_id) ON DELETE CASCADE,
    CONSTRAINT fk_con_partida_factura_poliza
        FOREIGN KEY (poliza_id) REFERENCES public.con_partida_hdr (poliza_id)
);

CREATE INDEX IF NOT EXISTS ix_con_partida_factura_poliza
    ON public.con_partida_factura (company_id, poliza_id);

COMMENT ON TABLE public.con_partida_factura IS
'Puente factura ↔ partida del lote de facturación (plan F3). Una factura solo puede pertenecer a un lote posteado (uq company+factura): correr el lote dos veces no duplica.';

-- -----------------------------------------------------------------------------
-- 5. Resolución de dimensiones según el modo configurado (helper interno)
-- -----------------------------------------------------------------------------
-- Devuelve la cuenta para un uso aplicando el modo de granularidad de
-- con_integracion_config: GENERAL ignora dimensiones, POR_SERVICIO pasa solo
-- servicio, POR_SERVICIO_CATEGORIA pasa todo. Reusa fn_con_resolver_cuenta (F1).
CREATE OR REPLACE FUNCTION public.fn_con_resolver_cuenta_modo(
    p_company_id bigint,
    p_uso varchar,
    p_modo varchar,
    p_servicio_id bigint,
    p_categoria_servicio_id integer,
    p_con_medicion boolean
) RETURNS bigint
LANGUAGE sql
STABLE
AS $function$
    SELECT CASE p_modo
        WHEN 'POR_SERVICIO' THEN
            public.fn_con_resolver_cuenta(p_company_id, p_uso, p_servicio_id, NULL, NULL)
        WHEN 'POR_SERVICIO_CATEGORIA' THEN
            public.fn_con_resolver_cuenta(p_company_id, p_uso, p_servicio_id, p_categoria_servicio_id, p_con_medicion)
        ELSE
            public.fn_con_resolver_cuenta(p_company_id, p_uso, NULL, NULL, NULL)
    END;
$function$;

-- -----------------------------------------------------------------------------
-- 6. Preview del lote (no escribe nada)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_con_preview_partidas_facturacion(
    p_company_id bigint,
    p_fecha_desde date,
    p_fecha_hasta date,
    p_modo_agrupacion varchar DEFAULT 'DIA'
) RETURNS TABLE (
    fecha_partida date,
    uso varchar,
    account_id bigint,
    account_code varchar,
    account_name varchar,
    debe numeric,
    haber numeric,
    facturas bigint
)
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_modo_ventas varchar;
    v_modo_cxc varchar;
BEGIN
    SELECT c.modo_ventas, c.modo_cxc
    INTO v_modo_ventas, v_modo_cxc
    FROM public.con_integracion_config c
    WHERE c.company_id = p_company_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'La empresa % no tiene configuración de integración contable (pantalla Integración Contable / perfil ERSAPS).', p_company_id;
    END IF;

    RETURN QUERY
    WITH candidatas AS (
        SELECT f.id, f.fechaemision, f.categoria_servicio_id, f.con_medicion,
               CASE WHEN upper(p_modo_agrupacion) = 'PERIODO' THEN p_fecha_hasta ELSE f.fechaemision END AS fecha_grupo
        FROM public.factura f
        WHERE f.company_id = p_company_id
          AND f.tipofacturacion = 'S'
          AND f.tipofactura = 'F'
          AND COALESCE(f.estado_id, 1) <> 3
          AND COALESCE(f.estado, 'A') <> 'N'
          AND f.fechaemision BETWEEN p_fecha_desde AND p_fecha_hasta
          AND NOT EXISTS (
              SELECT 1 FROM public.con_partida_factura pf
              WHERE pf.company_id = f.company_id AND pf.factura_id = f.id)
    ),
    lineas AS (
        SELECT c.fecha_grupo, c.id AS factura_id, fd.montovalor,
               s.servicio_id, c.categoria_servicio_id, c.con_medicion
        FROM candidatas c
        JOIN public.factura_detalle fd ON fd.factura_id = c.id
        LEFT JOIN public.adm_servicio s
               ON s.company_id = p_company_id
              AND upper(btrim(s.codigo)) = upper(btrim(fd.tiposervicio))
        WHERE COALESCE(fd.montovalor, 0) <> 0
    ),
    resueltas AS (
        SELECT l.fecha_grupo, l.factura_id, l.montovalor,
               public.fn_con_resolver_cuenta_modo(p_company_id, 'INGRESO', v_modo_ventas,
                   l.servicio_id, l.categoria_servicio_id, l.con_medicion) AS ingreso_account,
               public.fn_con_resolver_cuenta_modo(p_company_id, 'CXC', v_modo_cxc,
                   l.servicio_id, l.categoria_servicio_id, l.con_medicion) AS cxc_account
        FROM lineas l
    ),
    ambos_lados AS (
        SELECT r.fecha_grupo, 'CXC'::varchar AS uso_lado, r.cxc_account AS cuenta,
               r.montovalor AS debe, 0::numeric AS haber, r.factura_id
        FROM resueltas r
        UNION ALL
        SELECT r.fecha_grupo, 'INGRESO'::varchar, r.ingreso_account,
               0::numeric, r.montovalor, r.factura_id
        FROM resueltas r
    )
    SELECT a.fecha_grupo,
           a.uso_lado,
           a.cuenta,
           pc.code,
           pc.name,
           round(SUM(a.debe), 2),
           round(SUM(a.haber), 2),
           COUNT(DISTINCT a.factura_id)
    FROM ambos_lados a
    JOIN public.con_plan_cuentas pc ON pc.account_id = a.cuenta
    GROUP BY a.fecha_grupo, a.uso_lado, a.cuenta, pc.code, pc.name
    ORDER BY a.fecha_grupo, a.uso_lado DESC, pc.code;
END;
$function$;

COMMENT ON FUNCTION public.fn_con_preview_partidas_facturacion(bigint, date, date, varchar) IS
'Preview del lote de partidas de facturación (plan F3): líneas agregadas por fecha de partida × uso × cuenta, sin escribir nada. Lanza la misma excepción que el lote real si alguna combinación no resuelve cuenta.';

-- -----------------------------------------------------------------------------
-- 7. Generación del lote (postea vía motor único)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sp_con_generar_partidas_facturacion(
    p_company_id bigint,
    p_fecha_desde date,
    p_fecha_hasta date,
    p_modo_agrupacion varchar DEFAULT 'DIA',
    p_usuario text DEFAULT current_user
) RETURNS TABLE (
    lote_id bigint,
    polizas integer,
    facturas integer,
    encoladas integer,
    total numeric
)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_config record;
    v_asiento record;
    v_lote_id bigint;
    v_grupo record;
    v_period_id bigint;
    v_poliza_id bigint;
    v_seq integer;
    v_line smallint;
    v_total_grupo numeric;
    v_polizas integer := 0;
    v_facturas integer := 0;
    v_encoladas integer := 0;
    v_total numeric := 0;
    v_linea record;
BEGIN
    IF upper(COALESCE(p_modo_agrupacion, '')) NOT IN ('DIA', 'PERIODO') THEN
        RAISE EXCEPTION 'Modo de agrupación no soportado: %. Use DIA o PERIODO.', p_modo_agrupacion;
    END IF;

    SELECT c.modo_ventas, c.modo_cxc, c.encolar_sin_periodo
    INTO v_config
    FROM public.con_integracion_config c
    WHERE c.company_id = p_company_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'La empresa % no tiene configuración de integración contable.', p_company_id;
    END IF;

    -- Diario y tipo del módulo VENTAS (pestaña Asientos de F2)
    SELECT a.journal_id, a.type_id
    INTO v_asiento
    FROM public.con_integracion_asiento a
    WHERE a.company_id = p_company_id AND a.module = 'VENTAS';
    IF NOT FOUND OR v_asiento.journal_id IS NULL OR v_asiento.type_id IS NULL THEN
        RAISE EXCEPTION 'El módulo VENTAS no tiene diario y tipo de partida configurados (pestaña Asientos de Integración Contable).';
    END IF;

    -- Candidatas a tabla temporal (excluye anuladas y ya posteadas)
    DROP TABLE IF EXISTS pg_temp.tmp_lote_candidatas;
    CREATE TEMP TABLE tmp_lote_candidatas ON COMMIT DROP AS
    SELECT f.id AS factura_id, f.fechaemision, f.categoria_servicio_id, f.con_medicion,
           CASE WHEN upper(p_modo_agrupacion) = 'PERIODO' THEN p_fecha_hasta ELSE f.fechaemision END AS fecha_grupo
    FROM public.factura f
    WHERE f.company_id = p_company_id
      AND f.tipofacturacion = 'S'
      AND f.tipofactura = 'F'
      AND COALESCE(f.estado_id, 1) <> 3
      AND COALESCE(f.estado, 'A') <> 'N'
      AND f.fechaemision BETWEEN p_fecha_desde AND p_fecha_hasta
      AND NOT EXISTS (
          SELECT 1 FROM public.con_partida_factura pf
          WHERE pf.company_id = f.company_id AND pf.factura_id = f.id);

    IF NOT EXISTS (SELECT 1 FROM tmp_lote_candidatas) THEN
        RETURN QUERY SELECT NULL::bigint, 0, 0, 0, 0::numeric;
        RETURN;
    END IF;

    INSERT INTO public.con_lote_facturacion
        (company_id, fecha_desde, fecha_hasta, modo_agrupacion, created_by)
    VALUES (p_company_id, p_fecha_desde, p_fecha_hasta, upper(p_modo_agrupacion), p_usuario)
    RETURNING con_lote_facturacion.lote_id INTO v_lote_id;

    -- Un grupo = una partida (por día de emisión, o una sola si PERIODO)
    FOR v_grupo IN
        SELECT c.fecha_grupo, COUNT(*) AS n_facturas
        FROM tmp_lote_candidatas c
        GROUP BY c.fecha_grupo
        ORDER BY c.fecha_grupo
    LOOP
        -- Período contable abierto que cubra la fecha del grupo (regla D6)
        SELECT p.period_id INTO v_period_id
        FROM public.con_periodo_contable p
        WHERE p.company_id = p_company_id
          AND COALESCE(p.status_id, 0) = 0
          AND v_grupo.fecha_grupo BETWEEN p.start_date::date AND p.end_date::date
        ORDER BY p.start_date DESC
        LIMIT 1;

        IF v_period_id IS NULL THEN
            IF v_config.encolar_sin_periodo THEN
                INSERT INTO public.con_partida_pendiente
                    (company_id, module, origen_tipo, origen_id, fecha_documento,
                     descripcion, payload, motivo, created_by)
                VALUES
                    (p_company_id, 'VENTAS', 'LOTE_FACTURACION', v_lote_id, v_grupo.fecha_grupo,
                     format('Lote facturación %s..%s: %s factura(s) del %s sin período contable abierto',
                            p_fecha_desde, p_fecha_hasta, v_grupo.n_facturas, v_grupo.fecha_grupo),
                     jsonb_build_object(
                         'fecha_desde', p_fecha_desde,
                         'fecha_hasta', p_fecha_hasta,
                         'fecha_partida', v_grupo.fecha_grupo,
                         'modo_agrupacion', upper(p_modo_agrupacion),
                         'facturas', v_grupo.n_facturas),
                     'SIN_PERIODO_ABIERTO', p_usuario);
                v_encoladas := v_encoladas + v_grupo.n_facturas;
                CONTINUE;
            END IF;
            RAISE EXCEPTION 'No hay período contable abierto para la fecha % y la configuración no permite encolar.', v_grupo.fecha_grupo;
        END IF;

        -- Total del grupo (suma del detalle = lo facturado en el rango)
        SELECT round(COALESCE(SUM(fd.montovalor), 0), 2) INTO v_total_grupo
        FROM tmp_lote_candidatas c
        JOIN public.factura_detalle fd ON fd.factura_id = c.factura_id
        WHERE c.fecha_grupo = v_grupo.fecha_grupo;

        IF v_total_grupo = 0 THEN
            CONTINUE;
        END IF;

        -- Encabezado (misma convención de numeración del motor)
        SELECT COUNT(*) + 1 INTO v_seq
        FROM public.con_partida_hdr h
        WHERE h.company_id = p_company_id;

        INSERT INTO public.con_partida_hdr (
            company_id, journal_id, period_id, module, document_type,
            document_id, document_number, poliza_number, sequence_number,
            poliza_date, description, status, source_reference,
            created_at, created_by, type_id, total_debit, total_credit
        ) VALUES (
            p_company_id, v_asiento.journal_id, v_period_id, 'VENTAS', 'LOTE_FAC',
            v_lote_id, format('LOTE-%s-%s', v_lote_id, to_char(v_grupo.fecha_grupo, 'YYYYMMDD')),
            p_company_id::text || '-' || EXTRACT(YEAR FROM v_grupo.fecha_grupo)::text || '-' || lpad(v_seq::text, 6, '0'),
            v_seq, v_grupo.fecha_grupo,
            format('Lote de facturación %s (%s factura(s))', to_char(v_grupo.fecha_grupo, 'DD/MM/YYYY'), v_grupo.n_facturas),
            0, format('LOTE-%s', v_lote_id), now(), p_usuario, v_asiento.type_id, 0, 0
        )
        RETURNING poliza_id INTO v_poliza_id;

        -- Líneas: Debe CxC / Haber Ingresos, agregadas por cuenta resuelta
        v_line := 0;
        FOR v_linea IN
            WITH lineas AS (
                SELECT fd.montovalor, s.servicio_id, c.categoria_servicio_id, c.con_medicion
                FROM tmp_lote_candidatas c
                JOIN public.factura_detalle fd ON fd.factura_id = c.factura_id
                LEFT JOIN public.adm_servicio s
                       ON s.company_id = p_company_id
                      AND upper(btrim(s.codigo)) = upper(btrim(fd.tiposervicio))
                WHERE c.fecha_grupo = v_grupo.fecha_grupo
                  AND COALESCE(fd.montovalor, 0) <> 0
            ),
            resueltas AS (
                SELECT l.montovalor,
                       public.fn_con_resolver_cuenta_modo(p_company_id, 'INGRESO', v_config.modo_ventas,
                           l.servicio_id, l.categoria_servicio_id, l.con_medicion) AS ingreso_account,
                       public.fn_con_resolver_cuenta_modo(p_company_id, 'CXC', v_config.modo_cxc,
                           l.servicio_id, l.categoria_servicio_id, l.con_medicion) AS cxc_account
                FROM lineas l
            )
            SELECT cuenta, SUM(debe) AS debe, SUM(haber) AS haber
            FROM (
                SELECT r.cxc_account AS cuenta, r.montovalor AS debe, 0::numeric AS haber FROM resueltas r
                UNION ALL
                SELECT r.ingreso_account, 0::numeric, r.montovalor FROM resueltas r
            ) x
            GROUP BY cuenta
            ORDER BY SUM(debe) = 0, cuenta
        LOOP
            v_line := v_line + 1;
            INSERT INTO public.con_partida_dtl (
                company_id, poliza_id, line_number, account_id,
                debit_amount, credit_amount, description, source_document
            ) VALUES (
                p_company_id, v_poliza_id, v_line, v_linea.cuenta,
                round(v_linea.debe, 2), round(v_linea.haber, 2),
                CASE WHEN v_linea.debe > 0 THEN 'CxC abonados — lote de facturación'
                     ELSE 'Ingresos por servicios — lote de facturación' END,
                format('LOTE-%s', v_lote_id)
            );
        END LOOP;

        UPDATE public.con_partida_hdr h
        SET total_debit = v_total_grupo, total_credit = v_total_grupo
        WHERE h.poliza_id = v_poliza_id;

        -- Motor único (D1): sp_con_postear_poliza valida balance y actualiza saldos
        PERFORM public.sp_con_postear_poliza(p_company_id, v_poliza_id, p_usuario);

        -- Marcar facturas del grupo (idempotencia)
        INSERT INTO public.con_partida_factura (company_id, factura_id, lote_id, poliza_id, created_by)
        SELECT p_company_id, c.factura_id, v_lote_id, v_poliza_id, p_usuario
        FROM tmp_lote_candidatas c
        WHERE c.fecha_grupo = v_grupo.fecha_grupo;

        -- Si esta fecha estaba encolada de una corrida anterior, marcar procesada
        UPDATE public.con_partida_pendiente pp
        SET status_id = 2, poliza_id = v_poliza_id, procesada_at = now(), procesada_by = p_usuario,
            updated_at = now(), updated_by = p_usuario
        WHERE pp.company_id = p_company_id
          AND pp.module = 'VENTAS'
          AND pp.origen_tipo = 'LOTE_FACTURACION'
          AND pp.status_id = 1
          AND pp.fecha_documento = v_grupo.fecha_grupo;

        v_polizas := v_polizas + 1;
        v_facturas := v_facturas + v_grupo.n_facturas;
        v_total := v_total + v_total_grupo;
    END LOOP;

    UPDATE public.con_lote_facturacion l
    SET facturas = v_facturas, polizas = v_polizas, encoladas = v_encoladas, total = v_total,
        status_id = CASE
            WHEN v_polizas > 0 AND v_encoladas > 0 THEN 2
            WHEN v_polizas = 0 AND v_encoladas > 0 THEN 3
            ELSE 1
        END
    WHERE l.lote_id = v_lote_id;

    RETURN QUERY SELECT v_lote_id, v_polizas, v_facturas, v_encoladas, v_total;
END;
$function$;

COMMENT ON FUNCTION public.sp_con_generar_partidas_facturacion(bigint, date, date, varchar, text) IS
'Lote manual de partidas de facturación (plan F3, D5/D10). Toma facturas del rango sin partida (excluye anuladas), arma Debe CxC / Haber Ingresos con fn_con_resolver_cuenta según los modos configurados, postea vía sp_con_postear_poliza (motor único D1) y marca las facturas en con_partida_factura (idempotente). Sin período abierto: encola en con_partida_pendiente si la config lo permite. Devuelve (lote_id, polizas, facturas, encoladas, total).';
