-- =============================================================================
-- Integración Contable ↔ Comercial — Fase 2: asientos por módulo
-- Fecha: 2026-07-03
-- Plan: docs/plans/2026-07-02-plan-integracion-contable-comercial.md §5 Fase 2
--       (pestaña "Asientos" de la pantalla Configuración de Integración
--       Contable: diario y tipo de partida por módulo).
--
-- Contenido:
--   1. con_integracion_asiento — diario contable y tipo de partida que usará
--      cada módulo comercial al generar sus partidas (F3+). Complementa a
--      con_integracion_config (F1): los flags activo_* siguen en la cabecera.
--
-- Idempotente. Producción: aplicar SOLO en ventana de deploy acordada.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.con_integracion_asiento (
    integracion_asiento_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,

    -- módulo comercial que genera la partida (espejo de los flags activo_*
    -- de con_integracion_config)
    module varchar(30) NOT NULL,

    -- diario y tipo de partida a usar al postear; NULL = aún sin configurar
    -- (el módulo no puede activarse hasta completarlos)
    journal_id bigint,
    type_id bigint,

    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),

    CONSTRAINT uq_con_integracion_asiento_company_module UNIQUE (company_id, module),
    CONSTRAINT fk_con_integracion_asiento_company
        FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_con_integracion_asiento_diario
        FOREIGN KEY (journal_id) REFERENCES public.con_diario (journal_id),
    -- FK compuesta tenant-safe (con_tipo_transaccion tiene AK company_id+type_id)
    CONSTRAINT fk_con_integracion_asiento_tipo
        FOREIGN KEY (company_id, type_id)
        REFERENCES public.con_tipo_transaccion (company_id, type_id),
    CONSTRAINT ck_con_integracion_asiento_module
        CHECK (module IN ('FACTURACION', 'CAJA', 'BANCOS', 'NOTAS', 'MISCELANEOS'))
);

COMMENT ON TABLE public.con_integracion_asiento IS
'Diario contable y tipo de partida por módulo comercial (plan F2, pestaña Asientos). Una fila por empresa × módulo; los flags de activación viven en con_integracion_config. Consumido por los posteos automáticos y el lote de facturación (F3+).';
