-- =============================================================================
-- App Lectores (Flutter) — Catálogo de condiciones de lectura administrable
-- Fecha: 2026-07-06
-- Spec: app_lectores/docs/SPEC_CONDICIONES_LECTURA.md (cierra el TODO(l8) de L7)
-- Plan: app_lectores/docs/PLAN_EJECUCION_2026-07.md (fases L0–L12, decisión A6)
--
-- Contexto: L7 (captura de lectura) necesita el catálogo de condiciones con su
-- `tipo` (N/MIN/PND/PD) para decidir si se exige lectura y cómo calcula el motor
-- V3 el consumo. Hoy NO hay fuente: el WS Java `/CondicionesLectura` fue removido
-- y la tabla `condicion_lectura` dropeada; L7 dejó un seed provisional en la app.
--
-- Decisión de negocio (2026-07-06): las condiciones se administran POR EMPRESA.
--
-- Dos niveles (spec §2):
--   1. adm_condicion_lectura_tipo — referencia GLOBAL de tipos, acoplada al motor
--      V3 (sp_adm_calcular_factura_lectura ramifica por tipo: N pide lectura;
--      MIN/PND → consumo 0; PD → promedio). NO editable por el admin: si pudiera
--      inventar un tipo, el motor no sabría calcularlo.
--   2. adm_condicion_lectura — catálogo administrable POR EMPRESA (A6,
--      ICompanyScopedEntity). El admin crea/renombra/desactiva condiciones y elige
--      "esta se comporta como Promedio", pero apunta SIEMPRE a un tipo fijo.
--
-- Ampliación tarifaria (spec §5.3): `historicomedicion.condicion` (columna
-- destino de sp_lectura_v3.p_condicion_lectura) es varchar(3) → se amplía a
-- varchar(10). Es BACKWARD-COMPATIBLE: los params de sp_lectura_v3 y
-- sp_adm_calcular_factura_lectura ya son `character varying` sin límite y el motor
-- usa `text` internamente (acepta MIN/PND/PD sin truncar); el único punto angosto
-- era el almacenamiento. El WS viejo sigue mandando 1 char (ya trunca en C#), que
-- entra sin problema en la columna ancha; el MobileApi manda el código completo.
-- Sin cambio de comportamiento del motor (la regresión LecturaV3Tests queda igual).
--
-- Idempotente. El WS viejo (WSappLectores) y usuarioapc quedan intactos.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. adm_condicion_lectura_tipo — referencia GLOBAL de tipos (acople al motor V3)
--    No editable por el admin. Vocabulario fijo N/MIN/PND/PD.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.adm_condicion_lectura_tipo (
    tipo             varchar(10) PRIMARY KEY,   -- N, MIN, PND, PD
    descripcion      varchar(60) NOT NULL,      -- "Normal", "Consumo mínimo", ...
    requiere_lectura boolean     NOT NULL       -- true solo para N (semántica del motor)
);

COMMENT ON TABLE public.adm_condicion_lectura_tipo IS
'Referencia GLOBAL de tipos de condición de lectura (N/MIN/PND/PD), acoplada al motor V3 (sp_adm_calcular_factura_lectura ramifica por tipo). No editable por el admin: no se inventan tipos porque el motor no sabría calcularlos. requiere_lectura=true solo para N.';

-- Seed del vocabulario fijo (idempotente; descripción se refresca si cambia).
INSERT INTO public.adm_condicion_lectura_tipo (tipo, descripcion, requiere_lectura)
VALUES
    ('N',   'Normal',          true),
    ('MIN', 'Consumo mínimo',  false),
    ('PND', 'Pendiente',       false),
    ('PD',  'Promedio',        false)
ON CONFLICT (tipo) DO UPDATE
    SET descripcion      = EXCLUDED.descripcion,
        requiere_lectura = EXCLUDED.requiere_lectura;

-- -----------------------------------------------------------------------------
-- 2. adm_condicion_lectura — catálogo administrable POR EMPRESA (A6)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.adm_condicion_lectura (
    condicion_lectura_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           bigint      NOT NULL,
    codigo               varchar(10) NOT NULL,             -- visible al lector (editable)
    descripcion          varchar(60) NOT NULL,
    tipo                 varchar(10) NOT NULL,             -- FK → tipo global (comportamiento)
    facturacion          char(1)     NOT NULL DEFAULT 'S', -- S/N
    aplica_descuento     char(1)     NOT NULL DEFAULT 'N', -- S/N
    orden                int         NOT NULL DEFAULT 0,
    activo               boolean     NOT NULL DEFAULT true,
    created_at           timestamptz NOT NULL DEFAULT now(),
    created_by           varchar(100) NOT NULL DEFAULT current_user,
    updated_at           timestamptz,
    updated_by           varchar(100),

    CONSTRAINT uq_adm_condicion_lectura_company_codigo UNIQUE (company_id, codigo),
    CONSTRAINT fk_adm_condicion_lectura_company
        FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_adm_condicion_lectura_tipo
        FOREIGN KEY (tipo) REFERENCES public.adm_condicion_lectura_tipo (tipo) ON DELETE RESTRICT,
    CONSTRAINT ck_adm_condicion_lectura_facturacion CHECK (facturacion IN ('S', 'N')),
    CONSTRAINT ck_adm_condicion_lectura_aplica_descuento CHECK (aplica_descuento IN ('S', 'N'))
);

-- Búsqueda del endpoint: activas por empresa, ordenadas.
CREATE INDEX IF NOT EXISTS ix_adm_condicion_lectura_company_orden
    ON public.adm_condicion_lectura (company_id, orden)
    WHERE activo;

COMMENT ON TABLE public.adm_condicion_lectura IS
'Catálogo de condiciones de lectura administrable POR EMPRESA (A6, ICompanyScopedEntity). codigo/descripcion/orden/activo/facturacion/aplica_descuento editables; tipo elegido de adm_condicion_lectura_tipo (comportamiento del motor V3, no editable). GET /api/condiciones (apc.MobileApi) lo expone scopeado por la sesión; requiereLectura se deriva del tipo en el server.';

-- -----------------------------------------------------------------------------
-- 3. Seed inicial POR EMPRESA: las 4 condiciones estándar (codigo = tipo).
--    Idempotente (solo inserta las que faltan). El ABM las ajusta después.
-- -----------------------------------------------------------------------------
INSERT INTO public.adm_condicion_lectura
    (company_id, codigo, descripcion, tipo, facturacion, aplica_descuento, orden, activo, created_by)
SELECT c.company_id, t.tipo, t.descripcion, t.tipo, 'S', 'N', t.orden, true, 'seed-condiciones'
FROM public.cfg_company c
CROSS JOIN (VALUES
    ('N',   'Normal',         1),
    ('MIN', 'Consumo mínimo', 2),
    ('PND', 'Pendiente',      3),
    ('PD',  'Promedio',       4)
) AS t(tipo, descripcion, orden)
WHERE NOT EXISTS (
    SELECT 1 FROM public.adm_condicion_lectura a
    WHERE a.company_id = c.company_id
      AND a.codigo = t.tipo
);

-- -----------------------------------------------------------------------------
-- 4. Ampliación tarifaria: historicomedicion.condicion varchar(3) → varchar(10).
--    Columna destino del código de condición que persiste sp_lectura_v3.
--    Idempotente (solo amplía si hoy es más angosta). Backward-compatible: no
--    reescribe la tabla ni cambia el comportamiento del motor.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_len integer;
BEGIN
    SELECT character_maximum_length
    INTO v_len
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'historicomedicion'
      AND column_name = 'condicion';

    IF v_len IS NOT NULL AND v_len < 10 THEN
        ALTER TABLE public.historicomedicion
            ALTER COLUMN condicion TYPE varchar(10);
    END IF;
END$$;

COMMENT ON COLUMN public.historicomedicion.condicion IS
'Código de la condición de lectura aplicada (adm_condicion_lectura.codigo). varchar(10) desde 2026-07-06 (era varchar(3)) para admitir códigos administrables sin truncar. El WS viejo sigue mandando 1 char (compatible); el MobileApi manda el código completo.';
