-- =============================================================================
-- SAR-Compliance fase 1 — Catálogos + adm_establecimiento (multi-empresa)
-- Fecha: 2026-05-07
-- Plan: Prestadoras/docs/PLAN_SAR_COMPLIANCE_2026-05-06.md
-- Idempotente: puede aplicarse varias veces sin efectos secundarios.
-- =============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1) cfg_tipo_documento_fiscal — catálogo SAR Acuerdo 481-2017
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cfg_tipo_documento_fiscal (
    tipo_documento_fiscal_id smallint PRIMARY KEY,
    codigo varchar(10) NOT NULL UNIQUE,
    descripcion varchar(80) NOT NULL,
    es_comprobante_fiscal boolean NOT NULL,
    es_documento_complementario boolean NOT NULL,
    requiere_factura_origen boolean NOT NULL DEFAULT false,
    activo boolean NOT NULL DEFAULT true
);

INSERT INTO public.cfg_tipo_documento_fiscal
    (tipo_documento_fiscal_id, codigo, descripcion, es_comprobante_fiscal, es_documento_complementario, requiere_factura_origen) VALUES
    ( 1, 'FAC',  'Factura',                       true,  false, false),
    ( 2, 'FACP', 'Factura prevalorada',           true,  false, false),
    ( 3, 'TIK',  'Ticket',                        true,  false, false),
    ( 4, 'BOL',  'Boleta de compra',              true,  false, false),
    ( 5, 'HON',  'Recibo por honorarios',         true,  false, false),
    ( 6, 'NC',   'Nota de crédito',               false, true,  true),
    ( 7, 'ND',   'Nota de débito',                false, true,  true),
    ( 8, 'GR',   'Guía de remisión',              false, true,  false),
    ( 9, 'CRT',  'Comprobante de retención',      false, true,  false),
    (10, 'REC',  'Recibo de servicio público',    true,  false, false)
ON CONFLICT (tipo_documento_fiscal_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 2) cfg_motivo_anulacion — catálogo motivos NC
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cfg_motivo_anulacion (
    motivo_anulacion_id smallint PRIMARY KEY,
    codigo varchar(20) NOT NULL UNIQUE,
    descripcion varchar(150) NOT NULL,
    aplica_factura boolean NOT NULL DEFAULT true,
    aplica_recibo boolean NOT NULL DEFAULT true,
    activo boolean NOT NULL DEFAULT true
);

INSERT INTO public.cfg_motivo_anulacion (motivo_anulacion_id, codigo, descripcion) VALUES
    (1, 'ERROR_LECTURA',     'Error en lectura del medidor'),
    (2, 'ERROR_TARIFA',      'Error en aplicación de tarifa'),
    (3, 'ERROR_DATOS',       'Error en datos del cliente'),
    (4, 'DUPLICADA',         'Factura emitida en duplicado'),
    (5, 'EXONERACION',       'Aplicación posterior de exoneración'),
    (6, 'CORRECCION_PERIODO','Corrección de período'),
    (7, 'OTRO',              'Otro motivo (debe detallarse en observaciones)')
ON CONFLICT (motivo_anulacion_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 3) cfg_estado_documento_fiscal — estados numéricos para documentos
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cfg_estado_documento_fiscal (
    estado_id smallint PRIMARY KEY,
    codigo varchar(20) NOT NULL UNIQUE,
    descripcion varchar(80) NOT NULL,
    activo boolean NOT NULL DEFAULT true
);

INSERT INTO public.cfg_estado_documento_fiscal (estado_id, codigo, descripcion) VALUES
    (1, 'EMITIDA',   'Documento emitido'),
    (2, 'APLICADA',  'Documento aplicado a saldo cliente'),
    (3, 'ANULADA',   'Documento anulado por NC'),
    (4, 'PENDIENTE', 'Pendiente de sincronización')
ON CONFLICT (estado_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 4) adm_establecimiento — N establecimientos por empresa (multi-empresa)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.adm_establecimiento (
    establecimiento_id bigint GENERATED BY DEFAULT AS IDENTITY,
    company_id bigint NOT NULL,

    -- identificación SAR
    codigo varchar(20) NOT NULL,
    nombre varchar(200) NOT NULL,

    -- datos fiscales (pueden diferir de la empresa madre)
    rtn_emisor varchar(20) NOT NULL,
    razon_social_emisor varchar(200) NOT NULL,
    direccion_emisor varchar(300) NOT NULL,
    telefono varchar(50),
    correo varchar(150),

    -- estado
    status_id smallint NOT NULL DEFAULT 1,
    es_principal boolean NOT NULL DEFAULT false,

    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),

    CONSTRAINT pk_adm_establecimiento PRIMARY KEY (establecimiento_id),
    CONSTRAINT uq_adm_establecimiento_company_estab UNIQUE (company_id, establecimiento_id),
    CONSTRAINT fk_adm_establecimiento_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT uq_adm_establecimiento_codigo UNIQUE (company_id, codigo),
    CONSTRAINT ck_adm_establecimiento_rtn_format CHECK (rtn_emisor ~ '^[0-9]{14}$'),
    CONSTRAINT ck_adm_establecimiento_status CHECK (status_id IN (0, 1))
);

CREATE INDEX IF NOT EXISTS ix_adm_establecimiento_company
    ON public.adm_establecimiento (company_id, status_id);

-- Una sola empresa puede tener un solo principal activo
CREATE UNIQUE INDEX IF NOT EXISTS uq_adm_establecimiento_principal_por_company
    ON public.adm_establecimiento (company_id)
    WHERE es_principal = true AND status_id = 1;

-- ----------------------------------------------------------------------------
-- 5) Seed inicial: para cada cfg_company que aún no tenga establecimiento
--    principal, crear uno copiando los datos de la empresa.
--    Idempotente: solo inserta si no existe.
-- ----------------------------------------------------------------------------
INSERT INTO public.adm_establecimiento
    (company_id, codigo, nombre, rtn_emisor, razon_social_emisor, direccion_emisor, telefono, correo, es_principal, status_id)
SELECT
    c.company_id,
    'PRINCIPAL'                              AS codigo,
    COALESCE(c.commercial_name, c.legal_name) AS nombre,
    c.tax_id                                 AS rtn_emisor,
    c.legal_name                             AS razon_social_emisor,
    COALESCE(c.address, 'PENDIENTE')         AS direccion_emisor,
    c.phone                                  AS telefono,
    c.email                                  AS correo,
    true                                     AS es_principal,
    1                                        AS status_id
FROM public.cfg_company c
WHERE NOT EXISTS (
    SELECT 1
    FROM public.adm_establecimiento e
    WHERE e.company_id = c.company_id
      AND e.es_principal = true
      AND e.status_id = 1
)
  AND c.tax_id ~ '^[0-9]{14}$';   -- solo seed si la empresa tiene RTN válido

COMMIT;

-- ----------------------------------------------------------------------------
-- Verificación post-migración
-- ----------------------------------------------------------------------------
SELECT 'cfg_tipo_documento_fiscal' AS tabla, count(*) AS filas FROM public.cfg_tipo_documento_fiscal
UNION ALL
SELECT 'cfg_motivo_anulacion',        count(*) FROM public.cfg_motivo_anulacion
UNION ALL
SELECT 'cfg_estado_documento_fiscal', count(*) FROM public.cfg_estado_documento_fiscal
UNION ALL
SELECT 'adm_establecimiento',         count(*) FROM public.adm_establecimiento;

-- Empresas sin establecimiento principal (deberían ser 0 si todas tienen tax_id válido)
SELECT c.company_id, c.code, c.legal_name, c.tax_id
FROM public.cfg_company c
LEFT JOIN public.adm_establecimiento e
       ON e.company_id = c.company_id AND e.es_principal = true AND e.status_id = 1
WHERE e.establecimiento_id IS NULL;
