-- =============================================================================
-- Integración Contable ↔ Comercial — Fase 1: Modelo de configuración
-- Fecha: 2026-07-02
-- Plan: docs/plans/2026-07-02-plan-integracion-contable-comercial.md §5 Fase 1
--       (decisiones D2/D3/D4: configuración única por empresa, plan-agnóstica;
--        reemplaza a con_regla_integracion y con_plantilla_partida_* como
--        fuente de configuración — esos objetos NO se tocan aquí).
--
-- Contenido:
--   1. con_integracion_config   — cabecera por empresa (modos de granularidad)
--   2. con_integracion_cuenta   — matriz de cuentas (uso × servicio × categoría × medición)
--   3. con_partida_pendiente    — cola de regularización (solo estructura; se consume en F3)
--   4. fn_con_cuenta_posteable  — helper: account_id posteable por código
--   5. fn_con_resolver_cuenta   — resolución con fallback "lo más específico gana"
--   6. sp_con_aplicar_perfil_integracion — auto-llenado por convención del plan
--      cargado (perfil ERSAPS; diseño abierto a NIIF futuro)
--
-- NOTA (perfil ERSAPS): el llenado resuelve SIEMPRE por con_plan_cuentas.code
-- (robusto entre ambientes — en respaldos se observaron adm_servicio.cont_account_id
-- huérfanos tras recargas del plan). Convención espejo del plan regulatorio:
--   Ingreso  5.1.XXX...      = '51'       || XXX || '000000'
--   CxC abonados             = '11301010' || XXX
--   Previsión incobrables    = '11303010' || XXX
--   (ej. 51101000000 ↔ 11301010101 ↔ 11303010101)
--
-- Idempotente. Producción: aplicar SOLO en ventana de deploy acordada.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. con_integracion_config — cabecera de integración contable por empresa
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.con_integracion_config (
    config_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,

    -- granularidad de las líneas analíticas (D4)
    modo_ventas varchar(30) NOT NULL DEFAULT 'GENERAL',
    modo_cxc varchar(30) NOT NULL DEFAULT 'GENERAL',

    -- comportamiento cuando no hay período contable abierto: encolar en
    -- con_partida_pendiente (true) o rechazar la operación (false)
    encolar_sin_periodo boolean NOT NULL DEFAULT true,

    -- activación del posteo automático por módulo (D10); apagados por defecto,
    -- se encienden por empresa al desplegar cada fase
    activo_facturacion boolean NOT NULL DEFAULT false,
    activo_caja boolean NOT NULL DEFAULT false,
    activo_bancos boolean NOT NULL DEFAULT false,
    activo_notas boolean NOT NULL DEFAULT false,
    activo_miscelaneos boolean NOT NULL DEFAULT false,

    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),

    CONSTRAINT uq_con_integracion_config_company UNIQUE (company_id),
    CONSTRAINT fk_con_integracion_config_company
        FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT ck_con_integracion_config_modo_ventas
        CHECK (modo_ventas IN ('GENERAL', 'POR_SERVICIO', 'POR_SERVICIO_CATEGORIA')),
    CONSTRAINT ck_con_integracion_config_modo_cxc
        CHECK (modo_cxc IN ('GENERAL', 'POR_SERVICIO', 'POR_SERVICIO_CATEGORIA'))
);

COMMENT ON TABLE public.con_integracion_config IS
'Cabecera de configuración de integración contable-comercial por empresa (plan F1, D3/D4). Una fila por empresa; los modos definen la granularidad de las líneas analíticas que arma fn_con_resolver_cuenta.';

-- -----------------------------------------------------------------------------
-- 2. con_integracion_cuenta — matriz de cuentas por uso y dimensiones
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.con_integracion_cuenta (
    integracion_cuenta_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,

    uso varchar(30) NOT NULL,

    -- dimensiones opcionales: NULL = comodín (fila general o de servicio)
    servicio_id bigint,
    categoria_servicio_id integer,
    con_medicion boolean,

    account_id bigint NOT NULL,
    is_active boolean NOT NULL DEFAULT true,

    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),

    CONSTRAINT fk_con_integracion_cuenta_company
        FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_con_integracion_cuenta_servicio
        FOREIGN KEY (company_id, servicio_id)
        REFERENCES public.adm_servicio (company_id, servicio_id),
    CONSTRAINT fk_con_integracion_cuenta_categoria
        FOREIGN KEY (categoria_servicio_id)
        REFERENCES public.categoria_servicio (categoria_servicio_id),
    CONSTRAINT fk_con_integracion_cuenta_account
        FOREIGN KEY (account_id) REFERENCES public.con_plan_cuentas (account_id),
    CONSTRAINT ck_con_integracion_cuenta_uso
        CHECK (uso IN ('CXC', 'INGRESO', 'CAJA', 'BANCO_DEFAULT', 'ISV', 'DESCUENTO',
                       'RECARGO_MORA', 'PREVISION_INCOBRABLE', 'GASTO_INCOBRABLE',
                       'RESULTADO_EJERCICIO', 'RESULTADO_ACUMULADO', 'DEVOLUCION_NC',
                       'TRANSITORIA')),
    -- categoría/medición solo tienen sentido bajo un servicio
    CONSTRAINT ck_con_integracion_cuenta_dims
        CHECK (servicio_id IS NOT NULL
               OR (categoria_servicio_id IS NULL AND con_medicion IS NULL))
);

-- Unicidad tenant-safe tratando NULL como valor (un solo comodín por combinación).
-- Expresiones COALESCE en lugar de NULLS NOT DISTINCT para compatibilidad PG<15.
CREATE UNIQUE INDEX IF NOT EXISTS ux_con_integracion_cuenta_dims
    ON public.con_integracion_cuenta (
        company_id, uso,
        COALESCE(servicio_id, 0),
        COALESCE(categoria_servicio_id, 0),
        COALESCE(con_medicion::integer, -1)
    );

CREATE INDEX IF NOT EXISTS ix_con_integracion_cuenta_company_uso
    ON public.con_integracion_cuenta (company_id, uso)
    WHERE is_active;

COMMENT ON TABLE public.con_integracion_cuenta IS
'Matriz de cuentas de integración contable (plan F1, D4). Cada fila mapea (uso × servicio × categoría × medición) → account_id del plan de la empresa. NULL en una dimensión = comodín; fn_con_resolver_cuenta elige la fila más específica.';

-- -----------------------------------------------------------------------------
-- 3. con_partida_pendiente — cola de regularización (estructura; se consume en F3)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.con_partida_pendiente (
    partida_pendiente_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,

    module varchar(30) NOT NULL,               -- VENTAS, CAJA, BANCOS, NOTAS, MISCELANEOS
    origen_tipo varchar(50) NOT NULL,          -- ej. FACTURA, LOTE_FACTURACION, TRANSACCION_ABONADO
    origen_id bigint,
    origen_referencia varchar(120),

    fecha_documento date NOT NULL,
    descripcion varchar(500),
    payload jsonb NOT NULL DEFAULT '{}'::jsonb, -- datos necesarios para regenerar la partida

    motivo varchar(200) NOT NULL DEFAULT 'SIN_PERIODO_ABIERTO',
    status_id smallint NOT NULL DEFAULT 1,      -- 1=PENDIENTE 2=PROCESADA 3=DESCARTADA
    intentos integer NOT NULL DEFAULT 0,
    ultimo_error text,

    poliza_id bigint,                           -- partida generada al procesar
    procesada_at timestamptz,
    procesada_by varchar(100),

    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),

    CONSTRAINT fk_con_partida_pendiente_company
        FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_con_partida_pendiente_poliza
        FOREIGN KEY (poliza_id) REFERENCES public.con_partida_hdr (poliza_id) ON DELETE SET NULL,
    CONSTRAINT ck_con_partida_pendiente_status
        CHECK (status_id IN (1, 2, 3))
);

CREATE INDEX IF NOT EXISTS ix_con_partida_pendiente_company_status
    ON public.con_partida_pendiente (company_id, status_id);

CREATE INDEX IF NOT EXISTS ix_con_partida_pendiente_origen
    ON public.con_partida_pendiente (company_id, module, origen_tipo, origen_id);

COMMENT ON TABLE public.con_partida_pendiente IS
'Cola de regularización contable (plan F1 punto 4). Cuando un módulo con encolar_sin_periodo=true no encuentra período contable abierto, deja aquí la partida por generar; la pantalla de F3 la reprocesa. Estados: 1=PENDIENTE, 2=PROCESADA, 3=DESCARTADA.';

-- -----------------------------------------------------------------------------
-- 4. fn_con_cuenta_posteable — helper: account_id posteable por código
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_con_cuenta_posteable(
    p_company_id bigint,
    p_code text
) RETURNS bigint
LANGUAGE sql
STABLE
AS $function$
    SELECT c.account_id
    FROM public.con_plan_cuentas c
    WHERE c.company_id = p_company_id
      AND c.code = p_code
      AND c.allows_posting
    LIMIT 1;
$function$;

COMMENT ON FUNCTION public.fn_con_cuenta_posteable(bigint, text) IS
'Devuelve el account_id de la cuenta posteable con ese código para la empresa, o NULL si no existe / no es posteable.';

-- -----------------------------------------------------------------------------
-- 5. fn_con_resolver_cuenta — resolución con fallback específico → servicio → general
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_con_resolver_cuenta(
    p_company_id bigint,
    p_uso varchar,
    p_servicio_id bigint DEFAULT NULL,
    p_categoria_servicio_id integer DEFAULT NULL,
    p_con_medicion boolean DEFAULT NULL
) RETURNS bigint
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_account_id bigint;
BEGIN
    -- "Lo más específico gana": una fila matchea si cada dimensión configurada
    -- es comodín (NULL) o coincide con el parámetro. Filas más específicas que
    -- los parámetros quedan excluidas por el WHERE (NULL = x → no matchea).
    SELECT ic.account_id
    INTO v_account_id
    FROM public.con_integracion_cuenta ic
    WHERE ic.company_id = p_company_id
      AND ic.uso = p_uso
      AND ic.is_active
      AND (ic.servicio_id IS NULL OR ic.servicio_id = p_servicio_id)
      AND (ic.categoria_servicio_id IS NULL OR ic.categoria_servicio_id = p_categoria_servicio_id)
      AND (ic.con_medicion IS NULL OR ic.con_medicion = p_con_medicion)
    ORDER BY (ic.servicio_id IS NOT NULL)::integer * 4
           + (ic.categoria_servicio_id IS NOT NULL)::integer * 2
           + (ic.con_medicion IS NOT NULL)::integer DESC,
             ic.integracion_cuenta_id
    LIMIT 1;

    IF v_account_id IS NULL THEN
        RAISE EXCEPTION
            'Integración contable: no hay cuenta configurada para uso=% (company_id=%, servicio_id=%, categoria_servicio_id=%, con_medicion=%).',
            p_uso, p_company_id, p_servicio_id, p_categoria_servicio_id, p_con_medicion
        USING HINT = 'Complete la matriz en Configuración de Integración Contable o aplique un perfil (sp_con_aplicar_perfil_integracion).',
              ERRCODE = 'P0001';
    END IF;

    RETURN v_account_id;
END;
$function$;

COMMENT ON FUNCTION public.fn_con_resolver_cuenta(bigint, varchar, bigint, integer, boolean) IS
'Resuelve la cuenta contable para un uso y dimensiones opcionales con fallback "lo más específico gana" → servicio → general (plan F1 punto 3). El llamador pasa las dimensiones según el modo configurado en con_integracion_config. RAISE EXCEPTION si no hay fila aplicable.';

-- -----------------------------------------------------------------------------
-- 6. sp_con_aplicar_perfil_integracion — auto-llenado por convención del plan
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sp_con_aplicar_perfil_integracion(
    p_company_id bigint,
    p_perfil text,
    p_user text DEFAULT 'perfil-integracion'
) RETURNS TABLE (
    insertadas integer,
    existentes integer,
    sin_cuenta integer
)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_insertadas integer := 0;
    v_candidatas integer := 0;
    v_sin_cuenta integer := 0;
    v_faltantes text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.cfg_company c WHERE c.company_id = p_company_id) THEN
        RAISE EXCEPTION 'Empresa % no existe.', p_company_id;
    END IF;

    IF UPPER(BTRIM(p_perfil)) <> 'ERSAPS' THEN
        RAISE EXCEPTION 'Perfil de integración no soportado: %. Perfiles disponibles: ERSAPS.', p_perfil;
    END IF;

    -- Cabecera: al aplicar el perfil regulatorio la granularidad por defecto es
    -- la máxima (servicio × categoría × medición). No pisa una config existente.
    INSERT INTO public.con_integracion_config
        (company_id, modo_ventas, modo_cxc, encolar_sin_periodo, created_by)
    VALUES
        (p_company_id, 'POR_SERVICIO_CATEGORIA', 'POR_SERVICIO_CATEGORIA', true, p_user)
    ON CONFLICT (company_id) DO NOTHING;

    -- ---------------------------------------------------------------------
    -- Candidatas del perfil (uso, dimensiones, código de cuenta ERSAPS)
    -- ---------------------------------------------------------------------
    DROP TABLE IF EXISTS pg_temp.tmp_perfil_integracion;
    CREATE TEMP TABLE tmp_perfil_integracion (
        uso varchar(30) NOT NULL,
        servicio_id bigint,
        categoria_servicio_id integer,
        con_medicion boolean,
        code text NOT NULL
    ) ON COMMIT DROP;

    -- 6.1 Usos generales (fila comodín por uso).
    --     DEVOLUCION_NC se deja sin configurar a propósito: la NC espeja las
    --     cuentas de la factura origen salvo que el contador configure una.
    INSERT INTO tmp_perfil_integracion (uso, code) VALUES
        ('CXC',                  '11301010304'),  -- CxC Abonados - Otros Cargos (fallback)
        ('INGRESO',              '51304000000'),  -- Otros Cargos (fallback)
        ('CAJA',                 '11101020000'),  -- Caja General
        ('BANCO_DEFAULT',        '11102030000'),  -- Banco - Otras Cuentas
        ('ISV',                  '21105010000'),  -- Impuestos por Pagar
        ('DESCUENTO',            '54100000000'),  -- Descuento sobre venta de agua
        ('RECARGO_MORA',         '51304000000'),  -- Otros Cargos
        ('PREVISION_INCOBRABLE', '11303010304'),  -- Previsión Abonados - Otros Cargos (fallback)
        ('GASTO_INCOBRABLE',     '71206000000'),  -- Pérdida por Deudores Incobrables
        ('RESULTADO_EJERCICIO',  '31502000000'),  -- Resultados del Ejercicio
        ('RESULTADO_ACUMULADO',  '31501000000'),  -- Resultados Acumulados de Ejercicios Anteriores
        ('TRANSITORIA',          '21109000000');  -- Otras Cuentas por Pagar (puente)

    -- 6.2 Nivel servicio: cuenta de ingreso representativa por convención de
    --     código del servicio (misma tabla que el backfill día-10) + espejos.
    WITH servicio_ingreso AS (
        SELECT s.servicio_id,
               UPPER(BTRIM(s.codigo)) AS codigo,
               CASE UPPER(BTRIM(s.codigo))
                   WHEN 'AGUA_POTABLE'      THEN '51101000000'
                   WHEN 'ALCANTARILLADO'    THEN '51201000000'
                   WHEN 'CONEXION'          THEN '51301000000'
                   WHEN 'INSTALACION'       THEN '51301000000'
                   WHEN 'CORTE_RECONEXION'  THEN '51302000000'
                   WHEN 'AGUA_CISTERNA'     THEN '51303000000'
                   WHEN 'TASA_AMBIENTAL'    THEN '51304000000'
                   WHEN 'TASA_SVA_ERSAPS'   THEN '51304000000'
                   WHEN 'TRASLADO'          THEN '51304000000'
                   WHEN 'MODIFICACION'      THEN '51304000000'
                   WHEN 'OTROS_COLATERALES' THEN '51304000000'
                   ELSE NULL
               END AS ingreso_code
        FROM public.adm_servicio s
        WHERE s.company_id = p_company_id
          AND s.status_id = 1
    )
    INSERT INTO tmp_perfil_integracion (uso, servicio_id, code)
    SELECT u.uso, si.servicio_id,
           CASE u.uso
               WHEN 'INGRESO'              THEN si.ingreso_code
               WHEN 'CXC'                  THEN '11301010' || substr(si.ingreso_code, 3, 3)
               WHEN 'PREVISION_INCOBRABLE' THEN '11303010' || substr(si.ingreso_code, 3, 3)
           END
    FROM servicio_ingreso si
    CROSS JOIN (VALUES ('INGRESO'), ('CXC'), ('PREVISION_INCOBRABLE')) AS u(uso)
    WHERE si.ingreso_code IS NOT NULL;

    -- Servicios activos sin convención conocida: quedan cubiertos por la fila
    -- general (fallback) y se reportan como advertencia.
    SELECT string_agg(s.codigo, ', ') INTO v_faltantes
    FROM public.adm_servicio s
    WHERE s.company_id = p_company_id
      AND s.status_id = 1
      AND UPPER(BTRIM(s.codigo)) NOT IN
          ('AGUA_POTABLE','ALCANTARILLADO','CONEXION','INSTALACION','CORTE_RECONEXION',
           'AGUA_CISTERNA','TASA_AMBIENTAL','TASA_SVA_ERSAPS','TRASLADO','MODIFICACION',
           'OTROS_COLATERALES');
    IF v_faltantes IS NOT NULL THEN
        RAISE NOTICE 'Perfil ERSAPS: servicios sin convención de cuenta (usarán la fila general): %', v_faltantes;
    END IF;

    -- Descuento por servicio (agua / alcantarillado).
    INSERT INTO tmp_perfil_integracion (uso, servicio_id, code)
    SELECT 'DESCUENTO', s.servicio_id,
           CASE UPPER(BTRIM(s.codigo))
               WHEN 'AGUA_POTABLE'   THEN '54100000000'
               WHEN 'ALCANTARILLADO' THEN '54200000000'
           END
    FROM public.adm_servicio s
    WHERE s.company_id = p_company_id
      AND s.status_id = 1
      AND UPPER(BTRIM(s.codigo)) IN ('AGUA_POTABLE', 'ALCANTARILLADO');

    -- 6.3 Matriz servicio × categoría (× medición para agua potable).
    --     Columna ERSAPS por descripción de la categoría (robusto entre ambientes):
    --     1=Doméstico, 2=Comercial, 3=Industrial, 4=Gubernamental/Pública.
    WITH categoria_col AS (
        SELECT cs.categoria_servicio_id,
               CASE
                   WHEN lower(cs.descripcion) LIKE '%domestic%' OR lower(cs.descripcion) LIKE '%doméstic%' THEN 1
                   WHEN lower(cs.descripcion) LIKE '%comercial%' THEN 2
                   WHEN lower(cs.descripcion) LIKE '%industrial%' THEN 3
                   WHEN lower(cs.descripcion) LIKE '%public%' OR lower(cs.descripcion) LIKE '%públic%'
                        OR lower(cs.descripcion) LIKE '%gubernam%' OR lower(cs.descripcion) LIKE '%estatal%' THEN 4
               END AS col
        FROM public.categoria_servicio cs
        WHERE cs.estado
    ),
    -- Agua potable: 5.1.1.01–04 con medición, 05–08 sin medición.
    agua AS (
        SELECT s.servicio_id, cc.categoria_servicio_id, m.medido,
               '511' || lpad((cc.col + CASE WHEN m.medido THEN 0 ELSE 4 END)::text, 2, '0') || '000000' AS ingreso_code
        FROM public.adm_servicio s
        CROSS JOIN categoria_col cc
        CROSS JOIN (VALUES (true), (false)) AS m(medido)
        WHERE s.company_id = p_company_id
          AND s.status_id = 1
          AND UPPER(BTRIM(s.codigo)) = 'AGUA_POTABLE'
          AND cc.col IS NOT NULL
    ),
    -- Alcantarillado: 5.1.2.01–04, sin dimensión de medición.
    alcantarillado AS (
        SELECT s.servicio_id, cc.categoria_servicio_id, NULL::boolean AS medido,
               '512' || lpad(cc.col::text, 2, '0') || '000000' AS ingreso_code
        FROM public.adm_servicio s
        CROSS JOIN categoria_col cc
        WHERE s.company_id = p_company_id
          AND s.status_id = 1
          AND UPPER(BTRIM(s.codigo)) = 'ALCANTARILLADO'
          AND cc.col IS NOT NULL
    ),
    matriz AS (
        SELECT * FROM agua
        UNION ALL
        SELECT * FROM alcantarillado
    )
    INSERT INTO tmp_perfil_integracion (uso, servicio_id, categoria_servicio_id, con_medicion, code)
    SELECT u.uso, x.servicio_id, x.categoria_servicio_id, x.medido,
           CASE u.uso
               WHEN 'INGRESO'              THEN x.ingreso_code
               WHEN 'CXC'                  THEN '11301010' || substr(x.ingreso_code, 3, 3)
               WHEN 'PREVISION_INCOBRABLE' THEN '11303010' || substr(x.ingreso_code, 3, 3)
           END
    FROM matriz x
    CROSS JOIN (VALUES ('INGRESO'), ('CXC'), ('PREVISION_INCOBRABLE')) AS u(uso);

    -- ---------------------------------------------------------------------
    -- Resolución de códigos e inserción idempotente
    -- ---------------------------------------------------------------------
    SELECT COUNT(*) INTO v_candidatas FROM tmp_perfil_integracion;

    SELECT COUNT(*) INTO v_sin_cuenta
    FROM tmp_perfil_integracion t
    WHERE public.fn_con_cuenta_posteable(p_company_id, t.code) IS NULL;

    IF v_sin_cuenta > 0 THEN
        SELECT string_agg(DISTINCT t.code, ', ') INTO v_faltantes
        FROM tmp_perfil_integracion t
        WHERE public.fn_con_cuenta_posteable(p_company_id, t.code) IS NULL;
        RAISE NOTICE 'Perfil ERSAPS: % candidatas omitidas — códigos sin cuenta posteable en el plan: %', v_sin_cuenta, v_faltantes;
    END IF;

    INSERT INTO public.con_integracion_cuenta
        (company_id, uso, servicio_id, categoria_servicio_id, con_medicion, account_id, created_by)
    SELECT p_company_id, t.uso, t.servicio_id, t.categoria_servicio_id, t.con_medicion,
           public.fn_con_cuenta_posteable(p_company_id, t.code), p_user
    FROM tmp_perfil_integracion t
    WHERE public.fn_con_cuenta_posteable(p_company_id, t.code) IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM public.con_integracion_cuenta ic
          WHERE ic.company_id = p_company_id
            AND ic.uso = t.uso
            AND ic.servicio_id IS NOT DISTINCT FROM t.servicio_id
            AND ic.categoria_servicio_id IS NOT DISTINCT FROM t.categoria_servicio_id
            AND ic.con_medicion IS NOT DISTINCT FROM t.con_medicion
      );

    GET DIAGNOSTICS v_insertadas = ROW_COUNT;

    RETURN QUERY SELECT v_insertadas,
                        v_candidatas - v_sin_cuenta - v_insertadas,
                        v_sin_cuenta;
END;
$function$;

COMMENT ON FUNCTION public.sp_con_aplicar_perfil_integracion(bigint, text, text) IS
'Auto-llenado de con_integracion_config/con_integracion_cuenta por convención de códigos del plan cargado (plan F1 punto 5). Perfil ERSAPS: matriz completa CxC/Ingresos/Previsión por servicio × categoría × medición + usos generales. Idempotente: no pisa filas existentes. Devuelve (insertadas, existentes, sin_cuenta).';
