-- =============================================================================
-- Cierre CAI offline V3: preparacion/confirmacion de correlativo y bitacora de
-- conflictos de sincronizacion para soporte operativo en portal.
-- Fecha: 2026-04-19
-- =============================================================================

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_adm_cai_facturacion_company_cai_id'
          AND conrelid = 'public.adm_cai_facturacion'::regclass
    ) THEN
        ALTER TABLE public.adm_cai_facturacion
            ADD CONSTRAINT uq_adm_cai_facturacion_company_cai_id
            UNIQUE (company_id, cai_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_adm_cai_bloque_reservado_company_bloque_id'
          AND conrelid = 'public.adm_cai_bloque_reservado'::regclass
    ) THEN
        ALTER TABLE public.adm_cai_bloque_reservado
            ADD CONSTRAINT uq_adm_cai_bloque_reservado_company_bloque_id
            UNIQUE (company_id, cai_bloque_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.adm_lectura_v3_conflicto_sync (
    lectura_v3_conflicto_sync_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    cliente_id bigint,
    cliente_clave varchar(30),
    lectura_uuid varchar(100),
    cai_id bigint,
    cai_bloque_id bigint,
    correlativo bigint,
    numero_factura varchar(80) NOT NULL,
    codigo_conflicto varchar(60) NOT NULL,
    detalle_conflicto varchar(500),
    payload_resumen jsonb,
    factura_id bigint,
    estado_codigo varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),
    CONSTRAINT fk_adm_lectura_v3_conflicto_sync_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_adm_lectura_v3_conflicto_sync_cai FOREIGN KEY (company_id, cai_id) REFERENCES public.adm_cai_facturacion (company_id, cai_id),
    CONSTRAINT fk_adm_lectura_v3_conflicto_sync_bloque FOREIGN KEY (company_id, cai_bloque_id) REFERENCES public.adm_cai_bloque_reservado (company_id, cai_bloque_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_adm_lectura_v3_conflicto_sync_company_numero
    ON public.adm_lectura_v3_conflicto_sync (company_id, numero_factura);

CREATE UNIQUE INDEX IF NOT EXISTS uq_adm_lectura_v3_conflicto_sync_company_uuid
    ON public.adm_lectura_v3_conflicto_sync (company_id, lectura_uuid)
    WHERE lectura_uuid IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_adm_lectura_v3_conflicto_sync_lookup
    ON public.adm_lectura_v3_conflicto_sync (company_id, estado_codigo, created_at DESC);

DROP FUNCTION IF EXISTS public.sp_adm_obtener_o_reservar_bloque_cai_ruta(bigint, varchar, integer, varchar);

CREATE OR REPLACE FUNCTION public.sp_adm_obtener_o_reservar_bloque_cai_ruta(
    p_company_id bigint,
    p_ruta_codigo varchar,
    p_cantidad integer DEFAULT 250,
    p_usuario varchar DEFAULT current_user
)
RETURNS TABLE (
    cai_bloque_id bigint,
    cai_id bigint,
    codigo_cai varchar,
    prefijo_documento varchar,
    correlativo_desde bigint,
    correlativo_hasta bigint,
    correlativo_actual bigint,
    correlativo_siguiente bigint,
    fecha_expiracion date,
    estado_codigo varchar
)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_ruta_codigo varchar := NULLIF(BTRIM(COALESCE(p_ruta_codigo, '')), '');
    v_cai_id bigint;
BEGIN
    IF v_ruta_codigo IS NULL THEN
        RAISE EXCEPTION 'RUTA_REQUERIDA: se requiere ruta para resolver bloque CAI offline.';
    END IF;

    RETURN QUERY
    SELECT
        b.cai_bloque_id,
        b.cai_id,
        c.codigo_cai,
        c.prefijo_documento,
        b.correlativo_desde,
        b.correlativo_hasta,
        b.correlativo_actual,
        LEAST(b.correlativo_actual + 1, b.correlativo_hasta) AS correlativo_siguiente,
        b.fecha_expiracion,
        b.estado_codigo
    FROM public.adm_cai_bloque_reservado b
    JOIN public.adm_cai_facturacion c
      ON c.company_id = b.company_id
     AND c.cai_id = b.cai_id
    WHERE b.company_id = p_company_id
      AND b.ruta_codigo = v_ruta_codigo
      AND b.status_id = 1
      AND c.status_id = 1
      AND current_date >= c.vigencia_desde
      AND (c.vigencia_hasta IS NULL OR current_date <= c.vigencia_hasta)
      AND (b.fecha_expiracion IS NULL OR current_date <= b.fecha_expiracion)
      AND b.correlativo_actual < b.correlativo_hasta
    ORDER BY b.fecha_reserva DESC, b.cai_bloque_id DESC
    LIMIT 1;

    IF FOUND THEN
        RETURN;
    END IF;

    SELECT c.cai_id
    INTO v_cai_id
    FROM public.adm_cai_facturacion c
    WHERE c.company_id = p_company_id
      AND c.status_id = 1
      AND current_date >= c.vigencia_desde
      AND (c.vigencia_hasta IS NULL OR current_date <= c.vigencia_hasta)
    ORDER BY c.vigencia_desde DESC, c.cai_id DESC
    LIMIT 1;

    IF v_cai_id IS NULL THEN
        RAISE EXCEPTION 'CAI_VIGENTE_NO_DISPONIBLE: no existe CAI activo/vigente para la empresa %.', p_company_id;
    END IF;

    PERFORM 1
    FROM public.sp_adm_reservar_bloque_cai(
        p_company_id,
        v_cai_id,
        NULL,
        NULL,
        v_ruta_codigo,
        COALESCE(NULLIF(p_cantidad, 0), 250),
        NULL,
        p_usuario
    );

    RETURN QUERY
    SELECT
        b.cai_bloque_id,
        b.cai_id,
        c.codigo_cai,
        c.prefijo_documento,
        b.correlativo_desde,
        b.correlativo_hasta,
        b.correlativo_actual,
        LEAST(b.correlativo_actual + 1, b.correlativo_hasta) AS correlativo_siguiente,
        b.fecha_expiracion,
        b.estado_codigo
    FROM public.adm_cai_bloque_reservado b
    JOIN public.adm_cai_facturacion c
      ON c.company_id = b.company_id
     AND c.cai_id = b.cai_id
    WHERE b.company_id = p_company_id
      AND b.ruta_codigo = v_ruta_codigo
      AND b.status_id = 1
    ORDER BY b.fecha_reserva DESC, b.cai_bloque_id DESC
    LIMIT 1;
END;
$function$;

DROP FUNCTION IF EXISTS public.sp_adm_prepare_correlativo_cai_sync(bigint, bigint, bigint, bigint, varchar, varchar, varchar);

CREATE OR REPLACE FUNCTION public.sp_adm_prepare_correlativo_cai_sync(
    p_company_id bigint,
    p_cliente_id bigint,
    p_id_cai bigint,
    p_correlativo bigint,
    p_numero_factura varchar,
    p_lectura_uuid varchar DEFAULT NULL,
    p_usuario varchar DEFAULT current_user
)
RETURNS TABLE (
    success boolean,
    estado_codigo varchar,
    cai_bloque_id bigint,
    factura_id bigint,
    mensaje text
)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_uuid varchar := NULLIF(BTRIM(COALESCE(p_lectura_uuid, '')), '');
    v_numero varchar := NULLIF(BTRIM(COALESCE(p_numero_factura, '')), '');
    v_bloque record;
    v_existente public.adm_cai_correlativo_emitido%ROWTYPE;
BEGIN
    IF p_id_cai IS NULL OR p_id_cai <= 0 OR p_correlativo IS NULL OR p_correlativo <= 0 OR v_numero IS NULL THEN
        RAISE EXCEPTION 'CAI_DATOS_REQUERIDOS: id_cai, correlativo y numero_factura son requeridos.';
    END IF;

    SELECT
        b.cai_bloque_id,
        b.fecha_expiracion
    INTO v_bloque
    FROM public.adm_cai_bloque_reservado b
    JOIN public.adm_cai_facturacion c
      ON c.company_id = b.company_id
     AND c.cai_id = b.cai_id
    WHERE b.company_id = p_company_id
      AND b.cai_id = p_id_cai
      AND b.status_id = 1
      AND c.status_id = 1
      AND current_date >= c.vigencia_desde
      AND (c.vigencia_hasta IS NULL OR current_date <= c.vigencia_hasta)
      AND p_correlativo BETWEEN b.correlativo_desde AND b.correlativo_hasta
    ORDER BY b.fecha_reserva DESC, b.cai_bloque_id DESC
    LIMIT 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'BLOQUE_INVALIDO: el correlativo % no pertenece a un bloque CAI reservado/activo.', p_correlativo;
    END IF;

    IF v_bloque.fecha_expiracion IS NOT NULL AND current_date > v_bloque.fecha_expiracion THEN
        RAISE EXCEPTION 'CAI_VENCIDO: el bloque reservado para el correlativo % ya expiro.', p_correlativo;
    END IF;

    SELECT *
    INTO v_existente
    FROM public.adm_cai_correlativo_emitido e
    WHERE e.company_id = p_company_id
      AND (
            (v_uuid IS NOT NULL AND e.lectura_uuid = v_uuid)
            OR e.numero_factura = v_numero
            OR (e.cai_id = p_id_cai AND e.correlativo = p_correlativo)
          )
    ORDER BY e.cai_correlativo_emitido_id DESC
    LIMIT 1;

    IF FOUND THEN
        IF COALESCE(v_existente.cai_id, 0) = p_id_cai
           AND COALESCE(v_existente.correlativo, 0) = p_correlativo
           AND v_existente.numero_factura = v_numero THEN
            success := true;
            estado_codigo := CASE
                WHEN v_existente.factura_id IS NOT NULL THEN 'IDEMPOTENTE'
                ELSE COALESCE(v_existente.estado_codigo, 'PENDING_SYNC')
            END;
            cai_bloque_id := v_existente.cai_bloque_id;
            factura_id := v_existente.factura_id;
            mensaje := CASE
                WHEN v_existente.factura_id IS NOT NULL THEN 'El correlativo ya fue confirmado para esta misma lectura.'
                ELSE 'El correlativo ya estaba preparado para sincronizacion.'
            END;
            RETURN NEXT;
            RETURN;
        END IF;

        RAISE EXCEPTION 'CORRELATIVO_DUPLICADO: el correlativo/numero ya fue utilizado por otra lectura.';
    END IF;

    INSERT INTO public.adm_cai_correlativo_emitido (
        company_id,
        cai_bloque_id,
        cai_id,
        correlativo,
        numero_factura,
        cliente_id,
        lectura_uuid,
        estado_codigo,
        created_by
    )
    VALUES (
        p_company_id,
        v_bloque.cai_bloque_id,
        p_id_cai,
        p_correlativo,
        v_numero,
        p_cliente_id,
        v_uuid,
        'PENDING_SYNC',
        COALESCE(NULLIF(BTRIM(p_usuario), ''), current_user)
    );

    success := true;
    estado_codigo := 'PENDING_SYNC';
    cai_bloque_id := v_bloque.cai_bloque_id;
    factura_id := NULL;
    mensaje := 'Correlativo preparado para sincronizacion.';
    RETURN NEXT;
END;
$function$;

DROP FUNCTION IF EXISTS public.sp_adm_confirmar_correlativo_cai_sync(bigint, bigint, bigint, bigint, varchar, varchar, bigint, varchar);

CREATE OR REPLACE FUNCTION public.sp_adm_confirmar_correlativo_cai_sync(
    p_company_id bigint,
    p_cliente_id bigint,
    p_id_cai bigint,
    p_correlativo bigint,
    p_numero_factura varchar,
    p_lectura_uuid varchar DEFAULT NULL,
    p_factura_id bigint DEFAULT NULL,
    p_usuario varchar DEFAULT current_user
)
RETURNS TABLE (
    success boolean,
    estado_codigo varchar,
    cai_bloque_id bigint,
    factura_id bigint,
    mensaje text
)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_uuid varchar := NULLIF(BTRIM(COALESCE(p_lectura_uuid, '')), '');
    v_numero varchar := NULLIF(BTRIM(COALESCE(p_numero_factura, '')), '');
    v_bloque record;
    v_existente public.adm_cai_correlativo_emitido%ROWTYPE;
BEGIN
    IF p_id_cai IS NULL OR p_id_cai <= 0 OR p_correlativo IS NULL OR p_correlativo <= 0 OR v_numero IS NULL THEN
        RAISE EXCEPTION 'CAI_DATOS_REQUERIDOS: id_cai, correlativo y numero_factura son requeridos.';
    END IF;

    SELECT
        b.cai_bloque_id
    INTO v_bloque
    FROM public.adm_cai_bloque_reservado b
    WHERE b.company_id = p_company_id
      AND b.cai_id = p_id_cai
      AND p_correlativo BETWEEN b.correlativo_desde AND b.correlativo_hasta
    ORDER BY b.fecha_reserva DESC, b.cai_bloque_id DESC
    LIMIT 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'BLOQUE_INVALIDO: no se encontro bloque reservado para confirmar el correlativo %.', p_correlativo;
    END IF;

    SELECT *
    INTO v_existente
    FROM public.adm_cai_correlativo_emitido e
    WHERE e.company_id = p_company_id
      AND (
            (v_uuid IS NOT NULL AND e.lectura_uuid = v_uuid)
            OR e.numero_factura = v_numero
            OR (e.cai_id = p_id_cai AND e.correlativo = p_correlativo)
          )
    ORDER BY e.cai_correlativo_emitido_id DESC
    LIMIT 1;

    IF FOUND THEN
        IF COALESCE(v_existente.cai_id, 0) <> p_id_cai
           OR COALESCE(v_existente.correlativo, 0) <> p_correlativo
           OR v_existente.numero_factura <> v_numero THEN
            RAISE EXCEPTION 'FACTURA_YA_CONFIRMADA: existe un registro previo incompatible para este correlativo.';
        END IF;

        UPDATE public.adm_cai_correlativo_emitido AS e
        SET cliente_id = COALESCE(p_cliente_id, e.cliente_id),
            factura_id = COALESCE(p_factura_id, e.factura_id),
            estado_codigo = 'CONFIRMADO',
            fecha_confirmacion = now(),
            detalle_conflicto = NULL,
            updated_at = now(),
            updated_by = COALESCE(NULLIF(BTRIM(p_usuario), ''), current_user)
        WHERE e.cai_correlativo_emitido_id = v_existente.cai_correlativo_emitido_id;

        success := true;
        estado_codigo := 'CONFIRMADO';
        cai_bloque_id := v_existente.cai_bloque_id;
        factura_id := COALESCE(p_factura_id, v_existente.factura_id);
        mensaje := 'Correlativo confirmado correctamente.';
        RETURN NEXT;
        RETURN;
    END IF;

    INSERT INTO public.adm_cai_correlativo_emitido (
        company_id,
        cai_bloque_id,
        cai_id,
        correlativo,
        numero_factura,
        cliente_id,
        lectura_uuid,
        factura_id,
        estado_codigo,
        fecha_confirmacion,
        created_by
    )
    VALUES (
        p_company_id,
        v_bloque.cai_bloque_id,
        p_id_cai,
        p_correlativo,
        v_numero,
        p_cliente_id,
        v_uuid,
        p_factura_id,
        'CONFIRMADO',
        now(),
        COALESCE(NULLIF(BTRIM(p_usuario), ''), current_user)
    );

    success := true;
    estado_codigo := 'CONFIRMADO';
    cai_bloque_id := v_bloque.cai_bloque_id;
    factura_id := p_factura_id;
    mensaje := 'Correlativo confirmado correctamente.';
    RETURN NEXT;
END;
$function$;

DROP FUNCTION IF EXISTS public.sp_adm_registrar_conflicto_sync_lectura_v3(bigint, bigint, varchar, varchar, bigint, bigint, varchar, varchar, varchar, jsonb, varchar);

CREATE OR REPLACE FUNCTION public.sp_adm_registrar_conflicto_sync_lectura_v3(
    p_company_id bigint,
    p_cliente_id bigint,
    p_cliente_clave varchar,
    p_lectura_uuid varchar,
    p_id_cai bigint,
    p_correlativo bigint,
    p_numero_factura varchar,
    p_codigo_conflicto varchar,
    p_detalle_conflicto varchar,
    p_payload_resumen jsonb DEFAULT NULL,
    p_usuario varchar DEFAULT current_user
)
RETURNS bigint
LANGUAGE plpgsql
AS $function$
DECLARE
    v_uuid varchar := NULLIF(BTRIM(COALESCE(p_lectura_uuid, '')), '');
    v_numero varchar := NULLIF(BTRIM(COALESCE(p_numero_factura, '')), '');
    v_bloque_id bigint;
    v_conflicto_id bigint;
BEGIN
    IF v_numero IS NULL THEN
        RETURN 0;
    END IF;

    IF p_id_cai IS NOT NULL AND p_correlativo IS NOT NULL THEN
        SELECT b.cai_bloque_id
        INTO v_bloque_id
        FROM public.adm_cai_bloque_reservado b
        WHERE b.company_id = p_company_id
          AND b.cai_id = p_id_cai
          AND p_correlativo BETWEEN b.correlativo_desde AND b.correlativo_hasta
        ORDER BY b.fecha_reserva DESC, b.cai_bloque_id DESC
        LIMIT 1;
    END IF;

    INSERT INTO public.adm_lectura_v3_conflicto_sync (
        company_id,
        cliente_id,
        cliente_clave,
        lectura_uuid,
        cai_id,
        cai_bloque_id,
        correlativo,
        numero_factura,
        codigo_conflicto,
        detalle_conflicto,
        payload_resumen,
        estado_codigo,
        created_by
    )
    VALUES (
        p_company_id,
        p_cliente_id,
        NULLIF(BTRIM(COALESCE(p_cliente_clave, '')), ''),
        v_uuid,
        p_id_cai,
        v_bloque_id,
        p_correlativo,
        v_numero,
        COALESCE(NULLIF(BTRIM(COALESCE(p_codigo_conflicto, '')), ''), 'SYNC_CONFLICT'),
        p_detalle_conflicto,
        p_payload_resumen,
        'PENDIENTE',
        COALESCE(NULLIF(BTRIM(p_usuario), ''), current_user)
    )
    ON CONFLICT (company_id, numero_factura)
    DO UPDATE
       SET cliente_id = COALESCE(EXCLUDED.cliente_id, adm_lectura_v3_conflicto_sync.cliente_id),
           cliente_clave = COALESCE(EXCLUDED.cliente_clave, adm_lectura_v3_conflicto_sync.cliente_clave),
           lectura_uuid = COALESCE(EXCLUDED.lectura_uuid, adm_lectura_v3_conflicto_sync.lectura_uuid),
           cai_id = COALESCE(EXCLUDED.cai_id, adm_lectura_v3_conflicto_sync.cai_id),
           cai_bloque_id = COALESCE(EXCLUDED.cai_bloque_id, adm_lectura_v3_conflicto_sync.cai_bloque_id),
           correlativo = COALESCE(EXCLUDED.correlativo, adm_lectura_v3_conflicto_sync.correlativo),
           codigo_conflicto = COALESCE(EXCLUDED.codigo_conflicto, adm_lectura_v3_conflicto_sync.codigo_conflicto),
           detalle_conflicto = COALESCE(EXCLUDED.detalle_conflicto, adm_lectura_v3_conflicto_sync.detalle_conflicto),
           payload_resumen = COALESCE(EXCLUDED.payload_resumen, adm_lectura_v3_conflicto_sync.payload_resumen),
           estado_codigo = 'PENDIENTE',
           updated_at = now(),
           updated_by = COALESCE(NULLIF(BTRIM(p_usuario), ''), current_user)
    RETURNING lectura_v3_conflicto_sync_id
    INTO v_conflicto_id;

    UPDATE public.adm_cai_correlativo_emitido
    SET estado_codigo = 'SYNC_CONFLICT',
        detalle_conflicto = COALESCE(p_detalle_conflicto, detalle_conflicto),
        updated_at = now(),
        updated_by = COALESCE(NULLIF(BTRIM(p_usuario), ''), current_user)
    WHERE company_id = p_company_id
      AND (
            (v_uuid IS NOT NULL AND lectura_uuid = v_uuid)
            OR numero_factura = v_numero
            OR (
                p_id_cai IS NOT NULL
                AND p_correlativo IS NOT NULL
                AND cai_id = p_id_cai
                AND correlativo = p_correlativo
            )
          );

    RETURN COALESCE(v_conflicto_id, 0);
END;
$function$;
