-- =============================================================================
-- Core: motor tarifario regulatorio escalable
-- Fecha: 2026-04-16
-- Alcance:
--   - crea el nucleo del modelo tarifario nuevo
--   - incluye auditoria, multiempresa y seeds base
--   - NO migra datos desde public.servicios/public.tarifas/public.tarifas_contador
--   - NO reemplaza todavia el flujo actual de facturacion
--
-- Notas:
--   - Las relaciones a cliente, medidor y cuenta contable se dejan diferidas
--     en esta fase para no acoplar el modelo antes del mapeo final.
--   - Todas las tablas nuevas usan status_id:
--       1 = activo
--       0 = inactivo
-- =============================================================================
-- -----------------------------------------------------------------------------
-- 1) Catalogos base
-- -----------------------------------------------------------------------------
CREATE TABLE
    IF NOT EXISTS public.adm_tipo_servicio (
        tipo_servicio_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id bigint NOT NULL,
        codigo varchar(30) NOT NULL,
        nombre varchar(100) NOT NULL,
        descripcion varchar(300),
        status_id smallint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL DEFAULT now (),
        created_by varchar(100) NOT NULL DEFAULT current_user,
        updated_at timestamptz,
        updated_by varchar(100),
        CONSTRAINT fk_adm_tipo_servicio_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
        CONSTRAINT ck_adm_tipo_servicio_status CHECK (status_id IN (0, 1)),
        CONSTRAINT uq_adm_tipo_servicio_company_codigo UNIQUE (company_id, codigo),
        CONSTRAINT uq_adm_tipo_servicio_company_id UNIQUE (company_id, tipo_servicio_id)
    );

CREATE INDEX IF NOT EXISTS ix_adm_tipo_servicio_company ON public.adm_tipo_servicio (company_id);

CREATE TABLE
    IF NOT EXISTS public.adm_categoria_regulatoria (
        categoria_regulatoria_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id bigint NOT NULL,
        codigo varchar(30) NOT NULL,
        nombre varchar(100) NOT NULL,
        descripcion varchar(300),
        status_id smallint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL DEFAULT now (),
        created_by varchar(100) NOT NULL DEFAULT current_user,
        updated_at timestamptz,
        updated_by varchar(100),
        CONSTRAINT fk_adm_categoria_regulatoria_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
        CONSTRAINT ck_adm_categoria_regulatoria_status CHECK (status_id IN (0, 1)),
        CONSTRAINT uq_adm_categoria_regulatoria_company_codigo UNIQUE (company_id, codigo),
        CONSTRAINT uq_adm_categoria_regulatoria_company_id UNIQUE (company_id, categoria_regulatoria_id)
    );

CREATE INDEX IF NOT EXISTS ix_adm_categoria_regulatoria_company ON public.adm_categoria_regulatoria (company_id);

CREATE TABLE
    IF NOT EXISTS public.adm_segmento_tarifario (
        segmento_tarifario_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id bigint NOT NULL,
        categoria_regulatoria_id bigint,
        codigo varchar(40) NOT NULL,
        nombre varchar(120) NOT NULL,
        descripcion varchar(300),
        status_id smallint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL DEFAULT now (),
        created_by varchar(100) NOT NULL DEFAULT current_user,
        updated_at timestamptz,
        updated_by varchar(100),
        CONSTRAINT fk_adm_segmento_tarifario_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
        CONSTRAINT fk_adm_segmento_tarifario_categoria FOREIGN KEY (company_id, categoria_regulatoria_id) REFERENCES public.adm_categoria_regulatoria (company_id, categoria_regulatoria_id),
        CONSTRAINT ck_adm_segmento_tarifario_status CHECK (status_id IN (0, 1)),
        CONSTRAINT uq_adm_segmento_tarifario_company_codigo UNIQUE (company_id, codigo),
        CONSTRAINT uq_adm_segmento_tarifario_company_id UNIQUE (company_id, segmento_tarifario_id)
    );

CREATE INDEX IF NOT EXISTS ix_adm_segmento_tarifario_company ON public.adm_segmento_tarifario (company_id);

CREATE INDEX IF NOT EXISTS ix_adm_segmento_tarifario_company_categoria ON public.adm_segmento_tarifario (company_id, categoria_regulatoria_id);

CREATE TABLE
    IF NOT EXISTS public.adm_condicion_medicion (
        condicion_medicion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id bigint NOT NULL,
        codigo varchar(30) NOT NULL,
        nombre varchar(100) NOT NULL,
        descripcion varchar(300),
        requiere_lectura boolean NOT NULL DEFAULT false,
        status_id smallint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL DEFAULT now (),
        created_by varchar(100) NOT NULL DEFAULT current_user,
        updated_at timestamptz,
        updated_by varchar(100),
        CONSTRAINT fk_adm_condicion_medicion_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
        CONSTRAINT ck_adm_condicion_medicion_status CHECK (status_id IN (0, 1)),
        CONSTRAINT uq_adm_condicion_medicion_company_codigo UNIQUE (company_id, codigo),
        CONSTRAINT uq_adm_condicion_medicion_company_id UNIQUE (company_id, condicion_medicion_id)
    );

CREATE INDEX IF NOT EXISTS ix_adm_condicion_medicion_company ON public.adm_condicion_medicion (company_id);

CREATE TABLE
    IF NOT EXISTS public.adm_tipo_regla_tarifaria (
        tipo_regla_tarifaria_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id bigint NOT NULL,
        codigo varchar(30) NOT NULL,
        nombre varchar(100) NOT NULL,
        descripcion varchar(300),
        status_id smallint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL DEFAULT now (),
        created_by varchar(100) NOT NULL DEFAULT current_user,
        updated_at timestamptz,
        updated_by varchar(100),
        CONSTRAINT fk_adm_tipo_regla_tarifaria_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
        CONSTRAINT ck_adm_tipo_regla_tarifaria_status CHECK (status_id IN (0, 1)),
        CONSTRAINT uq_adm_tipo_regla_tarifaria_company_codigo UNIQUE (company_id, codigo),
        CONSTRAINT uq_adm_tipo_regla_tarifaria_company_id UNIQUE (company_id, tipo_regla_tarifaria_id)
    );

CREATE INDEX IF NOT EXISTS ix_adm_tipo_regla_tarifaria_company ON public.adm_tipo_regla_tarifaria (company_id);

CREATE TABLE
    IF NOT EXISTS public.adm_tipo_ajuste_tarifario (
        tipo_ajuste_tarifario_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id bigint NOT NULL,
        codigo varchar(30) NOT NULL,
        nombre varchar(100) NOT NULL,
        descripcion varchar(300),
        status_id smallint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL DEFAULT now (),
        created_by varchar(100) NOT NULL DEFAULT current_user,
        updated_at timestamptz,
        updated_by varchar(100),
        CONSTRAINT fk_adm_tipo_ajuste_tarifario_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
        CONSTRAINT ck_adm_tipo_ajuste_tarifario_status CHECK (status_id IN (0, 1)),
        CONSTRAINT uq_adm_tipo_ajuste_tarifario_company_codigo UNIQUE (company_id, codigo),
        CONSTRAINT uq_adm_tipo_ajuste_tarifario_company_id UNIQUE (company_id, tipo_ajuste_tarifario_id)
    );

CREATE INDEX IF NOT EXISTS ix_adm_tipo_ajuste_tarifario_company ON public.adm_tipo_ajuste_tarifario (company_id);

CREATE TABLE
    IF NOT EXISTS public.adm_servicio (
        servicio_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id bigint NOT NULL,
        tipo_servicio_id bigint NOT NULL,
        codigo varchar(30) NOT NULL,
        nombre varchar(150) NOT NULL,
        descripcion varchar(300),
        es_asignable_cliente boolean NOT NULL DEFAULT false,
        usa_condicion_medicion boolean NOT NULL DEFAULT false,
        facturable_app boolean NOT NULL DEFAULT false,
        app_orden integer NOT NULL DEFAULT 0,
        permite_evento boolean NOT NULL DEFAULT false,
        genera_por_regla boolean NOT NULL DEFAULT false,
        cont_account_id bigint,
        orden_visual integer NOT NULL DEFAULT 0,
        status_id smallint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL DEFAULT now (),
        created_by varchar(100) NOT NULL DEFAULT current_user,
        updated_at timestamptz,
        updated_by varchar(100),
        CONSTRAINT fk_adm_servicio_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
        CONSTRAINT fk_adm_servicio_tipo_servicio FOREIGN KEY (company_id, tipo_servicio_id) REFERENCES public.adm_tipo_servicio (company_id, tipo_servicio_id),
        CONSTRAINT ck_adm_servicio_status CHECK (status_id IN (0, 1)),
        CONSTRAINT uq_adm_servicio_company_codigo UNIQUE (company_id, codigo),
        CONSTRAINT uq_adm_servicio_company_id UNIQUE (company_id, servicio_id)
    );

CREATE INDEX IF NOT EXISTS ix_adm_servicio_company ON public.adm_servicio (company_id);

CREATE INDEX IF NOT EXISTS ix_adm_servicio_company_tipo ON public.adm_servicio (company_id, tipo_servicio_id);

CREATE INDEX IF NOT EXISTS ix_adm_servicio_company_app ON public.adm_servicio (company_id, facturable_app, app_orden);

-- -----------------------------------------------------------------------------
-- 2) Tablas operativas del motor
-- -----------------------------------------------------------------------------
CREATE TABLE
    IF NOT EXISTS public.adm_cuadro_tarifario (
        cuadro_tarifario_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id bigint NOT NULL,
        servicio_id bigint NOT NULL,
        categoria_regulatoria_id bigint,
        condicion_medicion_id bigint,
        segmento_tarifario_id bigint,
        codigo varchar(40) NOT NULL,
        nombre varchar(150) NOT NULL,
        descripcion varchar(300),
        vigencia_desde date NOT NULL,
        vigencia_hasta date,
        prioridad integer NOT NULL DEFAULT 1,
        referencia_normativa varchar(150),
        status_id smallint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL DEFAULT now (),
        created_by varchar(100) NOT NULL DEFAULT current_user,
        updated_at timestamptz,
        updated_by varchar(100),
        CONSTRAINT fk_adm_cuadro_tarifario_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
        CONSTRAINT fk_adm_cuadro_tarifario_servicio FOREIGN KEY (company_id, servicio_id) REFERENCES public.adm_servicio (company_id, servicio_id),
        CONSTRAINT fk_adm_cuadro_tarifario_categoria FOREIGN KEY (company_id, categoria_regulatoria_id) REFERENCES public.adm_categoria_regulatoria (company_id, categoria_regulatoria_id),
        CONSTRAINT fk_adm_cuadro_tarifario_condicion FOREIGN KEY (company_id, condicion_medicion_id) REFERENCES public.adm_condicion_medicion (company_id, condicion_medicion_id),
        CONSTRAINT fk_adm_cuadro_tarifario_segmento FOREIGN KEY (company_id, segmento_tarifario_id) REFERENCES public.adm_segmento_tarifario (company_id, segmento_tarifario_id),
        CONSTRAINT ck_adm_cuadro_tarifario_status CHECK (status_id IN (0, 1)),
        CONSTRAINT ck_adm_cuadro_tarifario_prioridad CHECK (prioridad >= 1),
        CONSTRAINT ck_adm_cuadro_tarifario_vigencia CHECK (
            vigencia_hasta IS NULL
            OR vigencia_hasta >= vigencia_desde
        ),
        CONSTRAINT uq_adm_cuadro_tarifario_company_codigo UNIQUE (company_id, codigo),
        CONSTRAINT uq_adm_cuadro_tarifario_company_id UNIQUE (company_id, cuadro_tarifario_id)
    );

CREATE INDEX IF NOT EXISTS ix_adm_cuadro_tarifario_company ON public.adm_cuadro_tarifario (company_id);

CREATE INDEX IF NOT EXISTS ix_adm_cuadro_tarifario_resolucion ON public.adm_cuadro_tarifario (
    company_id,
    servicio_id,
    categoria_regulatoria_id,
    condicion_medicion_id,
    segmento_tarifario_id,
    vigencia_desde,
    vigencia_hasta
);

CREATE TABLE
    IF NOT EXISTS public.adm_regla_tarifaria (
        regla_tarifaria_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id bigint NOT NULL,
        cuadro_tarifario_id bigint NOT NULL,
        tipo_regla_tarifaria_id bigint NOT NULL,
        orden integer NOT NULL DEFAULT 1,
        consumo_minimo numeric(18, 4),
        consumo_maximo numeric(18, 4),
        monto_fijo numeric(18, 4),
        monto_unitario numeric(18, 4),
        porcentaje numeric(18, 6),
        servicio_referencia_id bigint,
        parametros jsonb,
        status_id smallint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL DEFAULT now (),
        created_by varchar(100) NOT NULL DEFAULT current_user,
        updated_at timestamptz,
        updated_by varchar(100),
        CONSTRAINT fk_adm_regla_tarifaria_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
        CONSTRAINT fk_adm_regla_tarifaria_cuadro FOREIGN KEY (company_id, cuadro_tarifario_id) REFERENCES public.adm_cuadro_tarifario (company_id, cuadro_tarifario_id),
        CONSTRAINT fk_adm_regla_tarifaria_tipo FOREIGN KEY (company_id, tipo_regla_tarifaria_id) REFERENCES public.adm_tipo_regla_tarifaria (company_id, tipo_regla_tarifaria_id),
        CONSTRAINT fk_adm_regla_tarifaria_servicio_referencia FOREIGN KEY (company_id, servicio_referencia_id) REFERENCES public.adm_servicio (company_id, servicio_id),
        CONSTRAINT ck_adm_regla_tarifaria_status CHECK (status_id IN (0, 1)),
        CONSTRAINT ck_adm_regla_tarifaria_orden CHECK (orden >= 1),
        CONSTRAINT ck_adm_regla_tarifaria_rango CHECK (
            consumo_maximo IS NULL
            OR consumo_minimo IS NULL
            OR consumo_maximo >= consumo_minimo
        ),
        CONSTRAINT ck_adm_regla_tarifaria_montos CHECK (
            (
                monto_fijo IS NULL
                OR monto_fijo >= 0
            )
            AND (
                monto_unitario IS NULL
                OR monto_unitario >= 0
            )
            AND (
                porcentaje IS NULL
                OR porcentaje >= 0
            )
        )
    );

CREATE UNIQUE INDEX IF NOT EXISTS uq_adm_regla_tarifaria_company_cuadro_orden ON public.adm_regla_tarifaria (company_id, cuadro_tarifario_id, orden);

CREATE INDEX IF NOT EXISTS ix_adm_regla_tarifaria_company ON public.adm_regla_tarifaria (company_id);

CREATE TABLE
    IF NOT EXISTS public.adm_ajuste_tarifario (
        ajuste_tarifario_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id bigint NOT NULL,
        cuadro_tarifario_id bigint NOT NULL,
        tipo_ajuste_tarifario_id bigint NOT NULL,
        orden integer NOT NULL DEFAULT 1,
        servicio_referencia_id bigint,
        monto_fijo numeric(18, 4),
        porcentaje numeric(18, 6),
        tope_maximo numeric(18, 4),
        condicion_codigo varchar(50),
        parametros jsonb,
        status_id smallint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL DEFAULT now (),
        created_by varchar(100) NOT NULL DEFAULT current_user,
        updated_at timestamptz,
        updated_by varchar(100),
        CONSTRAINT fk_adm_ajuste_tarifario_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
        CONSTRAINT fk_adm_ajuste_tarifario_cuadro FOREIGN KEY (company_id, cuadro_tarifario_id) REFERENCES public.adm_cuadro_tarifario (company_id, cuadro_tarifario_id),
        CONSTRAINT fk_adm_ajuste_tarifario_tipo FOREIGN KEY (company_id, tipo_ajuste_tarifario_id) REFERENCES public.adm_tipo_ajuste_tarifario (company_id, tipo_ajuste_tarifario_id),
        CONSTRAINT fk_adm_ajuste_tarifario_servicio_referencia FOREIGN KEY (company_id, servicio_referencia_id) REFERENCES public.adm_servicio (company_id, servicio_id),
        CONSTRAINT ck_adm_ajuste_tarifario_status CHECK (status_id IN (0, 1)),
        CONSTRAINT ck_adm_ajuste_tarifario_orden CHECK (orden >= 1),
        CONSTRAINT ck_adm_ajuste_tarifario_valores CHECK (
            (
                monto_fijo IS NULL
                OR monto_fijo >= 0
            )
            AND (
                porcentaje IS NULL
                OR porcentaje >= 0
            )
            AND (
                tope_maximo IS NULL
                OR tope_maximo >= 0
            )
        )
    );

CREATE UNIQUE INDEX IF NOT EXISTS uq_adm_ajuste_tarifario_company_cuadro_orden ON public.adm_ajuste_tarifario (company_id, cuadro_tarifario_id, orden);

CREATE INDEX IF NOT EXISTS ix_adm_ajuste_tarifario_company ON public.adm_ajuste_tarifario (company_id);

CREATE TABLE
    IF NOT EXISTS public.adm_cliente_servicio (
        cliente_servicio_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id bigint NOT NULL,
        cliente_id bigint NOT NULL,
        servicio_id bigint NOT NULL,
        categoria_regulatoria_id bigint,
        condicion_medicion_id bigint,
        segmento_tarifario_id bigint,
        medidor_id bigint,
        cuadro_tarifario_id bigint,
        fecha_alta date NOT NULL,
        fecha_baja date,
        status_id smallint NOT NULL DEFAULT 1,
        created_at timestamptz NOT NULL DEFAULT now (),
        created_by varchar(100) NOT NULL DEFAULT current_user,
        updated_at timestamptz,
        updated_by varchar(100),
        CONSTRAINT fk_adm_cliente_servicio_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
        CONSTRAINT fk_adm_cliente_servicio_servicio FOREIGN KEY (company_id, servicio_id) REFERENCES public.adm_servicio (company_id, servicio_id),
        CONSTRAINT fk_adm_cliente_servicio_categoria FOREIGN KEY (company_id, categoria_regulatoria_id) REFERENCES public.adm_categoria_regulatoria (company_id, categoria_regulatoria_id),
        CONSTRAINT fk_adm_cliente_servicio_condicion FOREIGN KEY (company_id, condicion_medicion_id) REFERENCES public.adm_condicion_medicion (company_id, condicion_medicion_id),
        CONSTRAINT fk_adm_cliente_servicio_segmento FOREIGN KEY (company_id, segmento_tarifario_id) REFERENCES public.adm_segmento_tarifario (company_id, segmento_tarifario_id),
        CONSTRAINT fk_adm_cliente_servicio_cuadro FOREIGN KEY (company_id, cuadro_tarifario_id) REFERENCES public.adm_cuadro_tarifario (company_id, cuadro_tarifario_id),
        CONSTRAINT ck_adm_cliente_servicio_status CHECK (status_id IN (0, 1)),
        CONSTRAINT ck_adm_cliente_servicio_fechas CHECK (
            fecha_baja IS NULL
            OR fecha_baja >= fecha_alta
        )
    );

CREATE INDEX IF NOT EXISTS ix_adm_cliente_servicio_company ON public.adm_cliente_servicio (company_id);

CREATE INDEX IF NOT EXISTS ix_adm_cliente_servicio_cliente ON public.adm_cliente_servicio (company_id, cliente_id);

CREATE INDEX IF NOT EXISTS ix_adm_cliente_servicio_resolucion ON public.adm_cliente_servicio (company_id, cliente_id, servicio_id, status_id);

-- -----------------------------------------------------------------------------
-- 3) Seeds base multiempresa
-- -----------------------------------------------------------------------------
INSERT INTO
    public.adm_tipo_servicio (
        company_id,
        codigo,
        nombre,
        descripcion,
        status_id,
        created_at,
        created_by
    )
SELECT
    c.company_id,
    s.codigo,
    s.nombre,
    s.descripcion,
    1,
    now (),
    'system'
FROM
    public.cfg_company c
    CROSS JOIN (
        VALUES
            (
                'BASE',
                'Servicio Base Recurrente',
                'Servicio permanente que puede vivir en adm_cliente_servicio y participar en facturacion periodica.'
            ),
            (
                'EVENTUAL',
                'Servicio Colateral o Eventual',
                'Servicio que se cobra por ocurrencia o gestion puntual.'
            ),
            (
                'DERIVADO',
                'Cargo Regulatorio Derivado',
                'Concepto que nace por regla a partir de otro servicio base.'
            )
    ) AS s (codigo, nombre, descripcion) ON CONFLICT (company_id, codigo) DO
UPDATE
SET
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    status_id = 1,
    updated_at = now (),
    updated_by = 'system';

INSERT INTO
    public.adm_categoria_regulatoria (
        company_id,
        codigo,
        nombre,
        descripcion,
        status_id,
        created_at,
        created_by
    )
SELECT
    c.company_id,
    s.codigo,
    s.nombre,
    s.descripcion,
    1,
    now (),
    'system'
FROM
    public.cfg_company c
    CROSS JOIN (
        VALUES
            (
                'DOMESTICO',
                'Domestico',
                'Categoria regulatoria para uso residencial.'
            ),
            (
                'COMERCIAL',
                'Comercial',
                'Categoria regulatoria para actividad comercial.'
            ),
            (
                'INDUSTRIAL',
                'Industrial',
                'Categoria regulatoria para actividad industrial.'
            ),
            (
                'GUBERNAMENTAL',
                'Gubernamental',
                'Categoria regulatoria para entidades publicas o gubernamentales.'
            )
    ) AS s (codigo, nombre, descripcion) ON CONFLICT (company_id, codigo) DO
UPDATE
SET
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    status_id = 1,
    updated_at = now (),
    updated_by = 'system';

INSERT INTO
    public.adm_segmento_tarifario (
        company_id,
        categoria_regulatoria_id,
        codigo,
        nombre,
        descripcion,
        status_id,
        created_at,
        created_by
    )
SELECT
    c.company_id,
    cr.categoria_regulatoria_id,
    s.codigo,
    s.nombre,
    s.descripcion,
    1,
    now (),
    'system'
FROM
    public.cfg_company c
    JOIN public.adm_categoria_regulatoria cr ON cr.company_id = c.company_id
    JOIN (
        VALUES
            (
                'DOMESTICO',
                'DOMESTICA_BAJA',
                'Domestica Baja',
                'Segmento tarifario domestico sin medicion.'
            ),
            (
                'DOMESTICO',
                'DOMESTICA_MEDIA',
                'Domestica Media',
                'Segmento tarifario domestico sin medicion.'
            ),
            (
                'DOMESTICO',
                'DOMESTICA_ALTA',
                'Domestica Alta',
                'Segmento tarifario domestico sin medicion.'
            ),
            (
                'DOMESTICO',
                'DOMESTICA_TULIAN',
                'Domestica Tulian',
                'Segmento tarifario domestico especial.'
            ),
            (
                'DOMESTICO',
                'PREVENTIVA_DOMESTICA',
                'Preventiva Domestica',
                'Segmento tarifario domestico preventivo.'
            ),
            (
                'COMERCIAL',
                'COMERCIAL_PEQUENA',
                'Comercial Pequena',
                'Segmento tarifario comercial sin medicion.'
            ),
            (
                'COMERCIAL',
                'COMERCIAL_MEDIANA',
                'Comercial Mediana',
                'Segmento tarifario comercial sin medicion.'
            ),
            (
                'COMERCIAL',
                'COMERCIAL_GRANDE',
                'Comercial Grande',
                'Segmento tarifario comercial sin medicion.'
            ),
            (
                'COMERCIAL',
                'PREVENTIVA_COMERCIAL',
                'Preventiva Comercial',
                'Segmento tarifario comercial preventivo.'
            ),
            (
                'INDUSTRIAL',
                'INDUSTRIAL_PEQUENA',
                'Industrial Pequena',
                'Segmento tarifario industrial sin medicion.'
            ),
            (
                'INDUSTRIAL',
                'INDUSTRIAL_MEDIANA',
                'Industrial Mediana',
                'Segmento tarifario industrial sin medicion.'
            ),
            (
                'INDUSTRIAL',
                'INDUSTRIAL_GRANDE',
                'Industrial Grande',
                'Segmento tarifario industrial sin medicion.'
            ),
            (
                'INDUSTRIAL',
                'INDUSTRIAL_ENP',
                'Industrial ENP',
                'Segmento tarifario industrial especial para terminales portuarias.'
            ),
            (
                'GUBERNAMENTAL',
                'GUBERNAMENTAL_UNICA',
                'Publica Unica',
                'Segmento tarifario gubernamental sin medicion.'
            ),
            (
                'GUBERNAMENTAL',
                'PUBLICA_UNICA',
                'Publica Unica Especial',
                'Segmento tarifario gubernamental especial usado por APC en tarifas sin medicion.'
            )
    ) AS s (categoria_codigo, codigo, nombre, descripcion) ON cr.codigo = s.categoria_codigo
ON CONFLICT (company_id, codigo) DO
UPDATE
SET
    categoria_regulatoria_id = EXCLUDED.categoria_regulatoria_id,
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    status_id = 1,
    updated_at = now (),
    updated_by = 'system';

INSERT INTO
    public.adm_condicion_medicion (
        company_id,
        codigo,
        nombre,
        descripcion,
        requiere_lectura,
        status_id,
        created_at,
        created_by
    )
SELECT
    c.company_id,
    s.codigo,
    s.nombre,
    s.descripcion,
    s.requiere_lectura,
    1,
    now (),
    'system'
FROM
    public.cfg_company c
    CROSS JOIN (
        VALUES
            (
                'CON_MEDICION',
                'Con Medicion',
                'La tarifa depende de lectura o consumo medido.',
                true
            ),
            (
                'SIN_MEDICION',
                'Sin Medicion',
                'La tarifa no depende de lectura y se resuelve por monto fijo o regla especial.',
                false
            ),
            (
                'NO_APLICA',
                'No Aplica',
                'La condicion de medicion no participa en este servicio.',
                false
            )
    ) AS s (codigo, nombre, descripcion, requiere_lectura) ON CONFLICT (company_id, codigo) DO
UPDATE
SET
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    requiere_lectura = EXCLUDED.requiere_lectura,
    status_id = 1,
    updated_at = now (),
    updated_by = 'system';

INSERT INTO
    public.adm_tipo_regla_tarifaria (
        company_id,
        codigo,
        nombre,
        descripcion,
        status_id,
        created_at,
        created_by
    )
SELECT
    c.company_id,
    s.codigo,
    s.nombre,
    s.descripcion,
    1,
    now (),
    'system'
FROM
    public.cfg_company c
    CROSS JOIN (
        VALUES
            (
                'MONTO_FIJO',
                'Monto Fijo',
                'La tarifa se resuelve por un monto fijo.'
            ),
            (
                'RANGO_CONSUMO',
                'Rango de Consumo',
                'La tarifa se resuelve por tramo o rango de consumo.'
            ),
            (
                'PORCENTAJE_SERVICIO',
                'Porcentaje sobre otro servicio',
                'La tarifa se resuelve como porcentaje sobre otro servicio o concepto base.'
            ),
            (
                'REGLA_ESPECIAL',
                'Regla Especial',
                'La tarifa se resuelve por formula o logica especial.'
            )
    ) AS s (codigo, nombre, descripcion) ON CONFLICT (company_id, codigo) DO
UPDATE
SET
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    status_id = 1,
    updated_at = now (),
    updated_by = 'system';

INSERT INTO
    public.adm_tipo_ajuste_tarifario (
        company_id,
        codigo,
        nombre,
        descripcion,
        status_id,
        created_at,
        created_by
    )
SELECT
    c.company_id,
    s.codigo,
    s.nombre,
    s.descripcion,
    1,
    now (),
    'system'
FROM
    public.cfg_company c
    CROSS JOIN (
        VALUES
            (
                'DESCUENTO',
                'Descuento',
                'Disminucion directa sobre el monto base.'
            ),
            (
                'TOPE',
                'Tope',
                'Limite maximo aplicable al ajuste o beneficio.'
            ),
            (
                'EXONERACION',
                'Exoneracion',
                'Elimina total o parcialmente el cobro.'
            ),
            (
                'RECARGO',
                'Recargo',
                'Incrementa el monto por condicion especial.'
            ),
            (
                'BENEFICIO_ESPECIAL',
                'Beneficio Especial',
                'Beneficio regulado o legal sujeto a condicion.'
            )
    ) AS s (codigo, nombre, descripcion) ON CONFLICT (company_id, codigo) DO
UPDATE
SET
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    status_id = 1,
    updated_at = now (),
    updated_by = 'system';

INSERT INTO
    public.adm_servicio (
        company_id,
        tipo_servicio_id,
        codigo,
        nombre,
        descripcion,
        es_asignable_cliente,
        usa_condicion_medicion,
        facturable_app,
        app_orden,
        permite_evento,
        genera_por_regla,
        orden_visual,
        status_id,
        created_at,
        created_by
    )
SELECT
    c.company_id,
    ts.tipo_servicio_id,
    s.codigo,
    s.nombre,
    s.descripcion,
    s.es_asignable_cliente,
    s.usa_condicion_medicion,
    s.facturable_app,
    s.app_orden,
    s.permite_evento,
    s.genera_por_regla,
    s.orden_visual,
    1,
    now (),
    'system'
FROM
    public.cfg_company c
    JOIN public.adm_tipo_servicio ts ON ts.company_id = c.company_id
    JOIN (
        VALUES
            (
                'BASE',
                'AGUA_POTABLE',
                'Agua Potable',
                'Servicio base principal. Puede facturarse con medicion o sin medicion.',
                true,
                true,
                true,
                10,
                false,
                false,
                10
            ),
            (
                'BASE',
                'ALCANTARILLADO',
                'Alcantarillado',
                'Servicio base recurrente. Normalmente usa No Aplica en condicion de medicion.',
                true,
                false,
                true,
                20,
                false,
                false,
                20
            ),
            (
                'EVENTUAL',
                'CONEXION',
                'Conexion',
                'Cobro por conexion del servicio.',
                false,
                false,
                false,
                0,
                true,
                false,
                30
            ),
            (
                'EVENTUAL',
                'INSTALACION',
                'Instalacion',
                'Cobro por instalacion del servicio.',
                false,
                false,
                false,
                0,
                true,
                false,
                40
            ),
            (
                'EVENTUAL',
                'MODIFICACION',
                'Modificacion',
                'Cobro por modificacion del servicio.',
                false,
                false,
                false,
                0,
                true,
                false,
                50
            ),
            (
                'EVENTUAL',
                'TRASLADO',
                'Traslado',
                'Cobro por traslado del servicio.',
                false,
                false,
                false,
                0,
                true,
                false,
                60
            ),
            (
                'EVENTUAL',
                'CORTE_RECONEXION',
                'Corte y Reconexion',
                'Cobro colateral regulado por corte o reconexion.',
                false,
                false,
                false,
                0,
                true,
                false,
                70
            ),
            (
                'EVENTUAL',
                'AGUA_CISTERNA',
                'Agua Potable por Cisterna',
                'Servicio colateral regulado suministrado por cisterna.',
                false,
                false,
                false,
                0,
                true,
                false,
                80
            ),
            (
                'EVENTUAL',
                'OTROS_COLATERALES',
                'Otros Servicios Colaterales Regulados',
                'Cajon regulatorio para conceptos colaterales aprobados.',
                false,
                false,
                false,
                0,
                true,
                false,
                90
            ),
            (
                'DERIVADO',
                'TASA_AMBIENTAL',
                'Tasa Ambiental',
                'Se genera por regla como cargo derivado de agua potable segun cuadro tarifario vigente.',
                false,
                true,
                false,
                0,
                false,
                true,
                100
            ),
            (
                'DERIVADO',
                'TASA_SVA_ERSAPS',
                'Tasa SVA ERSAPS',
                'Se genera por regla como concepto regulatorio separado.',
                false,
                false,
                false,
                0,
                false,
                true,
                110
            )
    ) AS s (
        tipo_codigo,
        codigo,
        nombre,
        descripcion,
        es_asignable_cliente,
        usa_condicion_medicion,
        facturable_app,
        app_orden,
        permite_evento,
        genera_por_regla,
        orden_visual
    ) ON ts.codigo = s.tipo_codigo ON CONFLICT (company_id, codigo) DO
UPDATE
SET
    tipo_servicio_id = EXCLUDED.tipo_servicio_id,
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    es_asignable_cliente = EXCLUDED.es_asignable_cliente,
    usa_condicion_medicion = EXCLUDED.usa_condicion_medicion,
    facturable_app = EXCLUDED.facturable_app,
    app_orden = EXCLUDED.app_orden,
    permite_evento = EXCLUDED.permite_evento,
    genera_por_regla = EXCLUDED.genera_por_regla,
    orden_visual = EXCLUDED.orden_visual,
    status_id = 1,
    updated_at = now (),
    updated_by = 'system';
