-- =============================================================================
-- Core CAI / correlativo offline para facturacion formal V3
-- Fecha: 2026-04-18
-- Alcance:
--   - maestro de CAI
--   - bloques reservados por lector/dispositivo/ruta
--   - consumo de correlativos offline con idempotencia
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.adm_cai_facturacion (
    cai_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    codigo_cai varchar(100) NOT NULL,
    prefijo_documento varchar(30) NOT NULL,
    rango_desde bigint NOT NULL,
    rango_hasta bigint NOT NULL,
    vigencia_desde date NOT NULL,
    vigencia_hasta date,
    observaciones varchar(300),
    status_id smallint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),
    CONSTRAINT fk_adm_cai_facturacion_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT ck_adm_cai_facturacion_status CHECK (status_id IN (0, 1)),
    CONSTRAINT ck_adm_cai_facturacion_rango CHECK (rango_desde > 0 AND rango_hasta >= rango_desde),
    CONSTRAINT ck_adm_cai_facturacion_vigencia CHECK (vigencia_hasta IS NULL OR vigencia_hasta >= vigencia_desde),
    CONSTRAINT uq_adm_cai_facturacion_company_codigo UNIQUE (company_id, codigo_cai)
);

CREATE INDEX IF NOT EXISTS ix_adm_cai_facturacion_company
    ON public.adm_cai_facturacion (company_id);

CREATE INDEX IF NOT EXISTS ix_adm_cai_facturacion_vigencia
    ON public.adm_cai_facturacion (company_id, status_id, vigencia_desde, vigencia_hasta);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_adm_cai_facturacion_company_cai_id'
          AND conrelid = 'public.adm_cai_facturacion'::regclass
    ) THEN
        ALTER TABLE public.adm_cai_facturacion
            ADD CONSTRAINT uq_adm_cai_facturacion_company_cai_id
            UNIQUE (company_id, cai_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.adm_cai_bloque_reservado (
    cai_bloque_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    cai_id bigint NOT NULL,
    usuario_asignado varchar(100),
    dispositivo_id varchar(100),
    ruta_codigo varchar(30),
    correlativo_desde bigint NOT NULL,
    correlativo_hasta bigint NOT NULL,
    correlativo_actual bigint NOT NULL,
    fecha_reserva date NOT NULL DEFAULT current_date,
    fecha_expiracion date,
    estado_codigo varchar(30) NOT NULL DEFAULT 'RESERVADO',
    status_id smallint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),
    CONSTRAINT fk_adm_cai_bloque_reservado_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_adm_cai_bloque_reservado_cai FOREIGN KEY (company_id, cai_id) REFERENCES public.adm_cai_facturacion (company_id, cai_id),
    CONSTRAINT ck_adm_cai_bloque_reservado_status CHECK (status_id IN (0, 1)),
    CONSTRAINT ck_adm_cai_bloque_reservado_rango CHECK (
        correlativo_desde > 0
        AND correlativo_hasta >= correlativo_desde
        AND correlativo_actual >= correlativo_desde - 1
        AND correlativo_actual <= correlativo_hasta
    ),
    CONSTRAINT ck_adm_cai_bloque_reservado_fechas CHECK (fecha_expiracion IS NULL OR fecha_expiracion >= fecha_reserva)
);

CREATE INDEX IF NOT EXISTS ix_adm_cai_bloque_reservado_company
    ON public.adm_cai_bloque_reservado (company_id);

CREATE INDEX IF NOT EXISTS ix_adm_cai_bloque_reservado_lookup
    ON public.adm_cai_bloque_reservado (company_id, cai_id, status_id, fecha_reserva);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_adm_cai_bloque_reservado_company_bloque_id'
          AND conrelid = 'public.adm_cai_bloque_reservado'::regclass
    ) THEN
        ALTER TABLE public.adm_cai_bloque_reservado
            ADD CONSTRAINT uq_adm_cai_bloque_reservado_company_bloque_id
            UNIQUE (company_id, cai_bloque_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.adm_cai_correlativo_emitido (
    cai_correlativo_emitido_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    cai_bloque_id bigint NOT NULL,
    cai_id bigint NOT NULL,
    correlativo bigint NOT NULL,
    numero_factura varchar(80) NOT NULL,
    cliente_id bigint,
    lectura_uuid varchar(100),
    factura_id bigint,
    estado_codigo varchar(30) NOT NULL DEFAULT 'PENDING_OFFLINE',
    fecha_emision timestamptz NOT NULL DEFAULT now(),
    fecha_confirmacion timestamptz,
    detalle_conflicto varchar(300),
    status_id smallint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),
    CONSTRAINT fk_adm_cai_correlativo_emitido_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_adm_cai_correlativo_emitido_bloque FOREIGN KEY (company_id, cai_bloque_id) REFERENCES public.adm_cai_bloque_reservado (company_id, cai_bloque_id),
    CONSTRAINT fk_adm_cai_correlativo_emitido_cai FOREIGN KEY (company_id, cai_id) REFERENCES public.adm_cai_facturacion (company_id, cai_id),
    CONSTRAINT ck_adm_cai_correlativo_emitido_status CHECK (status_id IN (0, 1))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_adm_cai_correlativo_emitido_company_cai_corr
    ON public.adm_cai_correlativo_emitido (company_id, cai_id, correlativo);

CREATE UNIQUE INDEX IF NOT EXISTS uq_adm_cai_correlativo_emitido_company_numero
    ON public.adm_cai_correlativo_emitido (company_id, numero_factura);

CREATE UNIQUE INDEX IF NOT EXISTS uq_adm_cai_correlativo_emitido_company_lectura
    ON public.adm_cai_correlativo_emitido (company_id, lectura_uuid)
    WHERE lectura_uuid IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_adm_cai_correlativo_emitido_company
    ON public.adm_cai_correlativo_emitido (company_id, estado_codigo, fecha_emision);

DROP FUNCTION IF EXISTS public.sp_adm_reservar_bloque_cai(bigint, bigint, varchar, varchar, varchar, integer, date, varchar);

CREATE OR REPLACE FUNCTION public.sp_adm_reservar_bloque_cai(
    p_company_id bigint,
    p_cai_id bigint,
    p_usuario_asignado varchar DEFAULT NULL,
    p_dispositivo_id varchar DEFAULT NULL,
    p_ruta_codigo varchar DEFAULT NULL,
    p_cantidad integer DEFAULT 100,
    p_fecha_expiracion date DEFAULT NULL,
    p_usuario varchar DEFAULT current_user
)
RETURNS TABLE (
    cai_bloque_id bigint,
    correlativo_desde bigint,
    correlativo_hasta bigint
)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_cai public.adm_cai_facturacion%ROWTYPE;
    v_ultimo bigint;
BEGIN
    IF p_cantidad IS NULL OR p_cantidad <= 0 THEN
        RAISE EXCEPTION 'La cantidad a reservar debe ser mayor que cero.';
    END IF;

    SELECT *
    INTO v_cai
    FROM public.adm_cai_facturacion c
    WHERE c.company_id = p_company_id
      AND c.cai_id = p_cai_id
      AND c.status_id = 1
      AND current_date >= c.vigencia_desde
      AND (c.vigencia_hasta IS NULL OR current_date <= c.vigencia_hasta);

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe CAI activo/vigente para company_id=% cai_id=%.', p_company_id, p_cai_id;
    END IF;

    SELECT COALESCE(MAX(b.correlativo_hasta), v_cai.rango_desde - 1)
    INTO v_ultimo
    FROM public.adm_cai_bloque_reservado b
    WHERE b.company_id = p_company_id
      AND b.cai_id = p_cai_id;

    correlativo_desde := v_ultimo + 1;
    correlativo_hasta := correlativo_desde + p_cantidad - 1;

    IF correlativo_hasta > v_cai.rango_hasta THEN
        RAISE EXCEPTION 'CAI agotado para company_id=% cai_id=%. Siguiente=% ultimo=%',
            p_company_id, p_cai_id, correlativo_desde, v_cai.rango_hasta;
    END IF;

    INSERT INTO public.adm_cai_bloque_reservado (
        company_id,
        cai_id,
        usuario_asignado,
        dispositivo_id,
        ruta_codigo,
        correlativo_desde,
        correlativo_hasta,
        correlativo_actual,
        fecha_reserva,
        fecha_expiracion,
        estado_codigo,
        status_id,
        created_by
    )
    VALUES (
        p_company_id,
        p_cai_id,
        NULLIF(BTRIM(p_usuario_asignado), ''),
        NULLIF(BTRIM(p_dispositivo_id), ''),
        NULLIF(BTRIM(p_ruta_codigo), ''),
        correlativo_desde,
        correlativo_hasta,
        correlativo_desde - 1,
        current_date,
        p_fecha_expiracion,
        'RESERVADO',
        1,
        COALESCE(NULLIF(BTRIM(p_usuario), ''), current_user)
    )
    RETURNING adm_cai_bloque_reservado.cai_bloque_id
    INTO cai_bloque_id;

    RETURN NEXT;
END;
$function$;

DROP FUNCTION IF EXISTS public.sp_adm_consumir_correlativo_bloque_cai(bigint, bigint, bigint, varchar, varchar);

CREATE OR REPLACE FUNCTION public.sp_adm_consumir_correlativo_bloque_cai(
    p_company_id bigint,
    p_cai_bloque_id bigint,
    p_cliente_id bigint DEFAULT NULL,
    p_lectura_uuid varchar DEFAULT NULL,
    p_usuario varchar DEFAULT current_user
)
RETURNS TABLE (
    cai_id bigint,
    correlativo bigint,
    numero_factura varchar,
    prefijo_documento varchar,
    codigo_cai varchar
)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_bloque public.adm_cai_bloque_reservado%ROWTYPE;
    v_cai public.adm_cai_facturacion%ROWTYPE;
    v_existente public.adm_cai_correlativo_emitido%ROWTYPE;
BEGIN
    IF NULLIF(BTRIM(COALESCE(p_lectura_uuid, '')), '') IS NOT NULL THEN
        SELECT *
        INTO v_existente
        FROM public.adm_cai_correlativo_emitido e
        WHERE e.company_id = p_company_id
          AND e.lectura_uuid = p_lectura_uuid;

        IF FOUND THEN
            SELECT c.prefijo_documento, c.codigo_cai
            INTO prefijo_documento, codigo_cai
            FROM public.adm_cai_facturacion c
            WHERE c.company_id = p_company_id
              AND c.cai_id = v_existente.cai_id;

            cai_id := v_existente.cai_id;
            correlativo := v_existente.correlativo;
            numero_factura := v_existente.numero_factura;
            RETURN NEXT;
            RETURN;
        END IF;
    END IF;

    SELECT *
    INTO v_bloque
    FROM public.adm_cai_bloque_reservado b
    WHERE b.company_id = p_company_id
      AND b.cai_bloque_id = p_cai_bloque_id
      AND b.status_id = 1
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Bloque CAI invalido para company_id=% cai_bloque_id=%.', p_company_id, p_cai_bloque_id;
    END IF;

    IF v_bloque.fecha_expiracion IS NOT NULL AND current_date > v_bloque.fecha_expiracion THEN
        RAISE EXCEPTION 'Bloque CAI vencido para cai_bloque_id=%.', p_cai_bloque_id;
    END IF;

    SELECT *
    INTO v_cai
    FROM public.adm_cai_facturacion c
    WHERE c.company_id = p_company_id
      AND c.cai_id = v_bloque.cai_id
      AND c.status_id = 1
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'CAI maestro no disponible para cai_bloque_id=%.', p_cai_bloque_id;
    END IF;

    correlativo := v_bloque.correlativo_actual + 1;
    IF correlativo > v_bloque.correlativo_hasta THEN
        RAISE EXCEPTION 'CAI_AGOTADO: bloque % ya no tiene correlativos disponibles.', p_cai_bloque_id;
    END IF;

    prefijo_documento := v_cai.prefijo_documento;
    codigo_cai := v_cai.codigo_cai;
    cai_id := v_cai.cai_id;
    numero_factura := prefijo_documento || LPAD(correlativo::text, 8, '0');

    UPDATE public.adm_cai_bloque_reservado
    SET correlativo_actual = correlativo,
        updated_at = now(),
        updated_by = COALESCE(NULLIF(BTRIM(p_usuario), ''), current_user)
    WHERE company_id = p_company_id
      AND cai_bloque_id = p_cai_bloque_id;

    INSERT INTO public.adm_cai_correlativo_emitido (
        company_id,
        cai_bloque_id,
        cai_id,
        correlativo,
        numero_factura,
        cliente_id,
        lectura_uuid,
        estado_codigo,
        created_by
    )
    VALUES (
        p_company_id,
        p_cai_bloque_id,
        cai_id,
        correlativo,
        numero_factura,
        p_cliente_id,
        NULLIF(BTRIM(COALESCE(p_lectura_uuid, '')), ''),
        'PENDING_OFFLINE',
        COALESCE(NULLIF(BTRIM(p_usuario), ''), current_user)
    );

    RETURN NEXT;
END;
$function$;
