-- =============================================================================
-- Modelo NC/ND V3 — Notas de Crédito y Débito conforme SAR Acuerdo 481-2017
-- Fecha: 2026-05-14
-- Plan: PLAN_SAR_COMPLIANCE_2026-05-06.md §2.3-2.5, §3.1-3.2 (gaps SAR #3, #4, #5)
--
-- ADAPTACIÓN respecto al plan original (escrito 05-may):
--   El plan asumía la tabla adm_establecimiento, ELIMINADA el 09-may por la
--   decisión mono-sucursal. Las tablas NC/ND usan establecimiento_codigo
--   varchar(3) (igual que adm_cai_facturacion) y el snapshot del emisor se
--   resuelve desde cfg_company, no desde adm_establecimiento.
--
-- Contenido:
--   1. cfg_motivo_aumento  — catálogo de motivos para ND (nuevo)
--   2. adm_nota_credito + adm_nota_credito_detalle
--   3. adm_nota_debito  + adm_nota_debito_detalle
--   4. sp_adm_emitir_nota_credito
--   5. sp_adm_emitir_nota_debito
--
-- Prerequisitos ya en Azure: cfg_tipo_documento_fiscal, cfg_motivo_anulacion,
--   cfg_estado_documento_fiscal, adm_cai_facturacion (con tipo_documento_fiscal_id,
--   prefijo_documento, correlativo_actual), fn_adm_validar_cai_emitible.
--
-- Idempotente.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. cfg_motivo_aumento — catálogo de motivos para Nota de Débito
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cfg_motivo_aumento (
    motivo_aumento_id smallint PRIMARY KEY,
    codigo varchar(20) NOT NULL UNIQUE,
    descripcion varchar(150) NOT NULL,
    activo boolean NOT NULL DEFAULT true
);

INSERT INTO public.cfg_motivo_aumento (motivo_aumento_id, codigo, descripcion) VALUES
    (1, 'COBRO_EXTEMPORANEO', 'Cobro de servicio no facturado en su período'),
    (2, 'RECARGO_MORA',       'Recargo por mora sobre saldo vencido'),
    (3, 'AJUSTE_TARIFA',      'Ajuste por diferencia de tarifa a favor de la empresa'),
    (4, 'INTERES',            'Interés sobre convenio o saldo'),
    (5, 'OTRO',               'Otro motivo (debe detallarse en observaciones)')
ON CONFLICT (motivo_aumento_id) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 2.1 adm_nota_credito
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.adm_nota_credito (
    nota_credito_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    establecimiento_codigo varchar(3) NOT NULL DEFAULT '000',

    -- documento fiscal
    tipo_documento_fiscal_id smallint NOT NULL DEFAULT 6,  -- NC
    numero_documento varchar(80) NOT NULL,
    cai_id bigint NOT NULL,                  -- CAI específico tipo NC
    correlativo bigint NOT NULL,
    fecha_emision timestamptz NOT NULL DEFAULT now(),
    fecha_limite_cai date NOT NULL,
    leyenda_cai_rango varchar(200),

    -- emisor (snapshot de cfg_company al momento de emitir)
    rtn_emisor varchar(20) NOT NULL,
    razon_social_emisor varchar(200) NOT NULL,
    direccion_emisor varchar(300),

    -- receptor (cliente de la factura origen)
    cliente_id bigint NOT NULL,
    rtn_receptor varchar(20),
    razon_social_receptor varchar(200) NOT NULL,
    direccion_receptor varchar(300),

    -- referencia al documento original (OBLIGATORIO SAR)
    factura_origen_id integer NOT NULL,
    factura_origen_numero varchar(80) NOT NULL,
    factura_origen_fecha date NOT NULL,
    factura_origen_cai varchar(100),

    -- motivo
    motivo_anulacion_id smallint NOT NULL,
    motivo_detalle varchar(500),

    -- valores
    monto_disminuir numeric(18,4) NOT NULL,
    isv_disminuir numeric(18,4) NOT NULL DEFAULT 0,
    total_nota numeric(18,4) NOT NULL,
    anula_factura_origen boolean NOT NULL DEFAULT false,  -- true si la NC cubre el total

    -- estado (cfg_estado_documento_fiscal: 1=EMITIDA 2=APLICADA 3=ANULADA 4=PENDIENTE)
    estado_id smallint NOT NULL DEFAULT 1,

    -- auditoría
    usuario_emisor varchar(100) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),

    CONSTRAINT fk_adm_nota_credito_company
        FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_adm_nota_credito_cai
        FOREIGN KEY (company_id, cai_id) REFERENCES public.adm_cai_facturacion (company_id, cai_id),
    CONSTRAINT fk_adm_nota_credito_motivo
        FOREIGN KEY (motivo_anulacion_id) REFERENCES public.cfg_motivo_anulacion (motivo_anulacion_id),
    CONSTRAINT fk_adm_nota_credito_tipo_doc
        FOREIGN KEY (tipo_documento_fiscal_id) REFERENCES public.cfg_tipo_documento_fiscal (tipo_documento_fiscal_id),
    CONSTRAINT fk_adm_nota_credito_estado
        FOREIGN KEY (estado_id) REFERENCES public.cfg_estado_documento_fiscal (estado_id),
    CONSTRAINT fk_adm_nota_credito_factura_origen
        FOREIGN KEY (factura_origen_id) REFERENCES public.factura (id),
    CONSTRAINT fk_adm_nota_credito_cliente
        FOREIGN KEY (cliente_id) REFERENCES public.cliente_maestro (maestro_cliente_id),
    CONSTRAINT ck_adm_nota_credito_montos
        CHECK (monto_disminuir >= 0 AND total_nota >= 0 AND isv_disminuir >= 0),
    CONSTRAINT uq_adm_nota_credito_company_cai_correlativo
        UNIQUE (company_id, cai_id, correlativo)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_adm_nota_credito_company_numero
    ON public.adm_nota_credito (company_id, numero_documento);

CREATE INDEX IF NOT EXISTS ix_adm_nota_credito_factura_origen
    ON public.adm_nota_credito (company_id, factura_origen_id);

-- -----------------------------------------------------------------------------
-- 2.2 adm_nota_credito_detalle
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.adm_nota_credito_detalle (
    nota_credito_detalle_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota_credito_id bigint NOT NULL,
    servicio_id bigint,
    servicio_codigo varchar(50),
    descripcion varchar(300) NOT NULL,
    cantidad numeric(18,4) NOT NULL DEFAULT 1,
    monto_unitario numeric(18,4) NOT NULL,
    monto_total numeric(18,4) NOT NULL,
    isv_monto numeric(18,4) NOT NULL DEFAULT 0,
    cuenta_contable_codigo varchar(20),

    CONSTRAINT fk_adm_nc_detalle_nc
        FOREIGN KEY (nota_credito_id) REFERENCES public.adm_nota_credito (nota_credito_id) ON DELETE CASCADE,
    CONSTRAINT fk_adm_nc_detalle_servicio
        FOREIGN KEY (servicio_id) REFERENCES public.adm_servicio (servicio_id),
    CONSTRAINT ck_adm_nc_detalle_montos
        CHECK (cantidad > 0 AND monto_unitario >= 0 AND monto_total >= 0)
);

CREATE INDEX IF NOT EXISTS ix_adm_nc_detalle_nc
    ON public.adm_nota_credito_detalle (nota_credito_id);

-- -----------------------------------------------------------------------------
-- 2.3 adm_nota_debito  (estructura análoga: motivo_aumento + monto_aumentar)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.adm_nota_debito (
    nota_debito_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    establecimiento_codigo varchar(3) NOT NULL DEFAULT '000',

    tipo_documento_fiscal_id smallint NOT NULL DEFAULT 7,  -- ND
    numero_documento varchar(80) NOT NULL,
    cai_id bigint NOT NULL,
    correlativo bigint NOT NULL,
    fecha_emision timestamptz NOT NULL DEFAULT now(),
    fecha_limite_cai date NOT NULL,
    leyenda_cai_rango varchar(200),

    rtn_emisor varchar(20) NOT NULL,
    razon_social_emisor varchar(200) NOT NULL,
    direccion_emisor varchar(300),

    cliente_id bigint NOT NULL,
    rtn_receptor varchar(20),
    razon_social_receptor varchar(200) NOT NULL,
    direccion_receptor varchar(300),

    factura_origen_id integer NOT NULL,
    factura_origen_numero varchar(80) NOT NULL,
    factura_origen_fecha date NOT NULL,
    factura_origen_cai varchar(100),

    motivo_aumento_id smallint NOT NULL,
    motivo_detalle varchar(500),

    monto_aumentar numeric(18,4) NOT NULL,
    isv_aumentar numeric(18,4) NOT NULL DEFAULT 0,
    total_nota numeric(18,4) NOT NULL,

    estado_id smallint NOT NULL DEFAULT 1,

    usuario_emisor varchar(100) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL DEFAULT current_user,
    updated_at timestamptz,
    updated_by varchar(100),

    CONSTRAINT fk_adm_nota_debito_company
        FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_adm_nota_debito_cai
        FOREIGN KEY (company_id, cai_id) REFERENCES public.adm_cai_facturacion (company_id, cai_id),
    CONSTRAINT fk_adm_nota_debito_motivo
        FOREIGN KEY (motivo_aumento_id) REFERENCES public.cfg_motivo_aumento (motivo_aumento_id),
    CONSTRAINT fk_adm_nota_debito_tipo_doc
        FOREIGN KEY (tipo_documento_fiscal_id) REFERENCES public.cfg_tipo_documento_fiscal (tipo_documento_fiscal_id),
    CONSTRAINT fk_adm_nota_debito_estado
        FOREIGN KEY (estado_id) REFERENCES public.cfg_estado_documento_fiscal (estado_id),
    CONSTRAINT fk_adm_nota_debito_factura_origen
        FOREIGN KEY (factura_origen_id) REFERENCES public.factura (id),
    CONSTRAINT fk_adm_nota_debito_cliente
        FOREIGN KEY (cliente_id) REFERENCES public.cliente_maestro (maestro_cliente_id),
    CONSTRAINT ck_adm_nota_debito_montos
        CHECK (monto_aumentar >= 0 AND total_nota >= 0 AND isv_aumentar >= 0),
    CONSTRAINT uq_adm_nota_debito_company_cai_correlativo
        UNIQUE (company_id, cai_id, correlativo)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_adm_nota_debito_company_numero
    ON public.adm_nota_debito (company_id, numero_documento);

CREATE INDEX IF NOT EXISTS ix_adm_nota_debito_factura_origen
    ON public.adm_nota_debito (company_id, factura_origen_id);

-- -----------------------------------------------------------------------------
-- 2.4 adm_nota_debito_detalle
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.adm_nota_debito_detalle (
    nota_debito_detalle_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota_debito_id bigint NOT NULL,
    servicio_id bigint,
    servicio_codigo varchar(50),
    descripcion varchar(300) NOT NULL,
    cantidad numeric(18,4) NOT NULL DEFAULT 1,
    monto_unitario numeric(18,4) NOT NULL,
    monto_total numeric(18,4) NOT NULL,
    isv_monto numeric(18,4) NOT NULL DEFAULT 0,
    cuenta_contable_codigo varchar(20),

    CONSTRAINT fk_adm_nd_detalle_nd
        FOREIGN KEY (nota_debito_id) REFERENCES public.adm_nota_debito (nota_debito_id) ON DELETE CASCADE,
    CONSTRAINT fk_adm_nd_detalle_servicio
        FOREIGN KEY (servicio_id) REFERENCES public.adm_servicio (servicio_id),
    CONSTRAINT ck_adm_nd_detalle_montos
        CHECK (cantidad > 0 AND monto_unitario >= 0 AND monto_total >= 0)
);

CREATE INDEX IF NOT EXISTS ix_adm_nd_detalle_nd
    ON public.adm_nota_debito_detalle (nota_debito_id);

-- =============================================================================
-- 3. SP sp_adm_emitir_nota_credito
-- =============================================================================
DROP FUNCTION IF EXISTS public.sp_adm_emitir_nota_credito(bigint, integer, smallint, varchar, numeric, jsonb, varchar, bigint);

CREATE OR REPLACE FUNCTION public.sp_adm_emitir_nota_credito(
    p_company_id bigint,
    p_factura_origen_id integer,
    p_motivo_anulacion_id smallint,
    p_motivo_detalle varchar,
    p_monto_disminuir numeric,          -- NULL = total de la factura origen
    p_lineas jsonb,                     -- NULL = copia las líneas de la factura origen
    p_usuario_emisor varchar,
    p_cai_id bigint                     -- CAI específico tipo NC
)
RETURNS TABLE (
    success boolean,
    codigo text,
    mensaje text,
    nota_credito_id bigint,
    numero_documento text,
    correlativo bigint
)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_factura record;
    v_cai record;
    v_company record;
    v_correlativo bigint;
    v_numero text;
    v_nota_id bigint;
    v_total numeric(18,4);
    v_monto numeric(18,4);
    v_anula boolean;
    v_linea record;
    v_saldo_anterior numeric(18,4) := 0;
BEGIN
    -- 1. Validar factura origen
    SELECT f.id, f.numfactura, f.fechaemision, f.clientecodigo, f.saldototal,
           f.estado, f.company_id
    INTO v_factura
    FROM public.factura f
    WHERE f.id = p_factura_origen_id
      AND f.company_id = p_company_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'FACTURA_NO_EXISTE: factura origen % no existe para company %.',
            p_factura_origen_id, p_company_id;
    END IF;

    IF COALESCE(v_factura.estado, '') = 'N' THEN
        RAISE EXCEPTION 'FACTURA_YA_ANULADA: la factura origen % ya está anulada.', v_factura.numfactura;
    END IF;

    -- 2. Validar CAI emitible y que sea tipo NC (6)
    IF NOT public.fn_adm_validar_cai_emitible(p_company_id, p_cai_id) THEN
        RAISE EXCEPTION 'CAI_NO_EMITIBLE: el CAI % no está vigente o pasó su fecha límite de emisión.', p_cai_id;
    END IF;

    SELECT c.cai_id, c.prefijo_documento, c.correlativo_actual, c.rango_hasta,
           c.fecha_limite_emision, c.leyenda_rango, c.tipo_documento_fiscal_id,
           c.establecimiento_codigo
    INTO v_cai
    FROM public.adm_cai_facturacion c
    WHERE c.company_id = p_company_id AND c.cai_id = p_cai_id;

    IF v_cai.tipo_documento_fiscal_id <> 6 THEN
        RAISE EXCEPTION 'CAI_TIPO_INCORRECTO: el CAI % es tipo %, se requiere tipo 6 (Nota de Crédito).',
            p_cai_id, v_cai.tipo_documento_fiscal_id;
    END IF;

    -- 3. Tomar correlativo siguiente
    v_correlativo := v_cai.correlativo_actual + 1;
    IF v_correlativo > v_cai.rango_hasta THEN
        RAISE EXCEPTION 'CAI_AGOTADO: el CAI % alcanzó su rango máximo (%).', p_cai_id, v_cai.rango_hasta;
    END IF;

    v_numero := concat(COALESCE(v_cai.prefijo_documento, ''), lpad(v_correlativo::text, 8, '0'));

    -- 4. Snapshot emisor desde cfg_company
    SELECT co.tax_id, co.legal_name, co.commercial_name, co.address
    INTO v_company
    FROM public.cfg_company co
    WHERE co.company_id = p_company_id;

    -- 5. Monto a disminuir (default = saldo total de la factura)
    v_total := COALESCE(v_factura.saldototal, 0)::numeric(18,4);
    v_monto := COALESCE(p_monto_disminuir, v_total)::numeric(18,4);
    IF v_monto <= 0 THEN
        RAISE EXCEPTION 'MONTO_INVALIDO: el monto a disminuir debe ser mayor a 0.';
    END IF;
    IF v_monto > v_total THEN
        RAISE EXCEPTION 'MONTO_EXCEDE_FACTURA: monto a disminuir % supera el saldo de la factura %.',
            v_monto, v_total;
    END IF;
    v_anula := (v_monto >= v_total);

    -- 6. INSERT cabecera
    INSERT INTO public.adm_nota_credito (
        company_id, establecimiento_codigo,
        tipo_documento_fiscal_id, numero_documento, cai_id, correlativo,
        fecha_limite_cai, leyenda_cai_rango,
        rtn_emisor, razon_social_emisor, direccion_emisor,
        cliente_id, rtn_receptor, razon_social_receptor, direccion_receptor,
        factura_origen_id, factura_origen_numero, factura_origen_fecha, factura_origen_cai,
        motivo_anulacion_id, motivo_detalle,
        monto_disminuir, isv_disminuir, total_nota, anula_factura_origen,
        estado_id, usuario_emisor, created_by
    )
    SELECT
        p_company_id, COALESCE(v_cai.establecimiento_codigo, '000'),
        6, v_numero, p_cai_id, v_correlativo,
        v_cai.fecha_limite_emision, v_cai.leyenda_rango,
        COALESCE(v_company.tax_id, ''), COALESCE(v_company.legal_name, v_company.commercial_name, ''), v_company.address,
        cm.maestro_cliente_id, cm.maestro_cliente_rtn,
        cm.maestro_cliente_nombre, NULL,
        v_factura.id, v_factura.numfactura, v_factura.fechaemision, v_factura.numfactura,
        p_motivo_anulacion_id, p_motivo_detalle,
        v_monto, 0, v_monto, v_anula,
        1, p_usuario_emisor, p_usuario_emisor
    FROM public.cliente_maestro cm
    WHERE cm.maestro_cliente_clave = v_factura.clientecodigo
      AND cm.company_id = p_company_id
    LIMIT 1
    RETURNING adm_nota_credito.nota_credito_id INTO v_nota_id;

    IF v_nota_id IS NULL THEN
        RAISE EXCEPTION 'CLIENTE_NO_EXISTE: no se encontró cliente % para la factura origen.',
            v_factura.clientecodigo;
    END IF;

    -- 7. INSERT detalle: desde p_lineas o copiando de factura_detalle de la factura origen
    IF p_lineas IS NOT NULL THEN
        FOR v_linea IN
            SELECT *
            FROM jsonb_to_recordset(p_lineas) AS l(
                servicio_id bigint,
                servicio_codigo text,
                descripcion text,
                cantidad numeric,
                monto_unitario numeric,
                monto_total numeric,
                isv_monto numeric,
                cuenta_contable_codigo text
            )
        LOOP
            INSERT INTO public.adm_nota_credito_detalle (
                nota_credito_id, servicio_id, servicio_codigo, descripcion,
                cantidad, monto_unitario, monto_total, isv_monto, cuenta_contable_codigo
            )
            VALUES (
                v_nota_id, v_linea.servicio_id, v_linea.servicio_codigo,
                COALESCE(v_linea.descripcion, v_linea.servicio_codigo, ''),
                COALESCE(v_linea.cantidad, 1), COALESCE(v_linea.monto_unitario, 0),
                COALESCE(v_linea.monto_total, 0), COALESCE(v_linea.isv_monto, 0),
                v_linea.cuenta_contable_codigo
            );
        END LOOP;
    ELSE
        INSERT INTO public.adm_nota_credito_detalle (
            nota_credito_id, servicio_id, servicio_codigo, descripcion,
            cantidad, monto_unitario, monto_total, isv_monto
        )
        SELECT
            v_nota_id,
            s.servicio_id,
            fd.tiposervicio,
            COALESCE(fd.descripcion, fd.tiposervicio, ''),
            1,
            COALESCE(fd.montovalor, 0),
            COALESCE(fd.montovalor, 0),
            0
        FROM public.factura_detalle fd
        LEFT JOIN public.adm_servicio s
          ON s.company_id = p_company_id
         AND s.codigo = fd.tiposervicio
        WHERE fd.factura_id = v_factura.id
          AND COALESCE(fd.montovalor, 0) <> 0;
    END IF;

    -- 8. Avanzar correlativo del CAI
    UPDATE public.adm_cai_facturacion
    SET correlativo_actual = v_correlativo,
        updated_at = now(),
        updated_by = p_usuario_emisor
    WHERE company_id = p_company_id AND cai_id = p_cai_id;

    -- 9. Marcar la factura origen como anulada SOLO si la NC cubre el total
    IF v_anula THEN
        UPDATE public.factura
        SET estado = 'N',
            estado_id = 3,  -- ANULADA
            motivo_anulacion_id = p_motivo_anulacion_id,
            updated_at = now()
        WHERE id = v_factura.id;
    END IF;

    -- 9b. Reflejar la NC en el estado de cuenta del cliente (transaccion_abonado).
    -- Una NC DISMINUYE el saldo del cliente → creditos = monto, saldo_detalle negativo.
    SELECT COALESCE(ta.saldo, 0)
    INTO v_saldo_anterior
    FROM public.transaccion_abonado ta
    WHERE ta.company_id = p_company_id
      AND ta.cliente_clave = v_factura.clientecodigo
      AND ta.estado = 'A'
    ORDER BY ta.ide DESC
    LIMIT 1;

    INSERT INTO public.transaccion_abonado (
        company_id, cliente_clave, tipotransaccion, docufuente,
        fecha_docu, tipo_partida, descripcion,
        debitos, creditos, saldo,
        estado, estado_id, fecha_registro, usuario, saldo_detalle
    )
    VALUES (
        p_company_id, v_factura.clientecodigo, '205', v_nota_id,
        current_date, '01',
        concat('N/C ', v_numero, ' s/factura ', v_factura.numfactura),
        0, v_monto, COALESCE(v_saldo_anterior, 0) - v_monto,
        'A', 1, current_date, p_usuario_emisor, -v_monto
    );

    -- 10. Resultado
    RETURN QUERY SELECT
        true,
        'OK'::text,
        CASE WHEN v_anula
             THEN 'Nota de crédito emitida y factura origen anulada.'
             ELSE 'Nota de crédito parcial emitida (factura origen sigue activa).'
        END::text,
        v_nota_id,
        v_numero,
        v_correlativo;
END;
$function$;

-- =============================================================================
-- 4. SP sp_adm_emitir_nota_debito
-- =============================================================================
DROP FUNCTION IF EXISTS public.sp_adm_emitir_nota_debito(bigint, integer, smallint, varchar, numeric, jsonb, varchar, bigint);

CREATE OR REPLACE FUNCTION public.sp_adm_emitir_nota_debito(
    p_company_id bigint,
    p_factura_origen_id integer,
    p_motivo_aumento_id smallint,
    p_motivo_detalle varchar,
    p_monto_aumentar numeric,            -- requerido (un ND siempre indica cuánto aumenta)
    p_lineas jsonb,                      -- NULL = una sola línea con el motivo
    p_usuario_emisor varchar,
    p_cai_id bigint                      -- CAI específico tipo ND
)
RETURNS TABLE (
    success boolean,
    codigo text,
    mensaje text,
    nota_debito_id bigint,
    numero_documento text,
    correlativo bigint
)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_factura record;
    v_cai record;
    v_company record;
    v_correlativo bigint;
    v_numero text;
    v_nota_id bigint;
    v_monto numeric(18,4);
    v_linea record;
    v_motivo_desc text;
    v_saldo_anterior numeric(18,4) := 0;
BEGIN
    -- 1. Validar factura origen
    SELECT f.id, f.numfactura, f.fechaemision, f.clientecodigo, f.saldototal,
           f.estado, f.company_id
    INTO v_factura
    FROM public.factura f
    WHERE f.id = p_factura_origen_id
      AND f.company_id = p_company_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'FACTURA_NO_EXISTE: factura origen % no existe para company %.',
            p_factura_origen_id, p_company_id;
    END IF;

    IF COALESCE(v_factura.estado, '') = 'N' THEN
        RAISE EXCEPTION 'FACTURA_ANULADA: no se puede emitir ND sobre la factura anulada %.', v_factura.numfactura;
    END IF;

    -- 2. Validar CAI emitible y tipo ND (7)
    IF NOT public.fn_adm_validar_cai_emitible(p_company_id, p_cai_id) THEN
        RAISE EXCEPTION 'CAI_NO_EMITIBLE: el CAI % no está vigente o pasó su fecha límite de emisión.', p_cai_id;
    END IF;

    SELECT c.cai_id, c.prefijo_documento, c.correlativo_actual, c.rango_hasta,
           c.fecha_limite_emision, c.leyenda_rango, c.tipo_documento_fiscal_id,
           c.establecimiento_codigo
    INTO v_cai
    FROM public.adm_cai_facturacion c
    WHERE c.company_id = p_company_id AND c.cai_id = p_cai_id;

    IF v_cai.tipo_documento_fiscal_id <> 7 THEN
        RAISE EXCEPTION 'CAI_TIPO_INCORRECTO: el CAI % es tipo %, se requiere tipo 7 (Nota de Débito).',
            p_cai_id, v_cai.tipo_documento_fiscal_id;
    END IF;

    -- 3. Correlativo
    v_correlativo := v_cai.correlativo_actual + 1;
    IF v_correlativo > v_cai.rango_hasta THEN
        RAISE EXCEPTION 'CAI_AGOTADO: el CAI % alcanzó su rango máximo (%).', p_cai_id, v_cai.rango_hasta;
    END IF;
    v_numero := concat(COALESCE(v_cai.prefijo_documento, ''), lpad(v_correlativo::text, 8, '0'));

    -- 4. Snapshot emisor
    SELECT co.tax_id, co.legal_name, co.commercial_name, co.address
    INTO v_company
    FROM public.cfg_company co
    WHERE co.company_id = p_company_id;

    -- 5. Monto a aumentar (requerido)
    v_monto := COALESCE(p_monto_aumentar, 0)::numeric(18,4);
    IF v_monto <= 0 THEN
        RAISE EXCEPTION 'MONTO_INVALIDO: el monto a aumentar debe ser mayor a 0.';
    END IF;

    SELECT ma.descripcion INTO v_motivo_desc
    FROM public.cfg_motivo_aumento ma
    WHERE ma.motivo_aumento_id = p_motivo_aumento_id;

    -- 6. INSERT cabecera
    INSERT INTO public.adm_nota_debito (
        company_id, establecimiento_codigo,
        tipo_documento_fiscal_id, numero_documento, cai_id, correlativo,
        fecha_limite_cai, leyenda_cai_rango,
        rtn_emisor, razon_social_emisor, direccion_emisor,
        cliente_id, rtn_receptor, razon_social_receptor, direccion_receptor,
        factura_origen_id, factura_origen_numero, factura_origen_fecha, factura_origen_cai,
        motivo_aumento_id, motivo_detalle,
        monto_aumentar, isv_aumentar, total_nota,
        estado_id, usuario_emisor, created_by
    )
    SELECT
        p_company_id, COALESCE(v_cai.establecimiento_codigo, '000'),
        7, v_numero, p_cai_id, v_correlativo,
        v_cai.fecha_limite_emision, v_cai.leyenda_rango,
        COALESCE(v_company.tax_id, ''), COALESCE(v_company.legal_name, v_company.commercial_name, ''), v_company.address,
        cm.maestro_cliente_id, cm.maestro_cliente_rtn,
        cm.maestro_cliente_nombre, NULL,
        v_factura.id, v_factura.numfactura, v_factura.fechaemision, v_factura.numfactura,
        p_motivo_aumento_id, p_motivo_detalle,
        v_monto, 0, v_monto,
        1, p_usuario_emisor, p_usuario_emisor
    FROM public.cliente_maestro cm
    WHERE cm.maestro_cliente_clave = v_factura.clientecodigo
      AND cm.company_id = p_company_id
    LIMIT 1
    RETURNING adm_nota_debito.nota_debito_id INTO v_nota_id;

    IF v_nota_id IS NULL THEN
        RAISE EXCEPTION 'CLIENTE_NO_EXISTE: no se encontró cliente % para la factura origen.',
            v_factura.clientecodigo;
    END IF;

    -- 7. Detalle
    IF p_lineas IS NOT NULL THEN
        FOR v_linea IN
            SELECT *
            FROM jsonb_to_recordset(p_lineas) AS l(
                servicio_id bigint,
                servicio_codigo text,
                descripcion text,
                cantidad numeric,
                monto_unitario numeric,
                monto_total numeric,
                isv_monto numeric,
                cuenta_contable_codigo text
            )
        LOOP
            INSERT INTO public.adm_nota_debito_detalle (
                nota_debito_id, servicio_id, servicio_codigo, descripcion,
                cantidad, monto_unitario, monto_total, isv_monto, cuenta_contable_codigo
            )
            VALUES (
                v_nota_id, v_linea.servicio_id, v_linea.servicio_codigo,
                COALESCE(v_linea.descripcion, v_linea.servicio_codigo, ''),
                COALESCE(v_linea.cantidad, 1), COALESCE(v_linea.monto_unitario, 0),
                COALESCE(v_linea.monto_total, 0), COALESCE(v_linea.isv_monto, 0),
                v_linea.cuenta_contable_codigo
            );
        END LOOP;
    ELSE
        -- Una sola línea con el motivo del aumento
        INSERT INTO public.adm_nota_debito_detalle (
            nota_debito_id, servicio_id, servicio_codigo, descripcion,
            cantidad, monto_unitario, monto_total, isv_monto
        )
        VALUES (
            v_nota_id, NULL, NULL,
            COALESCE(v_motivo_desc, 'Ajuste por nota de débito'),
            1, v_monto, v_monto, 0
        );
    END IF;

    -- 8. Avanzar correlativo
    UPDATE public.adm_cai_facturacion
    SET correlativo_actual = v_correlativo,
        updated_at = now(),
        updated_by = p_usuario_emisor
    WHERE company_id = p_company_id AND cai_id = p_cai_id;

    -- 8b. Reflejar la ND en el estado de cuenta del cliente (transaccion_abonado).
    -- Una ND AUMENTA el saldo del cliente → debitos = monto, saldo_detalle positivo.
    SELECT COALESCE(ta.saldo, 0)
    INTO v_saldo_anterior
    FROM public.transaccion_abonado ta
    WHERE ta.company_id = p_company_id
      AND ta.cliente_clave = v_factura.clientecodigo
      AND ta.estado = 'A'
    ORDER BY ta.ide DESC
    LIMIT 1;

    INSERT INTO public.transaccion_abonado (
        company_id, cliente_clave, tipotransaccion, docufuente,
        fecha_docu, tipo_partida, descripcion,
        debitos, creditos, saldo,
        estado, estado_id, fecha_registro, usuario, saldo_detalle
    )
    VALUES (
        p_company_id, v_factura.clientecodigo, '206', v_nota_id,
        current_date, '01',
        concat('N/D ', v_numero, ' s/factura ', v_factura.numfactura),
        v_monto, 0, COALESCE(v_saldo_anterior, 0) + v_monto,
        'A', 1, current_date, p_usuario_emisor, v_monto
    );

    -- 9. Resultado (un ND NO anula la factura origen, solo aumenta el saldo del cliente)
    RETURN QUERY SELECT
        true,
        'OK'::text,
        'Nota de débito emitida correctamente.'::text,
        v_nota_id,
        v_numero,
        v_correlativo;
END;
$function$;

COMMENT ON TABLE public.adm_nota_credito IS
'Notas de Crédito V3 (SAR Acuerdo 481-2017). Disminuyen el saldo del cliente / anulan factura. Modelo mono-sucursal: usa establecimiento_codigo varchar(3), emisor snapshot desde cfg_company.';
COMMENT ON TABLE public.adm_nota_debito IS
'Notas de Débito V3 (SAR Acuerdo 481-2017). Aumentan el saldo del cliente (cobro extemporáneo, mora, ajuste). No anulan la factura origen.';
