-- ============================================================================
-- 20260704_ci_fase7_periodo_cierre.sql
-- Fase 7 del plan de integración contable-comercial (2026-07-02):
-- períodos comercial y contable + cierres de mes con avisos.
--
-- Idempotente. NO ejecutar en producción fuera de la ventana de deploy.
--
-- Contenido:
--   1. adm_periodo_comercial + adm_periodo_comercial_ciclo (multitenant,
--      estados numéricos) — reemplazan a historialmes como fuente de verdad
--      del mes comercial (decisión D6).
--   2. fn_adm_periodo_comercial_actual / fn_adm_periodo_comercial_ciclo_abierto.
--   3. Espejo → historialmes (triggers). OBLIGATORIO durante la transición:
--      el WS de lectores (APCService.svc.cs GetCiclo, queryV3) lee historialmes
--      con SQL inline (cerrarperiodo='P' AND cerrado='A') y NO se toca (D9).
--      Retiro del espejo: solo tras ≥1 mes estable post-F7 y repunte del WS.
--   4. Migración de datos historialmes → modelo nuevo (por empresa con
--      actividad comercial en historicomedicion).
--   5. Repunte de sp_adm_calcular_factura_lectura (corazón tarifario):
--      ÚNICO cambio = la validación de período abierto deja de leer
--      historialmes y usa fn_adm_periodo_comercial_ciclo_abierto.
--      ⚠ Cambio de comportamiento DOCUMENTADO: el SP legacy consideraba
--      abierto cualquier período EXISTENTE (su lista de letras de cierre
--      'S','SI','1','Y','TRUE','T' no incluía la convención real 'C', por lo
--      que un período cerrado con cerrado='C' seguía facturando). F7
--      introduce el bloqueo real por cierre — es el objetivo de la fase (D7).
--   6. Repunte de sp_informacion_ciclo (SP GetCiclo legacy del WS — solo SQL,
--      la app Android y el WS no cambian).
--   7. Cierre comercial: rutas pendientes por ciclo (validadas contra
--      facturas emitidas, NO contra historicomedicion), cierre de ciclo,
--      checklist y cierre de mes, apertura habilitada por el cierre anterior.
--   8. con_integracion_config.desfase_max_meses (aviso de desfase D6).
--   9. Cierre contable: checklist (facturas con partida, sin borradores,
--      caja posteada, cola de pendientes vacía, verificación de saldos F6)
--      → precierre → cierre → crea el período siguiente.
--  10. fn_adm_avisos_periodos: avisos para el banner del portal.
--
-- Estados numéricos (regla del repo: nada de estados en letras):
--   adm_periodo_comercial.status_id / adm_periodo_comercial_ciclo.status_id:
--     1 = ABIERTO, 2 = CERRADO
--   (con_periodo_contable mantiene su convención existente 0/1/2.)
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. Tablas de período comercial
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.adm_periodo_comercial (
    periodo_comercial_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           bigint NOT NULL,
    anio                 integer NOT NULL,
    mes                  smallint NOT NULL,
    status_id            smallint NOT NULL DEFAULT 1,
    fecha_apertura       timestamptz NOT NULL DEFAULT now(),
    abierto_por          varchar(100) NOT NULL DEFAULT current_user,
    fecha_cierre         timestamptz,
    cerrado_por          varchar(100),
    created_at           timestamptz NOT NULL DEFAULT now(),
    created_by           varchar(100) NOT NULL DEFAULT current_user,
    updated_at           timestamptz,
    updated_by           varchar(100),
    CONSTRAINT ck_adm_periodo_comercial_status CHECK (status_id IN (1, 2)),
    CONSTRAINT ck_adm_periodo_comercial_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_adm_periodo_comercial_anio CHECK (anio BETWEEN 2000 AND 2100),
    CONSTRAINT uq_adm_periodo_comercial_mes UNIQUE (company_id, anio, mes),
    -- AK para FKs compuestas tenant-safe (patrón F3)
    CONSTRAINT uq_adm_periodo_comercial_company_id UNIQUE (company_id, periodo_comercial_id)
);

CREATE INDEX IF NOT EXISTS ix_adm_periodo_comercial_abierto
    ON public.adm_periodo_comercial (company_id, anio DESC, mes DESC)
    WHERE status_id = 1;

CREATE TABLE IF NOT EXISTS public.adm_periodo_comercial_ciclo (
    periodo_ciclo_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           bigint NOT NULL,
    periodo_comercial_id bigint NOT NULL,
    ciclo_codigo         varchar(2) NOT NULL,
    status_id            smallint NOT NULL DEFAULT 1,
    fecha_apertura       timestamptz NOT NULL DEFAULT now(),
    abierto_por          varchar(100) NOT NULL DEFAULT current_user,
    -- fecha planificada de cierre (espejo de historialmes.fechacierre al abrir)
    fecha_limite         date,
    fecha_cierre         timestamptz,
    cerrado_por          varchar(100),
    created_at           timestamptz NOT NULL DEFAULT now(),
    created_by           varchar(100) NOT NULL DEFAULT current_user,
    updated_at           timestamptz,
    updated_by           varchar(100),
    CONSTRAINT ck_adm_periodo_comercial_ciclo_status CHECK (status_id IN (1, 2)),
    CONSTRAINT uq_adm_periodo_comercial_ciclo UNIQUE (company_id, periodo_comercial_id, ciclo_codigo),
    CONSTRAINT fk_adm_periodo_comercial_ciclo_periodo
        FOREIGN KEY (company_id, periodo_comercial_id)
        REFERENCES public.adm_periodo_comercial (company_id, periodo_comercial_id)
);

CREATE INDEX IF NOT EXISTS ix_adm_periodo_comercial_ciclo_codigo
    ON public.adm_periodo_comercial_ciclo (company_id, ciclo_codigo)
    WHERE status_id = 1;

-- ----------------------------------------------------------------------------
-- 2. Funciones de consulta del período comercial
-- ----------------------------------------------------------------------------

-- Período comercial "actual": el abierto más reciente de la empresa.
-- Equivale al legacy "historialmes con cerrarperiodo='P' ORDER BY ano, mes DESC".
CREATE OR REPLACE FUNCTION public.fn_adm_periodo_comercial_actual(
    p_company_id bigint
) RETURNS TABLE(
    periodo_comercial_id bigint,
    anio integer,
    mes smallint,
    fecha_apertura timestamptz
)
LANGUAGE sql
STABLE
AS $function$
    SELECT p.periodo_comercial_id, p.anio, p.mes, p.fecha_apertura
    FROM public.adm_periodo_comercial p
    WHERE p.company_id = p_company_id
      AND p.status_id = 1
    ORDER BY p.anio DESC, p.mes DESC
    LIMIT 1;
$function$;

-- ¿Está abierto el ciclo del período (empresa, año, mes, ciclo)?
-- Normaliza el código de ciclo igual que el legacy ('1' ≡ '01').
CREATE OR REPLACE FUNCTION public.fn_adm_periodo_comercial_ciclo_abierto(
    p_company_id bigint,
    p_anio integer,
    p_mes integer,
    p_ciclo character varying
) RETURNS boolean
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_raw text := btrim(coalesce(p_ciclo, ''));
    v_norm text;
BEGIN
    IF v_raw = '' THEN
        RETURN false;
    END IF;

    v_norm := CASE WHEN v_raw ~ '^[0-9]+$' THEN lpad(v_raw, 2, '0') ELSE v_raw END;

    RETURN EXISTS (
        SELECT 1
        FROM public.adm_periodo_comercial p
        JOIN public.adm_periodo_comercial_ciclo pc
          ON pc.company_id = p.company_id
         AND pc.periodo_comercial_id = p.periodo_comercial_id
        WHERE p.company_id = p_company_id
          AND p.anio = p_anio
          AND p.mes = p_mes
          AND p.status_id = 1
          AND pc.status_id = 1
          AND (pc.ciclo_codigo = v_norm OR pc.ciclo_codigo = v_raw)
    );
END;
$function$;

-- ----------------------------------------------------------------------------
-- 3. Espejo → historialmes (transición)
--    historialmes NO se dropea (regla: retiro físico solo tras ≥1 mes estable
--    post-F7). El WS de lectores la lee inline; el espejo la mantiene viva.
--    Nota multitenant: historialmes no tiene company_id; si dos empresas
--    llegaran a compartir (ano, mes, ciclo) el espejo escribe último-gana.
--    La tabla legacy siempre fue mono-empresa; se acepta durante la transición.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_adm_periodo_ciclo_espejo_sync(
    p_periodo_ciclo_id bigint
) RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    v_row record;
    v_abierto boolean;
BEGIN
    SELECT pc.ciclo_codigo,
           pc.status_id AS ciclo_status,
           pc.fecha_apertura,
           pc.abierto_por,
           pc.fecha_limite,
           pc.fecha_cierre,
           pc.cerrado_por,
           p.anio,
           p.mes,
           p.status_id AS periodo_status
    INTO v_row
    FROM public.adm_periodo_comercial_ciclo pc
    JOIN public.adm_periodo_comercial p
      ON p.company_id = pc.company_id
     AND p.periodo_comercial_id = pc.periodo_comercial_id
    WHERE pc.periodo_ciclo_id = p_periodo_ciclo_id;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    v_abierto := (v_row.periodo_status = 1 AND v_row.ciclo_status = 1);

    INSERT INTO public.historialmes
        (ano, mes, ciclo, fecha, fechaperiodo, usuarioapertura,
         cerrado, cerrarperiodo, fechacierre, usuariocierre)
    VALUES
        (v_row.anio, v_row.mes, v_row.ciclo_codigo,
         (v_row.fecha_apertura AT TIME ZONE 'UTC'),
         (v_row.fecha_apertura AT TIME ZONE 'UTC'),
         left(v_row.abierto_por, 150),
         CASE WHEN v_abierto THEN 'A' ELSE 'C' END,
         CASE WHEN v_abierto THEN 'P' ELSE 'C' END,
         COALESCE((v_row.fecha_cierre AT TIME ZONE 'UTC')::date, v_row.fecha_limite),
         left(v_row.cerrado_por, 20))
    ON CONFLICT (ano, mes, ciclo) DO UPDATE SET
        fecha         = EXCLUDED.fecha,
        fechaperiodo  = EXCLUDED.fechaperiodo,
        usuarioapertura = EXCLUDED.usuarioapertura,
        cerrado       = EXCLUDED.cerrado,
        cerrarperiodo = EXCLUDED.cerrarperiodo,
        fechacierre   = EXCLUDED.fechacierre,
        usuariocierre = EXCLUDED.usuariocierre;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_adm_periodo_ciclo_espejo_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM public.historialmes hm
        WHERE hm.ano = (SELECT p.anio FROM public.adm_periodo_comercial p
                        WHERE p.periodo_comercial_id = OLD.periodo_comercial_id)
          AND hm.mes = (SELECT p.mes FROM public.adm_periodo_comercial p
                        WHERE p.periodo_comercial_id = OLD.periodo_comercial_id)
          AND hm.ciclo = OLD.ciclo_codigo;
        RETURN OLD;
    END IF;

    PERFORM public.fn_adm_periodo_ciclo_espejo_sync(NEW.periodo_ciclo_id);
    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_adm_periodo_comercial_ciclo_espejo ON public.adm_periodo_comercial_ciclo;
CREATE TRIGGER trg_adm_periodo_comercial_ciclo_espejo
    AFTER INSERT OR UPDATE OR DELETE ON public.adm_periodo_comercial_ciclo
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_adm_periodo_ciclo_espejo_trigger();

-- Cambios de estado a nivel período re-sincronizan el espejo de sus ciclos
CREATE OR REPLACE FUNCTION public.fn_adm_periodo_comercial_espejo_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    v_ciclo record;
BEGIN
    IF NEW.status_id IS DISTINCT FROM OLD.status_id THEN
        FOR v_ciclo IN
            SELECT pc.periodo_ciclo_id
            FROM public.adm_periodo_comercial_ciclo pc
            WHERE pc.company_id = NEW.company_id
              AND pc.periodo_comercial_id = NEW.periodo_comercial_id
        LOOP
            PERFORM public.fn_adm_periodo_ciclo_espejo_sync(v_ciclo.periodo_ciclo_id);
        END LOOP;
    END IF;
    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_adm_periodo_comercial_espejo ON public.adm_periodo_comercial;
CREATE TRIGGER trg_adm_periodo_comercial_espejo
    AFTER UPDATE ON public.adm_periodo_comercial
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_adm_periodo_comercial_espejo_trigger();

-- ----------------------------------------------------------------------------
-- 4. Migración de datos historialmes → modelo nuevo
--    Por cada empresa con actividad comercial (historicomedicion). historialmes
--    es mono-empresa; sus períodos se replican en cada empresa con lecturas.
--    Idempotente vía ON CONFLICT DO NOTHING (no pisa cierres posteriores).
--    Semántica de "abierto": cerrarperiodo='P' (la convención que usan los
--    consumidores C# y el WS; en datos reales cerrado y cerrarperiodo son
--    consistentes A↔P, C↔C).
-- ----------------------------------------------------------------------------

DO $$
DECLARE
    v_company bigint;
    v_periodos integer := 0;
    v_ciclos integer := 0;
    n integer;
BEGIN
    FOR v_company IN
        SELECT DISTINCT hm2.company_id
        FROM public.historicomedicion hm2
        WHERE hm2.company_id IS NOT NULL
    LOOP
        INSERT INTO public.adm_periodo_comercial
            (company_id, anio, mes, status_id, fecha_apertura, abierto_por,
             fecha_cierre, cerrado_por, created_by)
        SELECT v_company,
               hm.ano::int,
               hm.mes::smallint,
               CASE WHEN bool_or(COALESCE(hm.cerrarperiodo, 'P') = 'P') THEN 1 ELSE 2 END,
               COALESCE(min(hm.fecha) AT TIME ZONE 'UTC', now()),
               COALESCE(left(btrim(max(hm.usuarioapertura)), 100), 'migracion-f7'),
               CASE WHEN bool_or(COALESCE(hm.cerrarperiodo, 'P') = 'P') THEN NULL
                    ELSE (max(hm.fechacierre)::timestamp AT TIME ZONE 'UTC') END,
               CASE WHEN bool_or(COALESCE(hm.cerrarperiodo, 'P') = 'P') THEN NULL
                    ELSE COALESCE(left(btrim(max(hm.usuariocierre)), 100), 'migracion-f7') END,
               'migracion-f7'
        FROM public.historialmes hm
        GROUP BY hm.ano, hm.mes
        ON CONFLICT (company_id, anio, mes) DO NOTHING;

        GET DIAGNOSTICS n = ROW_COUNT;
        v_periodos := v_periodos + n;

        INSERT INTO public.adm_periodo_comercial_ciclo
            (company_id, periodo_comercial_id, ciclo_codigo, status_id,
             fecha_apertura, abierto_por, fecha_limite, fecha_cierre, cerrado_por, created_by)
        SELECT v_company,
               p.periodo_comercial_id,
               btrim(hm.ciclo),
               CASE WHEN COALESCE(hm.cerrarperiodo, 'P') = 'P' THEN 1 ELSE 2 END,
               COALESCE(hm.fecha AT TIME ZONE 'UTC', now()),
               COALESCE(left(btrim(hm.usuarioapertura), 100), 'migracion-f7'),
               CASE WHEN COALESCE(hm.cerrarperiodo, 'P') = 'P' THEN hm.fechacierre ELSE NULL END,
               CASE WHEN COALESCE(hm.cerrarperiodo, 'P') = 'P' THEN NULL
                    ELSE (hm.fechacierre::timestamp AT TIME ZONE 'UTC') END,
               CASE WHEN COALESCE(hm.cerrarperiodo, 'P') = 'P' THEN NULL
                    ELSE COALESCE(left(btrim(hm.usuariocierre), 100), 'migracion-f7') END,
               'migracion-f7'
        FROM public.historialmes hm
        JOIN public.adm_periodo_comercial p
          ON p.company_id = v_company
         AND p.anio = hm.ano::int
         AND p.mes = hm.mes::smallint
        WHERE btrim(COALESCE(hm.ciclo, '')) <> ''
        ON CONFLICT (company_id, periodo_comercial_id, ciclo_codigo) DO NOTHING;

        GET DIAGNOSTICS n = ROW_COUNT;
        v_ciclos := v_ciclos + n;
    END LOOP;

    RAISE NOTICE 'F7 migración historialmes: % períodos y % ciclos migrados.', v_periodos, v_ciclos;
END $$;

-- ----------------------------------------------------------------------------
-- 5. Repunte de sp_adm_calcular_factura_lectura (corazón tarifario)
--    Cuerpo copiado de la definición viva; ÚNICO cambio: la validación de
--    período abierto (antes EXISTS sobre historialmes).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sp_adm_calcular_factura_lectura(p_company_id bigint, p_anio integer, p_mes integer, p_cliente_id bigint, p_contador character varying DEFAULT NULL::character varying, p_fecha_lectura date DEFAULT CURRENT_DATE, p_lectura_actual numeric DEFAULT NULL::numeric, p_condicion_lectura character varying DEFAULT 'N'::character varying, p_lectura_promedio numeric DEFAULT NULL::numeric, p_usuario character varying DEFAULT NULL::character varying, p_observacion character varying DEFAULT NULL::character varying, p_id_cai integer DEFAULT NULL::integer, p_correlativo_cai integer DEFAULT NULL::integer, p_numero_factura character varying DEFAULT NULL::character varying, p_informativo character varying DEFAULT NULL::character varying)
 RETURNS TABLE(company_id bigint, cliente_id bigint, cliente_clave text, cliente_nombre text, anio integer, mes integer, contador text, ciclo text, ruta text, secuencia text, tiene_medidor boolean, condicion_lectura_aplicada text, lectura_anterior numeric, lectura_actual_efectiva numeric, consumo_facturable numeric, numero_factura text, id_cai integer, correlativo_cai integer, fecha_factura date, fecha_vencimiento date, subtotal_servicios numeric, subtotal_ajustes numeric, saldos_anteriores numeric, recargos numeric, total_factura numeric, taservi1 numeric, taservi2 numeric, taservi3 numeric, taservi4 numeric, detalle_servicios_json jsonb, warnings_json jsonb, snapshot_contract_version text)
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
    v_cliente public.cliente_maestro%ROWTYPE;
    v_historico public.historicomedicion%ROWTYPE;
    v_fechavence date;
    v_diasvence integer;
    v_contador text;
    v_clave text;
    v_nombre text;
    v_tiene_medidor boolean;
    v_condicion text;
    v_lectura_anterior numeric := 0;
    v_lectura_actual_efectiva numeric := 0;
    v_consumo_facturable numeric := 0;
    v_subtotal_servicios numeric := 0;
    v_subtotal_ajustes numeric := 0;
    v_saldos_anteriores numeric := 0;
    v_recargos numeric := 0;
    v_tasa_mora numeric := 0;
    v_total_factura numeric := 0;
    v_descuento_tercera_edad_acumulado_mes numeric := 0;
    v_taservi1 numeric := 0;
    v_taservi2 numeric := 0;
    v_taservi3 numeric := 0;
    v_taservi4 numeric := 0;
    v_detalle_servicios jsonb := '[]'::jsonb;
    v_warnings jsonb := '[]'::jsonb;
    v_snapshot_contract_version text := 'LECTURA_V3_CONTRACT_1';
    v_periodo_abierto boolean := false;
    v_tiene_historico boolean := false;
    v_base_anchor_cliente_servicio_id bigint;
BEGIN
    SELECT *
    INTO v_cliente
    FROM public.cliente_maestro cm
    WHERE cm.company_id = p_company_id
      AND cm.maestro_cliente_id = p_cliente_id
      AND cm.estado = true;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe cliente activo para company_id=% y cliente_id=%.',
            p_company_id, p_cliente_id;
    END IF;

    v_clave := v_cliente.maestro_cliente_clave;
    v_nombre := v_cliente.maestro_cliente_nombre;
    v_tiene_medidor := COALESCE(v_cliente.maestro_cliente_tiene_medidor, false);
    v_contador := NULLIF(BTRIM(COALESCE(p_contador, v_cliente.contador)), '');
    v_condicion := UPPER(BTRIM(COALESCE(p_condicion_lectura, 'N')));

    IF p_id_cai IS NOT NULL THEN
        PERFORM 1
        FROM public.adm_cai_facturacion c
        WHERE c.company_id = p_company_id
          AND c.cai_id = p_id_cai
          AND c.status_id = 1
        LIMIT 1;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'No existe CAI V3 activo con id=% para company_id=%.', p_id_cai, p_company_id;
        END IF;
    END IF;

    SELECT *
    INTO v_historico
    FROM public.historicomedicion hm
    WHERE hm.company_id = p_company_id
      AND hm.ano = p_anio
      AND hm.mes = p_mes
      AND (
            (v_contador IS NOT NULL AND hm.contador = v_contador)
            OR hm.clave = v_clave
          )
    ORDER BY
        CASE WHEN v_contador IS NOT NULL AND hm.contador = v_contador THEN 0 ELSE 1 END,
        hm.ide DESC
    LIMIT 1;

    v_tiene_historico := FOUND;

    IF v_tiene_historico THEN
        v_lectura_anterior := COALESCE(v_historico.lect_ant, 0);

        SELECT cp.fechavence, cp.diasvence
        INTO v_fechavence, v_diasvence
        FROM public.calendariopro cp
        WHERE cp.ano = p_anio
          AND cp.mes = p_mes
          AND cp.ciclo = v_historico.ciclo
        ORDER BY cp.ide DESC
        LIMIT 1;

        -- F7 (2026-07-04): el período comercial vive en adm_periodo_comercial(_ciclo);
        -- historialmes queda como espejo de solo lectura durante la transición.
        -- (El chequeo legacy sobre historialmes trataba cerrado='C' como abierto
        --  porque su lista de letras no incluía 'C'; desde F7 el cierre bloquea.)
        v_periodo_abierto := public.fn_adm_periodo_comercial_ciclo_abierto(
            p_company_id, p_anio, p_mes, v_historico.ciclo);
    ELSE
        v_warnings := v_warnings || jsonb_build_array('SIN_HISTORICO_PERIODO');
    END IF;

    IF v_tiene_historico AND NOT v_periodo_abierto THEN
        RAISE EXCEPTION 'No hay periodo abierto para anio=% mes=% ciclo=%.',
            p_anio, p_mes, COALESCE(v_historico.ciclo, '(sin ciclo)');
    END IF;

    IF v_tiene_medidor THEN
        IF v_condicion IN ('MIN', 'PND') THEN
            v_consumo_facturable := 0;
            v_lectura_actual_efectiva := v_lectura_anterior;
        ELSIF v_condicion = 'PD' THEN
            v_consumo_facturable := GREATEST(COALESCE(p_lectura_promedio, 0), 0);
            v_lectura_actual_efectiva := v_lectura_anterior + v_consumo_facturable;
        ELSE
            v_lectura_actual_efectiva := COALESCE(p_lectura_actual, v_lectura_anterior);
            v_consumo_facturable := GREATEST(v_lectura_actual_efectiva - v_lectura_anterior, 0);
        END IF;
    ELSE
        v_lectura_actual_efectiva := COALESCE(p_lectura_actual, v_lectura_anterior, 0);
        v_consumo_facturable := 0;
    END IF;

    SELECT COALESCE((
        SELECT s.saldo_actual
        FROM public.sp_obtener_cliente_saldo(v_clave) s
        LIMIT 1
    ), 0)
    INTO v_saldos_anteriores;

    -- ── Recargo por mora (Plan de Arbitrios PC 2026 Art. 130) ──
    -- Si la empresa tiene configurado y ACTIVO el recargo, se aplica la tasa
    -- mensual sobre el saldo vencido. Mes a mes el recargo se acumula porque el
    -- saldo previo del periodo siguiente ya lo incluye.
    IF v_saldos_anteriores > 0 THEN
        SELECT COALESCE(rm.tasa_mensual, 0)
        INTO v_tasa_mora
        FROM public.cfg_recargo_mora rm
        WHERE rm.company_id = p_company_id
          AND rm.activo = true
        LIMIT 1;

        v_recargos := ROUND(COALESCE(v_saldos_anteriores, 0) * COALESCE(v_tasa_mora, 0), 4);

        IF v_recargos > 0 THEN
            v_warnings := v_warnings || jsonb_build_array('RECARGO_MORA_APLICADO');
        END IF;
    END IF;

    IF COALESCE(v_cliente.maestro_cliente_tercera_edad, false) THEN
        SELECT COALESCE(SUM(COALESCE(hm.descuentoapp, 0)), 0)
        INTO v_descuento_tercera_edad_acumulado_mes
        FROM public.historicomedicion hm
        WHERE hm.company_id = p_company_id
          AND hm.ano = p_anio
          AND hm.mes = p_mes
          AND hm.clave = v_clave
          AND (
                NULLIF(BTRIM(COALESCE(p_numero_factura, '')), '') IS NULL
                OR COALESCE(hm.numerofactura, '') <> NULLIF(BTRIM(COALESCE(p_numero_factura, '')), '')
              );
    END IF;

    SELECT cs.cliente_servicio_id
    INTO v_base_anchor_cliente_servicio_id
    FROM public.adm_cliente_servicio cs
    JOIN public.adm_servicio s
      ON s.company_id = cs.company_id
     AND s.servicio_id = cs.servicio_id
    WHERE cs.company_id = p_company_id
      AND cs.cliente_id = p_cliente_id
      AND cs.status_id = 1
      AND p_fecha_lectura >= cs.fecha_alta
      AND (cs.fecha_baja IS NULL OR p_fecha_lectura <= cs.fecha_baja)
      AND s.status_id = 1
      AND s.tipo_servicio_id IN (
            SELECT ts.tipo_servicio_id
            FROM public.adm_tipo_servicio ts
            WHERE ts.company_id = p_company_id
              AND ts.codigo = 'BASE'
      )
    ORDER BY CASE WHEN s.codigo = 'AGUA_POTABLE' THEN 0 ELSE 1 END,
             s.app_orden,
             cs.cliente_servicio_id
    LIMIT 1;

    IF v_base_anchor_cliente_servicio_id IS NULL THEN
        RAISE EXCEPTION 'El cliente % no tiene servicios base activos en adm_cliente_servicio.', v_clave;
    END IF;

    WITH base_services AS (
        SELECT
            cs.cliente_servicio_id,
            cs.cliente_id,
            s.servicio_id,
            s.codigo AS servicio_codigo,
            s.nombre AS servicio_nombre,
            ts.codigo AS tipo_servicio_codigo,
            s.app_orden,
            s.usa_condicion_medicion
        FROM public.adm_cliente_servicio cs
        JOIN public.adm_servicio s
          ON s.company_id = cs.company_id
         AND s.servicio_id = cs.servicio_id
        JOIN public.adm_tipo_servicio ts
          ON ts.company_id = s.company_id
         AND ts.tipo_servicio_id = s.tipo_servicio_id
        WHERE cs.company_id = p_company_id
          AND cs.cliente_id = p_cliente_id
          AND cs.status_id = 1
          AND p_fecha_lectura >= cs.fecha_alta
          AND (cs.fecha_baja IS NULL OR p_fecha_lectura <= cs.fecha_baja)
          AND s.status_id = 1
          AND ts.codigo = 'BASE'
    ),
    base_rule_rows AS (
        SELECT
            bs.cliente_servicio_id,
            bs.cliente_id,
            bs.servicio_id,
            bs.servicio_codigo,
            bs.servicio_nombre,
            bs.tipo_servicio_codigo,
            bs.app_orden,
            rr.cuadro_tarifario_id,
            rr.cuadro_codigo,
            rr.cuadro_nombre,
            rr.regla_tarifaria_id,
            rr.regla_orden,
            rr.tipo_regla_codigo,
            rr.tipo_regla_nombre,
            rr.modo_calculo,
            rr.consumo,
            rr.consumo_minimo,
            rr.consumo_maximo,
            rr.monto_fijo,
            rr.monto_unitario,
            rr.porcentaje,
            rr.unidades_aplicadas,
            rr.alquiler_aplicado,
            rr.monto_calculado,
            rr.servicio_referencia_id,
            rr.servicio_referencia_codigo,
            rr.parametros,
            rr.detalle_calculo,
            'BASE'::text AS origen_calculo
        FROM base_services bs
        CROSS JOIN LATERAL public.sp_adm_resolver_tarifa_cliente_servicio(
            p_company_id,
            bs.cliente_servicio_id,
            p_fecha_lectura,
            CASE
                WHEN bs.usa_condicion_medicion THEN v_consumo_facturable
                ELSE NULL
            END
        ) rr
    ),
    base_lines AS (
        SELECT
            br.cliente_servicio_id,
            br.cliente_id,
            br.servicio_id,
            br.servicio_codigo,
            br.servicio_nombre,
            br.tipo_servicio_codigo,
            br.app_orden,
            MIN(br.cuadro_tarifario_id) AS cuadro_tarifario_id,
            MIN(br.cuadro_codigo) AS cuadro_codigo,
            MIN(br.cuadro_nombre) AS cuadro_nombre,
            MIN(br.regla_tarifaria_id) AS regla_tarifaria_id,
            MIN(br.regla_orden) AS regla_orden,
            SUM(COALESCE(br.monto_calculado, 0))::numeric(18, 4) AS monto,
            false AS aplica_descuento,
            0::numeric(18, 4) AS monto_descuento,
            SUM(COALESCE(br.monto_calculado, 0))::numeric(18, 4) AS monto_final,
            'BASE'::text AS origen_calculo,
            jsonb_agg(
                jsonb_build_object(
                    'regla_tarifaria_id', br.regla_tarifaria_id,
                    'regla_orden', br.regla_orden,
                    'tipo_regla_codigo', br.tipo_regla_codigo,
                    'tipo_regla_nombre', br.tipo_regla_nombre,
                    'modo_calculo', br.modo_calculo,
                    'consumo', br.consumo,
                    'consumo_minimo', br.consumo_minimo,
                    'consumo_maximo', br.consumo_maximo,
                    'monto_fijo', br.monto_fijo,
                    'monto_unitario', br.monto_unitario,
                    'porcentaje', br.porcentaje,
                    'unidades_aplicadas', br.unidades_aplicadas,
                    'alquiler_aplicado', br.alquiler_aplicado,
                    'monto_calculado', br.monto_calculado,
                    'detalle_calculo', br.detalle_calculo
                )
                ORDER BY br.regla_orden, br.regla_tarifaria_id
            ) AS componentes
        FROM base_rule_rows br
        GROUP BY
            br.cliente_servicio_id,
            br.cliente_id,
            br.servicio_id,
            br.servicio_codigo,
            br.servicio_nombre,
            br.tipo_servicio_codigo,
            br.app_orden
    ),
    derived_services AS (
        SELECT
            s.servicio_id,
            s.codigo AS servicio_codigo,
            s.nombre AS servicio_nombre,
            ts.codigo AS tipo_servicio_codigo,
            s.app_orden
        FROM public.adm_servicio s
        JOIN public.adm_tipo_servicio ts
          ON ts.company_id = s.company_id
         AND ts.tipo_servicio_id = s.tipo_servicio_id
        WHERE s.company_id = p_company_id
          AND s.status_id = 1
          AND s.genera_por_regla = true
          AND ts.codigo = 'DERIVADO'
          AND s.codigo IN ('TASA_AMBIENTAL', 'TASA_SVA_ERSAPS')
    ),
    derived_rule_rows AS (
        SELECT
            ds.servicio_id,
            ds.servicio_codigo,
            ds.servicio_nombre,
            ds.tipo_servicio_codigo,
            ds.app_orden,
            rr.cuadro_tarifario_id,
            rr.cuadro_codigo,
            rr.cuadro_nombre,
            rr.regla_tarifaria_id,
            rr.regla_orden,
            rr.tipo_regla_codigo,
            rr.tipo_regla_nombre,
            rr.modo_calculo,
            rr.consumo,
            rr.consumo_minimo,
            rr.consumo_maximo,
            rr.monto_fijo,
            rr.monto_unitario,
            rr.porcentaje,
            rr.unidades_aplicadas,
            rr.alquiler_aplicado,
            rr.monto_referencia,
            rr.monto_calculado,
            rr.servicio_referencia_id,
            rr.servicio_referencia_codigo,
            rr.cliente_servicio_referencia_id,
            rr.parametros,
            rr.detalle_calculo,
            'DERIVADO'::text AS origen_calculo
        FROM derived_services ds
        CROSS JOIN LATERAL public.sp_adm_resolver_servicio_derivado_cliente_servicio(
            p_company_id,
            v_base_anchor_cliente_servicio_id,
            ds.servicio_codigo,
            p_fecha_lectura,
            v_consumo_facturable
        ) rr
    ),
    derived_lines AS (
        SELECT
            NULL::bigint AS cliente_servicio_id,
            p_cliente_id AS cliente_id,
            dr.servicio_id,
            dr.servicio_codigo,
            dr.servicio_nombre,
            dr.tipo_servicio_codigo,
            dr.app_orden,
            MIN(dr.cuadro_tarifario_id) AS cuadro_tarifario_id,
            MIN(dr.cuadro_codigo) AS cuadro_codigo,
            MIN(dr.cuadro_nombre) AS cuadro_nombre,
            MIN(dr.regla_tarifaria_id) AS regla_tarifaria_id,
            MIN(dr.regla_orden) AS regla_orden,
            SUM(COALESCE(dr.monto_calculado, 0))::numeric(18, 4) AS monto,
            false AS aplica_descuento,
            0::numeric(18, 4) AS monto_descuento,
            SUM(COALESCE(dr.monto_calculado, 0))::numeric(18, 4) AS monto_final,
            'DERIVADO'::text AS origen_calculo,
            jsonb_agg(
                jsonb_build_object(
                    'regla_tarifaria_id', dr.regla_tarifaria_id,
                    'regla_orden', dr.regla_orden,
                    'tipo_regla_codigo', dr.tipo_regla_codigo,
                    'tipo_regla_nombre', dr.tipo_regla_nombre,
                    'modo_calculo', dr.modo_calculo,
                    'consumo', dr.consumo,
                    'consumo_minimo', dr.consumo_minimo,
                    'consumo_maximo', dr.consumo_maximo,
                    'monto_fijo', dr.monto_fijo,
                    'monto_unitario', dr.monto_unitario,
                    'porcentaje', dr.porcentaje,
                    'unidades_aplicadas', dr.unidades_aplicadas,
                    'alquiler_aplicado', dr.alquiler_aplicado,
                    'monto_referencia', dr.monto_referencia,
                    'monto_calculado', dr.monto_calculado,
                    'servicio_referencia_id', dr.servicio_referencia_id,
                    'servicio_referencia_codigo', dr.servicio_referencia_codigo,
                    'cliente_servicio_referencia_id', dr.cliente_servicio_referencia_id,
                    'detalle_calculo', dr.detalle_calculo
                )
                ORDER BY dr.regla_orden, dr.regla_tarifaria_id
            ) AS componentes
        FROM derived_rule_rows dr
        GROUP BY
            dr.servicio_id,
            dr.servicio_codigo,
            dr.servicio_nombre,
            dr.tipo_servicio_codigo,
            dr.app_orden
    ),
    all_lines AS (
        SELECT * FROM base_lines
        UNION ALL
        SELECT * FROM derived_lines
    ),
    line_adjustments AS (
        SELECT
            al.cliente_servicio_id,
            al.servicio_id,
            al.origen_calculo,
            LEAST(
                COALESCE(
                    SUM(
                        CASE
                            WHEN aj.condicion_codigo = 'TERCERA_EDAD_DOMESTICO'
                                 AND tat.codigo IN ('DESCUENTO', 'BENEFICIO_ESPECIAL') THEN
                                LEAST(
                                    COALESCE(aj.monto_fijo, 0)
                                    + CASE
                                        WHEN COALESCE(NULLIF(v_cliente.descuento_tercera_edad, 0), aj.porcentaje) IS NOT NULL
                                            THEN al.monto * (COALESCE(NULLIF(v_cliente.descuento_tercera_edad, 0), aj.porcentaje) / 100.0)
                                        ELSE 0
                                      END,
                                    COALESCE(
                                        NULLIF((aj.parametros ->> 'tope_por_factura')::numeric, 0),
                                        aj.tope_maximo,
                                        999999999::numeric
                                    )
                                )
                            ELSE 0
                        END
                    ),
                    0
                ),
                al.monto
            )::numeric(18, 4) AS monto_descuento_potencial_tercera_edad,
            LEAST(
                COALESCE(
                    SUM(
                        CASE
                            WHEN aj.condicion_codigo = 'TERCERA_EDAD_DOMESTICO'
                                 AND tat.codigo IN ('DESCUENTO', 'BENEFICIO_ESPECIAL') THEN
                                LEAST(
                                    LEAST(
                                        COALESCE(aj.monto_fijo, 0)
                                        + CASE
                                            WHEN COALESCE(NULLIF(v_cliente.descuento_tercera_edad, 0), aj.porcentaje) IS NOT NULL
                                                THEN al.monto * (COALESCE(NULLIF(v_cliente.descuento_tercera_edad, 0), aj.porcentaje) / 100.0)
                                            ELSE 0
                                          END,
                                        COALESCE(
                                            NULLIF((aj.parametros ->> 'tope_por_factura')::numeric, 0),
                                            aj.tope_maximo,
                                            999999999::numeric
                                        )
                                    ),
                                    GREATEST(
                                        COALESCE(
                                            NULLIF((aj.parametros ->> 'tope_mensual')::numeric, 0),
                                            NULLIF((aj.parametros ->> 'tope_por_factura')::numeric, 0),
                                            aj.tope_maximo,
                                            999999999::numeric
                                        ) - v_descuento_tercera_edad_acumulado_mes,
                                        0
                                    )
                                )
                            ELSE 0
                        END
                    ),
                    0
                ),
                al.monto
            )::numeric(18, 4) AS monto_descuento_aplicado_tercera_edad,
            LEAST(
                COALESCE(
                    SUM(
                        CASE
                            WHEN tat.codigo IN ('DESCUENTO', 'BENEFICIO_ESPECIAL') THEN
                                CASE
                                    WHEN aj.condicion_codigo = 'TERCERA_EDAD_DOMESTICO' THEN
                                        LEAST(
                                            LEAST(
                                                COALESCE(aj.monto_fijo, 0)
                                                + CASE
                                                    WHEN COALESCE(NULLIF(v_cliente.descuento_tercera_edad, 0), aj.porcentaje) IS NOT NULL
                                                        THEN al.monto * (COALESCE(NULLIF(v_cliente.descuento_tercera_edad, 0), aj.porcentaje) / 100.0)
                                                    ELSE 0
                                                  END,
                                                COALESCE(
                                                    NULLIF((aj.parametros ->> 'tope_por_factura')::numeric, 0),
                                                    aj.tope_maximo,
                                                    999999999::numeric
                                                )
                                            ),
                                            GREATEST(
                                                COALESCE(
                                                    NULLIF((aj.parametros ->> 'tope_mensual')::numeric, 0),
                                                    NULLIF((aj.parametros ->> 'tope_por_factura')::numeric, 0),
                                                    aj.tope_maximo,
                                                    999999999::numeric
                                                ) - v_descuento_tercera_edad_acumulado_mes,
                                                0
                                            )
                                        )
                                    ELSE
                                        LEAST(
                                            COALESCE(aj.monto_fijo, 0)
                                            + CASE
                                                WHEN aj.porcentaje IS NOT NULL
                                                    THEN al.monto * (aj.porcentaje / 100.0)
                                                ELSE 0
                                              END,
                                            COALESCE(aj.tope_maximo, 999999999::numeric)
                                        )
                                END
                            WHEN tat.codigo = 'EXONERACION' THEN
                                al.monto
                            ELSE 0
                        END
                    ),
                    0
                ),
                al.monto
            )::numeric(18, 4) AS monto_descuento
        FROM all_lines al
        JOIN public.adm_ajuste_tarifario aj
          ON aj.company_id = p_company_id
         AND aj.cuadro_tarifario_id = al.cuadro_tarifario_id
         AND aj.status_id = 1
        JOIN public.adm_tipo_ajuste_tarifario tat
          ON tat.company_id = aj.company_id
         AND tat.tipo_ajuste_tarifario_id = aj.tipo_ajuste_tarifario_id
        LEFT JOIN public.adm_cliente_servicio cs
          ON cs.company_id = p_company_id
         AND cs.cliente_servicio_id = al.cliente_servicio_id
        LEFT JOIN public.adm_categoria_regulatoria cr
          ON cr.company_id = cs.company_id
         AND cr.categoria_regulatoria_id = cs.categoria_regulatoria_id
        WHERE
            aj.condicion_codigo IS NULL
            OR aj.condicion_codigo = ''
            OR (
                aj.condicion_codigo = 'TERCERA_EDAD_DOMESTICO'
                AND COALESCE(v_cliente.maestro_cliente_tercera_edad, false)
                AND al.servicio_codigo = 'AGUA_POTABLE'
                AND COALESCE(cr.codigo, '') = 'DOMESTICO'
            )
        GROUP BY
            al.cliente_servicio_id,
            al.servicio_id,
            al.origen_calculo,
            al.monto
    ),
    adjusted_lines AS (
        SELECT
            al.cliente_servicio_id,
            al.cliente_id,
            al.servicio_id,
            al.servicio_codigo,
            al.servicio_nombre,
            al.tipo_servicio_codigo,
            al.app_orden,
            al.cuadro_tarifario_id,
            al.cuadro_codigo,
            al.cuadro_nombre,
            al.regla_tarifaria_id,
            al.regla_orden,
            al.monto,
            (COALESCE(la.monto_descuento, 0) > 0) AS aplica_descuento,
            COALESCE(la.monto_descuento_potencial_tercera_edad, 0)::numeric(18, 4) AS monto_descuento_potencial_tercera_edad,
            COALESCE(la.monto_descuento_aplicado_tercera_edad, 0)::numeric(18, 4) AS monto_descuento_aplicado_tercera_edad,
            COALESCE(la.monto_descuento, 0)::numeric(18, 4) AS monto_descuento,
            GREATEST(al.monto - COALESCE(la.monto_descuento, 0), 0)::numeric(18, 4) AS monto_final,
            al.origen_calculo,
            al.componentes
        FROM all_lines al
        LEFT JOIN line_adjustments la
         ON COALESCE(la.cliente_servicio_id, -1) = COALESCE(al.cliente_servicio_id, -1)
         AND la.servicio_id = al.servicio_id
         AND la.origen_calculo = al.origen_calculo
    ),
    warning_flags AS (
        SELECT
            COALESCE(SUM(al.monto_descuento_potencial_tercera_edad), 0)::numeric(18, 4) AS descuento_tercera_edad_potencial,
            COALESCE(SUM(al.monto_descuento_aplicado_tercera_edad), 0)::numeric(18, 4) AS descuento_tercera_edad_aplicado
        FROM adjusted_lines al
    ),
    totals AS (
        SELECT
            COALESCE(SUM(al.monto_final), 0)::numeric(18, 4) AS subtotal_servicios,
            COALESCE(SUM(al.monto_descuento), 0)::numeric(18, 4) AS subtotal_ajustes,
            COALESCE(MAX(CASE WHEN al.servicio_codigo = 'AGUA_POTABLE' THEN al.monto_final END), 0)::numeric(18, 4) AS taservi1,
            COALESCE(MAX(CASE WHEN al.servicio_codigo = 'ALCANTARILLADO' THEN al.monto_final END), 0)::numeric(18, 4) AS taservi2,
            COALESCE(MAX(CASE WHEN al.servicio_codigo = 'TASA_AMBIENTAL' THEN al.monto_final END), 0)::numeric(18, 4) AS taservi3,
            COALESCE(MAX(CASE WHEN al.servicio_codigo = 'TASA_SVA_ERSAPS' THEN al.monto_final END), 0)::numeric(18, 4) AS taservi4
        FROM adjusted_lines al
    ),
    detail_json AS (
        SELECT COALESCE(
            jsonb_agg(
                jsonb_build_object(
                    'servicio_codigo', al.servicio_codigo,
                    'servicio_nombre', al.servicio_nombre,
                    'tipo_servicio', al.tipo_servicio_codigo,
                    'origen_calculo', al.origen_calculo,
                    'cliente_servicio_id', al.cliente_servicio_id,
                    'cuadro_tarifario_id', al.cuadro_tarifario_id,
                    'cuadro_codigo', al.cuadro_codigo,
                    'cuadro_nombre', al.cuadro_nombre,
                    'regla_tarifaria_id', al.regla_tarifaria_id,
                    'cantidad', CASE
                        WHEN al.servicio_codigo = 'AGUA_POTABLE' AND v_tiene_medidor THEN v_consumo_facturable
                        ELSE 1
                    END,
                    'monto', al.monto,
                    'aplica_descuento', al.aplica_descuento,
                    'monto_descuento', al.monto_descuento,
                    'monto_final', al.monto_final,
                    'componentes', al.componentes
                )
                ORDER BY al.app_orden, al.servicio_nombre, al.servicio_codigo
            ),
            '[]'::jsonb
        ) AS detalle_servicios_json
        FROM adjusted_lines al
    )
    SELECT
        p_company_id,
        p_cliente_id,
        v_clave::text,
        v_nombre::text,
        p_anio,
        p_mes,
        v_contador::text,
        COALESCE(v_historico.ciclo, '')::text,
        COALESCE(v_historico.ruta, '')::text,
        COALESCE(v_historico.secuencia, '')::text,
        v_tiene_medidor,
        v_condicion::text,
        v_lectura_anterior,
        v_lectura_actual_efectiva,
        v_consumo_facturable,
        COALESCE(p_numero_factura, '')::text,
        p_id_cai,
        p_correlativo_cai,
        COALESCE(p_fecha_lectura, current_date),
        v_fechavence,
        t.subtotal_servicios,
        t.subtotal_ajustes,
        v_saldos_anteriores,
        v_recargos,
        (t.subtotal_servicios + v_saldos_anteriores + v_recargos)::numeric(18, 4),
        t.taservi1,
        t.taservi2,
        t.taservi3,
        t.taservi4,
        dj.detalle_servicios_json,
        v_warnings
            || CASE
                WHEN wf.descuento_tercera_edad_potencial > 0
                     AND wf.descuento_tercera_edad_aplicado = 0
                    THEN jsonb_build_array('TOPE_TERCERA_EDAD_AGOTADO')
                ELSE '[]'::jsonb
               END
            || CASE
                WHEN wf.descuento_tercera_edad_potencial > wf.descuento_tercera_edad_aplicado
                     AND wf.descuento_tercera_edad_aplicado > 0
                    THEN jsonb_build_array('TOPE_TERCERA_EDAD_PARCIAL')
                ELSE '[]'::jsonb
               END,
        v_snapshot_contract_version
    INTO
        company_id,
        cliente_id,
        cliente_clave,
        cliente_nombre,
        anio,
        mes,
        contador,
        ciclo,
        ruta,
        secuencia,
        tiene_medidor,
        condicion_lectura_aplicada,
        lectura_anterior,
        lectura_actual_efectiva,
        consumo_facturable,
        numero_factura,
        id_cai,
        correlativo_cai,
        fecha_factura,
        fecha_vencimiento,
        subtotal_servicios,
        subtotal_ajustes,
        saldos_anteriores,
        recargos,
        total_factura,
        taservi1,
        taservi2,
        taservi3,
        taservi4,
        detalle_servicios_json,
        warnings_json,
        snapshot_contract_version
    FROM totals t
    CROSS JOIN detail_json dj
    CROSS JOIN warning_flags wf;

    RETURN NEXT;
END;
$function$;

-- ----------------------------------------------------------------------------
-- 6. Repunte de sp_informacion_ciclo (GetCiclo legacy del WS de lectores)
--    Misma firma y semántica (ruta → ciclo → último período abierto del ciclo).
--    Sin parámetro de empresa: el WS es company-agnóstico y NO cambia (D9);
--    igual que el legacy, resuelve sobre todos los tenants (rutas/ciclos son
--    catálogos globales). El WS actual usa un query inline sobre historialmes
--    (cubierto por el espejo de la sección 3); este SP queda como fallback.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.sp_informacion_ciclo(p_ruta character varying)
 RETURNS TABLE(r_ciclo integer, r_ano integer, r_mes integer)
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_ciclo integer;
    v_ruta_original text;
    v_ruta_normalizada text;
BEGIN
    v_ruta_original := btrim(coalesce(p_ruta, ''));
    v_ruta_normalizada := v_ruta_original;

    IF v_ruta_original ~ '^[0-9]+$' THEN
        v_ruta_normalizada := lpad(v_ruta_original, 5, '0');
    END IF;

    SELECT r.codciclo
    INTO v_ciclo
    FROM rutas r
    WHERE r.codruta = v_ruta_normalizada
       OR r.codruta = v_ruta_original
    ORDER BY CASE WHEN r.codruta = v_ruta_normalizada THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_ciclo IS NULL THEN
        RETURN;
    END IF;

    -- F7: el período comercial vive en adm_periodo_comercial(_ciclo)
    RETURN QUERY
    SELECT
        CASE
            WHEN pc.ciclo_codigo ~ '^[0-9]+$' THEN pc.ciclo_codigo::int
            ELSE v_ciclo
        END AS r_ciclo,
        p.anio AS r_ano,
        p.mes::int AS r_mes
    FROM public.adm_periodo_comercial_ciclo pc
    JOIN public.adm_periodo_comercial p
      ON p.company_id = pc.company_id
     AND p.periodo_comercial_id = pc.periodo_comercial_id
    WHERE p.status_id = 1
      AND pc.status_id = 1
      AND (pc.ciclo_codigo = lpad(v_ciclo::text, 2, '0') OR pc.ciclo_codigo = v_ciclo::text)
    ORDER BY p.anio DESC, p.mes DESC
    LIMIT 1;
END
$function$;

-- ----------------------------------------------------------------------------
-- 7. Cierre comercial: rutas pendientes, cierre de ciclo, checklist y cierre
--    de mes, apertura habilitada por el cierre del mes anterior.
-- ----------------------------------------------------------------------------

-- Rutas del ciclo con su avance de facturación del mes. "Pendiente" = ruta
-- activa con clientes activos y CERO facturas de lectura emitidas en el mes
-- (validación contra factura, NO contra historicomedicion: las filas de
-- historicomedicion se siembran al abrir el período y no prueban sincronía).
-- Rutas activas sin clientes asignados no bloquean (no aparecen).
CREATE OR REPLACE FUNCTION public.fn_adm_periodo_ciclo_rutas_pendientes(
    p_company_id bigint,
    p_periodo_ciclo_id bigint
) RETURNS TABLE(
    codruta varchar,
    clientes_activos bigint,
    facturas_mes bigint,
    pendiente boolean
)
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_ciclo record;
    v_ciclo_id integer;
BEGIN
    SELECT pc.ciclo_codigo, p.anio, p.mes
    INTO v_ciclo
    FROM public.adm_periodo_comercial_ciclo pc
    JOIN public.adm_periodo_comercial p
      ON p.company_id = pc.company_id
     AND p.periodo_comercial_id = pc.periodo_comercial_id
    WHERE pc.company_id = p_company_id
      AND pc.periodo_ciclo_id = p_periodo_ciclo_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe el ciclo de período comercial % para company_id=%.',
            p_periodo_ciclo_id, p_company_id;
    END IF;

    SELECT c.ciclos_id
    INTO v_ciclo_id
    FROM public.ciclos c
    WHERE btrim(c.ciclos_codigo) = v_ciclo.ciclo_codigo
       OR (c.ciclos_codigo ~ '^[0-9]+$' AND v_ciclo.ciclo_codigo ~ '^[0-9]+$'
           AND c.ciclos_codigo::int = v_ciclo.ciclo_codigo::int)
    ORDER BY CASE WHEN btrim(c.ciclos_codigo) = v_ciclo.ciclo_codigo THEN 0 ELSE 1 END
    LIMIT 1;

    IF v_ciclo_id IS NULL THEN
        -- ciclo sin fila de catálogo: no hay rutas que validar
        RETURN;
    END IF;

    RETURN QUERY
    SELECT r.codruta::varchar,
           count(DISTINCT cm.maestro_cliente_id) AS clientes_activos,
           count(DISTINCT f.id) AS facturas_mes,
           (count(DISTINCT f.id) = 0) AS pendiente
    FROM public.rutas r
    JOIN public.cliente_maestro cm
      ON cm.company_id = p_company_id
     AND cm.estado = true
     AND cm.ciclos_id = v_ciclo_id
     AND btrim(split_part(COALESCE(cm.maestro_cliente_indicativo_ruta, ''), '-', 3)) = btrim(r.codruta)
    LEFT JOIN public.factura f
      ON f.company_id = p_company_id
     AND btrim(f.clientecodigo) = btrim(cm.maestro_cliente_clave)
     AND f.tipofacturacion = 'S'
     AND f.tipofactura = 'F'
     AND COALESCE(f.estado_id, 1) <> 3
     AND COALESCE(f.estado, 'A') <> 'N'
     AND btrim(f.ano) ~ '^[0-9]+$' AND btrim(f.ano)::int = v_ciclo.anio
     AND btrim(f.mes) ~ '^[0-9]+$' AND btrim(f.mes)::int = v_ciclo.mes
    WHERE r.estado = true
      AND r.codciclo = v_ciclo_id
    GROUP BY r.codruta
    ORDER BY r.codruta;
END;
$function$;

-- Cierra un ciclo del período comercial. p_forzar=true omite la validación de
-- rutas pendientes (lo usa el flujo legacy de "Generar período" del auxiliar
-- de lectura, que siempre cerró sin validar; el cierre formal de la pantalla
-- de períodos valida u ofrece forzar con confirmación explícita).
CREATE OR REPLACE FUNCTION public.sp_adm_periodo_ciclo_cerrar(
    p_company_id bigint,
    p_periodo_ciclo_id bigint,
    p_usuario text,
    p_forzar boolean DEFAULT false
) RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    v_ciclo record;
    v_pendientes bigint;
BEGIN
    SELECT pc.*, p.anio, p.mes
    INTO v_ciclo
    FROM public.adm_periodo_comercial_ciclo pc
    JOIN public.adm_periodo_comercial p
      ON p.company_id = pc.company_id
     AND p.periodo_comercial_id = pc.periodo_comercial_id
    WHERE pc.company_id = p_company_id
      AND pc.periodo_ciclo_id = p_periodo_ciclo_id
    FOR UPDATE OF pc;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe el ciclo de período comercial % para company_id=%.',
            p_periodo_ciclo_id, p_company_id;
    END IF;

    IF v_ciclo.status_id <> 1 THEN
        RAISE EXCEPTION 'CICLO_YA_CERRADO: el ciclo % del período %-% ya está cerrado.',
            v_ciclo.ciclo_codigo, v_ciclo.anio, lpad(v_ciclo.mes::text, 2, '0');
    END IF;

    IF NOT p_forzar THEN
        SELECT count(*)
        INTO v_pendientes
        FROM public.fn_adm_periodo_ciclo_rutas_pendientes(p_company_id, p_periodo_ciclo_id) rp
        WHERE rp.pendiente;

        IF v_pendientes > 0 THEN
            RAISE EXCEPTION 'CICLO_RUTAS_PENDIENTES: % ruta(s) del ciclo % sin facturas emitidas en %-%.',
                v_pendientes, v_ciclo.ciclo_codigo, v_ciclo.anio, lpad(v_ciclo.mes::text, 2, '0');
        END IF;
    END IF;

    UPDATE public.adm_periodo_comercial_ciclo pc
    SET status_id = 2,
        fecha_cierre = now(),
        cerrado_por = left(p_usuario, 100),
        updated_at = now(),
        updated_by = left(p_usuario, 100)
    WHERE pc.company_id = p_company_id
      AND pc.periodo_ciclo_id = p_periodo_ciclo_id;
END;
$function$;

-- Checklist del cierre del mes comercial.
CREATE OR REPLACE FUNCTION public.fn_adm_periodo_comercial_checklist(
    p_company_id bigint,
    p_periodo_comercial_id bigint
) RETURNS TABLE(
    item varchar,
    ok boolean,
    cantidad bigint,
    detalle text
)
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_periodo record;
    v_n bigint;
    v_detalle text;
BEGIN
    SELECT p.*
    INTO v_periodo
    FROM public.adm_periodo_comercial p
    WHERE p.company_id = p_company_id
      AND p.periodo_comercial_id = p_periodo_comercial_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe el período comercial % para company_id=%.',
            p_periodo_comercial_id, p_company_id;
    END IF;

    -- 1. Todos los ciclos del mes cerrados
    SELECT count(*), string_agg(pc.ciclo_codigo, ', ' ORDER BY pc.ciclo_codigo)
    INTO v_n, v_detalle
    FROM public.adm_periodo_comercial_ciclo pc
    WHERE pc.company_id = p_company_id
      AND pc.periodo_comercial_id = p_periodo_comercial_id
      AND pc.status_id = 1;

    RETURN QUERY SELECT
        'CICLOS_ABIERTOS'::varchar,
        v_n = 0,
        v_n,
        CASE WHEN v_n = 0 THEN 'Todos los ciclos del mes están cerrados.'
             ELSE format('Ciclos abiertos: %s.', v_detalle) END;

    -- 2. Sin rutas pendientes en los ciclos abiertos (validado contra facturas
    --    emitidas; los ciclos ya cerrados validaron sus rutas al cerrarse)
    SELECT COALESCE(sum(pend.pendientes), 0)
    INTO v_n
    FROM public.adm_periodo_comercial_ciclo pc
    CROSS JOIN LATERAL (
        SELECT count(*) AS pendientes
        FROM public.fn_adm_periodo_ciclo_rutas_pendientes(p_company_id, pc.periodo_ciclo_id) rp
        WHERE rp.pendiente
    ) pend
    WHERE pc.company_id = p_company_id
      AND pc.periodo_comercial_id = p_periodo_comercial_id
      AND pc.status_id = 1;

    RETURN QUERY SELECT
        'RUTAS_PENDIENTES'::varchar,
        v_n = 0,
        v_n,
        CASE WHEN v_n = 0 THEN 'Sin rutas pendientes de facturar.'
             ELSE format('%s ruta(s) sin facturas emitidas en el mes.', v_n) END;
END;
$function$;

-- Cierra el mes comercial (requiere checklist en verde). Habilita abrir el
-- mes siguiente (sp_adm_periodo_comercial_abrir valida la secuencia).
CREATE OR REPLACE FUNCTION public.sp_adm_periodo_comercial_cerrar(
    p_company_id bigint,
    p_periodo_comercial_id bigint,
    p_usuario text
) RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    v_periodo record;
    v_fallas text;
BEGIN
    SELECT p.*
    INTO v_periodo
    FROM public.adm_periodo_comercial p
    WHERE p.company_id = p_company_id
      AND p.periodo_comercial_id = p_periodo_comercial_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe el período comercial % para company_id=%.',
            p_periodo_comercial_id, p_company_id;
    END IF;

    IF v_periodo.status_id <> 1 THEN
        RAISE EXCEPTION 'PERIODO_YA_CERRADO: el período comercial %-% ya está cerrado.',
            v_periodo.anio, lpad(v_periodo.mes::text, 2, '0');
    END IF;

    SELECT string_agg(format('%s (%s)', c.item, c.cantidad), '; ')
    INTO v_fallas
    FROM public.fn_adm_periodo_comercial_checklist(p_company_id, p_periodo_comercial_id) c
    WHERE NOT c.ok;

    IF v_fallas IS NOT NULL THEN
        RAISE EXCEPTION 'CHECKLIST_CIERRE_COMERCIAL: %', v_fallas;
    END IF;

    UPDATE public.adm_periodo_comercial p
    SET status_id = 2,
        fecha_cierre = now(),
        cerrado_por = left(p_usuario, 100),
        updated_at = now(),
        updated_by = left(p_usuario, 100)
    WHERE p.company_id = p_company_id
      AND p.periodo_comercial_id = p_periodo_comercial_id;
END;
$function$;

-- Abre (o reutiliza) el período comercial del mes y agrega el ciclo indicado.
-- p_validar_secuencia=true exige que el período del mes calendario anterior,
-- si existe, esté cerrado ("el cierre habilita el mes siguiente", D7). El
-- flujo legacy del auxiliar de lectura llama con false (conserva su
-- comportamiento histórico de generar sin validar secuencia).
-- Devuelve periodo_comercial_id.
CREATE OR REPLACE FUNCTION public.sp_adm_periodo_comercial_abrir(
    p_company_id bigint,
    p_anio integer,
    p_mes integer,
    p_ciclo character varying,
    p_usuario text,
    p_validar_secuencia boolean DEFAULT true
) RETURNS bigint
LANGUAGE plpgsql
AS $function$
DECLARE
    v_ciclo_norm text;
    v_periodo record;
    v_periodo_id bigint;
    v_ciclo_row record;
    v_anio_prev integer;
    v_mes_prev integer;
BEGIN
    IF p_anio IS NULL OR p_mes IS NULL OR p_mes NOT BETWEEN 1 AND 12 THEN
        RAISE EXCEPTION 'Período comercial inválido: anio=%, mes=%.', p_anio, p_mes;
    END IF;

    v_ciclo_norm := btrim(coalesce(p_ciclo, ''));
    IF v_ciclo_norm = '' THEN
        v_ciclo_norm := '01';
    ELSIF v_ciclo_norm ~ '^[0-9]+$' THEN
        v_ciclo_norm := lpad(v_ciclo_norm, 2, '0');
    END IF;

    IF length(v_ciclo_norm) > 2 THEN
        RAISE EXCEPTION 'Código de ciclo inválido: "%". Se esperan códigos cortos (01, 1).', p_ciclo;
    END IF;

    IF p_validar_secuencia THEN
        IF p_mes = 1 THEN
            v_anio_prev := p_anio - 1; v_mes_prev := 12;
        ELSE
            v_anio_prev := p_anio; v_mes_prev := p_mes - 1;
        END IF;

        IF EXISTS (
            SELECT 1 FROM public.adm_periodo_comercial p
            WHERE p.company_id = p_company_id
              AND p.anio = v_anio_prev AND p.mes = v_mes_prev
              AND p.status_id = 1
        ) THEN
            RAISE EXCEPTION 'PERIODO_ANTERIOR_ABIERTO: cierre el mes comercial %-% antes de abrir %-%.',
                v_anio_prev, lpad(v_mes_prev::text, 2, '0'), p_anio, lpad(p_mes::text, 2, '0');
        END IF;
    END IF;

    SELECT p.* INTO v_periodo
    FROM public.adm_periodo_comercial p
    WHERE p.company_id = p_company_id AND p.anio = p_anio AND p.mes = p_mes
    FOR UPDATE;

    IF FOUND THEN
        IF v_periodo.status_id <> 1 THEN
            RAISE EXCEPTION 'PERIODO_CERRADO: el período comercial %-% ya fue cerrado; no se reabre.',
                p_anio, lpad(p_mes::text, 2, '0');
        END IF;
        v_periodo_id := v_periodo.periodo_comercial_id;
    ELSE
        INSERT INTO public.adm_periodo_comercial
            (company_id, anio, mes, status_id, fecha_apertura, abierto_por, created_by)
        VALUES
            (p_company_id, p_anio, p_mes, 1, now(), left(p_usuario, 100), left(p_usuario, 100))
        RETURNING periodo_comercial_id INTO v_periodo_id;
    END IF;

    SELECT pc.* INTO v_ciclo_row
    FROM public.adm_periodo_comercial_ciclo pc
    WHERE pc.company_id = p_company_id
      AND pc.periodo_comercial_id = v_periodo_id
      AND pc.ciclo_codigo = v_ciclo_norm;

    IF FOUND THEN
        IF v_ciclo_row.status_id <> 1 THEN
            RAISE EXCEPTION 'CICLO_CERRADO: el ciclo % del período %-% ya fue cerrado; no se reabre.',
                v_ciclo_norm, p_anio, lpad(p_mes::text, 2, '0');
        END IF;
        -- ya abierto: idempotente
    ELSE
        INSERT INTO public.adm_periodo_comercial_ciclo
            (company_id, periodo_comercial_id, ciclo_codigo, status_id,
             fecha_apertura, abierto_por, fecha_limite, created_by)
        VALUES
            (p_company_id, v_periodo_id, v_ciclo_norm, 1,
             now(), left(p_usuario, 100),
             (make_date(p_anio, p_mes, 1) + interval '1 month' - interval '1 day')::date,
             left(p_usuario, 100));
    END IF;

    RETURN v_periodo_id;
END;
$function$;

-- ----------------------------------------------------------------------------
-- 8. Desfase comercial-contable configurable (D6): meses de diferencia
--    tolerados entre el mes comercial abierto y el período contable abierto
--    antes de emitir aviso.
-- ----------------------------------------------------------------------------

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'con_integracion_config'
          AND column_name = 'desfase_max_meses'
    ) THEN
        ALTER TABLE public.con_integracion_config
            ADD COLUMN desfase_max_meses smallint NOT NULL DEFAULT 1;
        ALTER TABLE public.con_integracion_config
            ADD CONSTRAINT ck_con_integracion_config_desfase
            CHECK (desfase_max_meses BETWEEN 0 AND 12);
    END IF;
END $$;

-- ----------------------------------------------------------------------------
-- 9. Cierre del mes contable: checklist → precierre → cierre → crea siguiente.
--    Estados de con_periodo_contable (convención existente): 0=ABIERTO,
--    1=PRECIERRE, 2=CERRADO. Desde F6, cerrado ⇒ los reportes leen el caché
--    con_saldo_cuenta; por eso el checklist incluye la verificación de saldos.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_con_checklist_cierre_periodo(
    p_company_id bigint,
    p_period_id bigint
) RETURNS TABLE(
    item varchar,
    ok boolean,
    cantidad numeric,
    detalle text
)
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_periodo record;
    v_desde date;
    v_hasta date;
    v_activo_fact boolean := false;
    v_activo_caja boolean := false;
    v_n numeric;
BEGIN
    SELECT pp.* INTO v_periodo
    FROM public.con_periodo_contable pp
    WHERE pp.company_id = p_company_id AND pp.period_id = p_period_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe el período contable % para company_id=%.',
            p_period_id, p_company_id;
    END IF;

    v_desde := v_periodo.start_date::date;
    v_hasta := v_periodo.end_date::date;

    SELECT COALESCE(c.activo_facturacion, false), COALESCE(c.activo_caja, false)
    INTO v_activo_fact, v_activo_caja
    FROM public.con_integracion_config c
    WHERE c.company_id = p_company_id;

    -- 1. Facturas del período con partida generada (puente con_partida_factura, F3)
    IF v_activo_fact THEN
        SELECT count(*) INTO v_n
        FROM public.factura f
        WHERE f.company_id = p_company_id
          AND f.tipofacturacion = 'S'
          AND f.tipofactura = 'F'
          AND COALESCE(f.estado_id, 1) <> 3
          AND COALESCE(f.estado, 'A') <> 'N'
          AND f.fechaemision BETWEEN v_desde AND v_hasta
          AND NOT EXISTS (
              SELECT 1 FROM public.con_partida_factura pf
              WHERE pf.company_id = p_company_id AND pf.factura_id = f.id);

        RETURN QUERY SELECT
            'FACTURAS_SIN_PARTIDA'::varchar, v_n = 0, v_n,
            CASE WHEN v_n = 0 THEN 'Todas las facturas del período tienen partida.'
                 ELSE format('%s factura(s) sin partida: generar el lote de partidas de facturación para el rango %s a %s.', v_n, v_desde, v_hasta) END;
    ELSE
        RETURN QUERY SELECT
            'FACTURAS_SIN_PARTIDA'::varchar, true, 0::numeric,
            'Integración de facturación no activa para la empresa.'::text;
    END IF;

    -- 2. Sin partidas en borrador dentro del período
    SELECT count(*) INTO v_n
    FROM public.con_partida_hdr h
    WHERE h.company_id = p_company_id
      AND h.status = 0
      AND (h.period_id = p_period_id
           OR (h.period_id IS NULL AND h.poliza_date::date BETWEEN v_desde AND v_hasta));

    RETURN QUERY SELECT
        'PARTIDAS_BORRADOR'::varchar, v_n = 0, v_n,
        CASE WHEN v_n = 0 THEN 'Sin partidas en borrador.'
             ELSE format('%s partida(s) en borrador: postearlas o eliminarlas antes de cerrar.', v_n) END;

    -- 3. Caja del período posteada (transacciones de sesión de caja 201/202
    --    con comprobante POSTED del módulo CAJA)
    IF v_activo_caja THEN
        SELECT count(*) INTO v_n
        FROM public.transaccion_abonado t
        WHERE t.company_id = p_company_id
          AND t.caja_id IS NOT NULL
          AND btrim(COALESCE(t.tipotransaccion, '')) IN ('201', '202')
          AND COALESCE(t.estado_id, 1) <> 3
          AND t.fecha_registro BETWEEN v_desde AND v_hasta
          AND NOT EXISTS (
              SELECT 1 FROM public.con_partida_hdr h
              WHERE h.company_id = p_company_id
                AND h.module = 'CAJA'
                AND h.document_id = t.ide
                AND h.status = 1);

        RETURN QUERY SELECT
            'CAJA_SIN_POSTEAR'::varchar, v_n = 0, v_n,
            CASE WHEN v_n = 0 THEN 'La caja del período está posteada.'
                 ELSE format('%s transacción(es) de caja sin comprobante contable posteado.', v_n) END;
    ELSE
        RETURN QUERY SELECT
            'CAJA_SIN_POSTEAR'::varchar, true, 0::numeric,
            'Integración de caja no activa para la empresa.'::text;
    END IF;

    -- 4. Cola de partidas pendientes vacía (toda la empresa: una pendiente de
    --    cualquier fecha se postearía en este período abierto al reprocesarla)
    SELECT count(*) INTO v_n
    FROM public.con_partida_pendiente pp
    WHERE pp.company_id = p_company_id
      AND pp.status_id = 1;

    RETURN QUERY SELECT
        'PENDIENTES_COLA'::varchar, v_n = 0, v_n,
        CASE WHEN v_n = 0 THEN 'Cola de partidas pendientes vacía.'
             ELSE format('%s partida(s) pendiente(s) en cola: reprocesarlas o descartarlas.', v_n) END;

    -- 5. Verificación de saldos del período (F6): caché vs libro sin divergencias
    SELECT count(*) INTO v_n
    FROM public.fn_con_verificar_saldo_cuenta(p_company_id, p_period_id);

    RETURN QUERY SELECT
        'SALDOS_CACHE'::varchar, v_n = 0, v_n,
        CASE WHEN v_n = 0 THEN 'Caché de saldos consistente con el libro.'
             ELSE format('%s divergencia(s) caché vs libro: revisar con "Verificar saldos" antes de cerrar.', v_n) END;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sp_con_periodo_precerrar(
    p_company_id bigint,
    p_period_id bigint,
    p_usuario text
) RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    v_periodo record;
    v_fallas text;
BEGIN
    SELECT pp.* INTO v_periodo
    FROM public.con_periodo_contable pp
    WHERE pp.company_id = p_company_id AND pp.period_id = p_period_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe el período contable % para company_id=%.',
            p_period_id, p_company_id;
    END IF;

    IF COALESCE(v_periodo.status_id, 2) <> 0 THEN
        RAISE EXCEPTION 'ESTADO_INVALIDO: solo un período ABIERTO puede pasar a precierre (período %, estado %).',
            v_periodo.code, COALESCE(v_periodo.status_id, 2);
    END IF;

    SELECT string_agg(format('%s (%s)', c.item, c.cantidad), '; ')
    INTO v_fallas
    FROM public.fn_con_checklist_cierre_periodo(p_company_id, p_period_id) c
    WHERE NOT c.ok;

    IF v_fallas IS NOT NULL THEN
        RAISE EXCEPTION 'CHECKLIST_CIERRE_PERIODO: %', v_fallas;
    END IF;

    UPDATE public.con_periodo_contable pp
    SET status_id = 1,
        status = 'PRECIERRE',
        updated_at = now(),
        updated_by = left(p_usuario, 100)
    WHERE pp.company_id = p_company_id AND pp.period_id = p_period_id;
END;
$function$;

-- Devuelve el period_id del período siguiente (creado o ya existente).
CREATE OR REPLACE FUNCTION public.sp_con_periodo_cerrar(
    p_company_id bigint,
    p_period_id bigint,
    p_usuario text
) RETURNS bigint
LANGUAGE plpgsql
AS $function$
DECLARE
    v_periodo record;
    v_fallas text;
    v_next_start date;
    v_next_end date;
    v_next_code varchar(20);
    v_next_id bigint;
    v_meses text[] := ARRAY['Enero','Febrero','Marzo','Abril','Mayo','Junio',
                            'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
BEGIN
    SELECT pp.* INTO v_periodo
    FROM public.con_periodo_contable pp
    WHERE pp.company_id = p_company_id AND pp.period_id = p_period_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe el período contable % para company_id=%.',
            p_period_id, p_company_id;
    END IF;

    IF COALESCE(v_periodo.status_id, 2) <> 1 THEN
        RAISE EXCEPTION 'ESTADO_INVALIDO: solo un período en PRECIERRE puede cerrarse (período %, estado %). Ejecute primero el precierre.',
            v_periodo.code, COALESCE(v_periodo.status_id, 2);
    END IF;

    SELECT string_agg(format('%s (%s)', c.item, c.cantidad), '; ')
    INTO v_fallas
    FROM public.fn_con_checklist_cierre_periodo(p_company_id, p_period_id) c
    WHERE NOT c.ok;

    IF v_fallas IS NOT NULL THEN
        RAISE EXCEPTION 'CHECKLIST_CIERRE_PERIODO: %', v_fallas;
    END IF;

    UPDATE public.con_periodo_contable pp
    SET status_id = 2,
        status = 'CERRADO',
        closed_at = now(),
        closed_by = left(p_usuario, 100),
        updated_at = now(),
        updated_by = left(p_usuario, 100)
    WHERE pp.company_id = p_company_id AND pp.period_id = p_period_id;

    -- Crear el período siguiente si no existe
    v_next_start := (date_trunc('month', v_periodo.start_date) + interval '1 month')::date;
    v_next_end := (v_next_start + interval '1 month' - interval '1 day')::date;
    v_next_code := to_char(v_next_start, 'YYYYMM');

    SELECT pp.period_id INTO v_next_id
    FROM public.con_periodo_contable pp
    WHERE pp.company_id = p_company_id AND pp.code = v_next_code
    LIMIT 1;

    IF v_next_id IS NULL THEN
        INSERT INTO public.con_periodo_contable
            (company_id, code, name, start_date, end_date, status, status_id, created_at, created_by)
        VALUES
            (p_company_id, v_next_code,
             v_meses[extract(month FROM v_next_start)::int] || ' ' || extract(year FROM v_next_start)::int,
             v_next_start, v_next_end, 'OPEN', 0, now(), left(p_usuario, 100))
        RETURNING period_id INTO v_next_id;
    END IF;

    RETURN v_next_id;
END;
$function$;

-- Reabre un período en PRECIERRE (única reapertura permitida; un CERRADO no
-- se reabre desde la app — los reportes de cerrados leen el caché F6).
CREATE OR REPLACE FUNCTION public.sp_con_periodo_reabrir(
    p_company_id bigint,
    p_period_id bigint,
    p_usuario text
) RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    v_periodo record;
BEGIN
    SELECT pp.* INTO v_periodo
    FROM public.con_periodo_contable pp
    WHERE pp.company_id = p_company_id AND pp.period_id = p_period_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe el período contable % para company_id=%.',
            p_period_id, p_company_id;
    END IF;

    IF COALESCE(v_periodo.status_id, 2) <> 1 THEN
        RAISE EXCEPTION 'ESTADO_INVALIDO: solo un período en PRECIERRE puede reabrirse (período %, estado %).',
            v_periodo.code, COALESCE(v_periodo.status_id, 2);
    END IF;

    UPDATE public.con_periodo_contable pp
    SET status_id = 0,
        status = 'OPEN',
        updated_at = now(),
        updated_by = left(p_usuario, 100)
    WHERE pp.company_id = p_company_id AND pp.period_id = p_period_id;
END;
$function$;

-- ----------------------------------------------------------------------------
-- 10. Avisos de períodos para el banner del portal.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_adm_avisos_periodos(
    p_company_id bigint
) RETURNS TABLE(
    tipo varchar,
    severidad varchar,
    mensaje text,
    cantidad bigint
)
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_hoy_anio integer := extract(year FROM current_date)::int;
    v_hoy_mes integer := extract(month FROM current_date)::int;
    v_hoy_ym integer;
    v_desfase_max integer := 1;
    v_activo_fact boolean := false;
    v_com_ym integer;
    v_con_ym integer;
    v_n bigint;
    v_detalle text;
BEGIN
    v_hoy_ym := v_hoy_anio * 12 + v_hoy_mes;

    SELECT COALESCE(c.desfase_max_meses, 1), COALESCE(c.activo_facturacion, false)
    INTO v_desfase_max, v_activo_fact
    FROM public.con_integracion_config c
    WHERE c.company_id = p_company_id;

    -- 1. Mes comercial vencido sin cerrar
    SELECT count(*), string_agg(format('%s-%s', p.anio, lpad(p.mes::text, 2, '0')), ', ' ORDER BY p.anio, p.mes)
    INTO v_n, v_detalle
    FROM public.adm_periodo_comercial p
    WHERE p.company_id = p_company_id
      AND p.status_id = 1
      AND (p.anio * 12 + p.mes) < v_hoy_ym;

    IF v_n > 0 THEN
        RETURN QUERY SELECT 'COMERCIAL_VENCIDO'::varchar, 'WARN'::varchar,
            format('Mes comercial vencido sin cerrar: %s.', v_detalle), v_n;
    END IF;

    -- 2. Período comercial del mes actual inexistente
    IF NOT EXISTS (
        SELECT 1 FROM public.adm_periodo_comercial p
        WHERE p.company_id = p_company_id AND p.anio = v_hoy_anio AND p.mes = v_hoy_mes
    ) THEN
        RETURN QUERY SELECT 'COMERCIAL_INEXISTENTE'::varchar, 'INFO'::varchar,
            format('No existe el período comercial %s-%s.', v_hoy_anio, lpad(v_hoy_mes::text, 2, '0')), 1::bigint;
    END IF;

    -- 3. Período contable vencido sin cerrar
    SELECT count(*), string_agg(pp.code, ', ' ORDER BY pp.start_date)
    INTO v_n, v_detalle
    FROM public.con_periodo_contable pp
    WHERE pp.company_id = p_company_id
      AND COALESCE(pp.status_id, 2) = 0
      AND pp.end_date::date < date_trunc('month', current_date)::date;

    IF v_n > 0 THEN
        RETURN QUERY SELECT 'CONTABLE_VENCIDO'::varchar, 'WARN'::varchar,
            format('Período contable vencido sin cerrar: %s.', v_detalle), v_n;
    END IF;

    -- 4. Período contable del mes actual inexistente
    IF NOT EXISTS (
        SELECT 1 FROM public.con_periodo_contable pp
        WHERE pp.company_id = p_company_id
          AND current_date BETWEEN pp.start_date::date AND pp.end_date::date
    ) THEN
        RETURN QUERY SELECT 'CONTABLE_INEXISTENTE'::varchar, 'WARN'::varchar,
            'No existe un período contable que cubra la fecha actual.'::text, 1::bigint;
    END IF;

    -- 5. Facturas sin partida (total acumulado, si la integración está activa)
    IF v_activo_fact THEN
        SELECT count(*) INTO v_n
        FROM public.factura f
        WHERE f.company_id = p_company_id
          AND f.tipofacturacion = 'S'
          AND f.tipofactura = 'F'
          AND COALESCE(f.estado_id, 1) <> 3
          AND COALESCE(f.estado, 'A') <> 'N'
          AND NOT EXISTS (
              SELECT 1 FROM public.con_partida_factura pf
              WHERE pf.company_id = p_company_id AND pf.factura_id = f.id);

        IF v_n > 0 THEN
            RETURN QUERY SELECT 'FACTURAS_SIN_PARTIDA'::varchar, 'INFO'::varchar,
                format('%s factura(s) sin partida contable (generar lote de facturación).', v_n), v_n;
        END IF;
    END IF;

    -- 6. Cola de partidas pendientes
    SELECT count(*) INTO v_n
    FROM public.con_partida_pendiente pp
    WHERE pp.company_id = p_company_id AND pp.status_id = 1;

    IF v_n > 0 THEN
        RETURN QUERY SELECT 'PENDIENTES_COLA'::varchar, 'INFO'::varchar,
            format('%s partida(s) pendiente(s) en cola de regularización.', v_n), v_n;
    END IF;

    -- 7. Desfase comercial-contable mayor al configurado
    SELECT max(p.anio * 12 + p.mes) INTO v_com_ym
    FROM public.adm_periodo_comercial p
    WHERE p.company_id = p_company_id AND p.status_id = 1;

    SELECT max(extract(year FROM pp.start_date)::int * 12 + extract(month FROM pp.start_date)::int)
    INTO v_con_ym
    FROM public.con_periodo_contable pp
    WHERE pp.company_id = p_company_id AND COALESCE(pp.status_id, 2) = 0;

    IF v_com_ym IS NOT NULL AND v_con_ym IS NOT NULL
       AND abs(v_com_ym - v_con_ym) > v_desfase_max THEN
        RETURN QUERY SELECT 'DESFASE_COMERCIAL_CONTABLE'::varchar, 'WARN'::varchar,
            format('El mes comercial abierto y el período contable abierto difieren %s mes(es) (máximo configurado: %s).',
                   abs(v_com_ym - v_con_ym), v_desfase_max), abs(v_com_ym - v_con_ym)::bigint;
    END IF;
END;
$function$;

COMMIT;
