-- =============================================================================
-- Integración Contable ↔ Comercial — Fase 8: migración del WS bancario SIMAFI
-- Fecha: 2026-07-04
-- Plan: docs/plans/2026-07-02-plan-integracion-contable-comercial.md §5 Fase 8
-- Contrato: docs/f8-contrato-ws-bancario.md (D8: contrato CONGELADO — byte-compat)
--
-- Contenido:
--   1. AK uq_ban_cuenta_company_id — habilita FKs compuestas tenant-safe hacia
--      ban_cuenta (mismo patrón que uq_factura_company_id de F3).
--   2. ban_ws_credencial — credenciales del canal bancario (equivalente SIAD de
--      la tabla `recolector` de SIMAFI): banco (idBancoWS del contrato), llave,
--      vigencia (INFORMATIVA: el WS viejo JAMÁS la valida — semántica replicada),
--      cuenta bancaria destino de los depósitos y tenant. La credencial resuelve
--      la empresa en cada request del banco (banco+key).
--   3. ban_ws_pago — bitácora e idempotencia del canal (equivalente SIAD de
--      `pagos_bancos`): un registro por referencia aplicada; estados NUMÉRICOS
--      (1=APLICADO, 2=REVERSADO).
--   4. Índice parcial de transaccion_abonado para localizar las transacciones
--      de un pago del WS (marker trans_aplicar = 'WSBANCO:<pago_id>').
--   5. fn_ban_ws_cliente / fn_ban_ws_pendientes — fuente única de la consulta
--      de saldos (la usa la consulta del WS y la validación del pago).
--   6. sp_ban_ws_pagar — pago del banco: idempotente por referencia (advisory
--      lock), monto == total pendiente (contrato /pago/servicios), aplicación
--      FIFO sobre factura_detalle (mismo derrame que AbonoService F4),
--      transaccion_abonado 202 por factura, movimiento ban_kardex DEP
--      (sp_ban_kardex_registrar_movimiento) y comprobante módulo BANCOS vía
--      sp_con_generar_comprobante_config (motor único; sin período abierto →
--      con_partida_pendiente según encolar_sin_periodo).
--   7. sp_ban_ws_reversar — reversión por referencia: restituye saldos de los
--      detalles, anula las transacciones 202, contramovimiento de kardex
--      (sp_ban_kardex_anular_movimiento_recalcular) y reverso del comprobante
--      (sp_con_revertir_comprobante_config).
--   8. Plantilla comentada del INSERT de migración de llaves (las llaves reales
--      NO van en el repo: se extraen de MySQL bdsimafi.recolector en la ventana).
--
-- Requisitos de configuración para postear (igual que F4):
--   con_integracion_config.activo_bancos = true + fila con_integracion_asiento
--   módulo 'BANCOS' (diario + tipo) + matriz con CXC/BANCO_DEFAULT. Con
--   activo_bancos = false el pago se registra SIN comprobante (asimetría
--   transicional documentada en F4). El tipo 'DEP' debe existir en
--   ban_tipos_transacciones de la empresa para el movimiento de kardex.
--
-- Idempotente. Producción: aplicar SOLO en la ventana de deploy acordada.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. AK compuesta de ban_cuenta (soporte de FK tenant-safe)
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_ban_cuenta_company_id' AND conrelid = 'public.ban_cuenta'::regclass)
    THEN
        ALTER TABLE public.ban_cuenta
            ADD CONSTRAINT uq_ban_cuenta_company_id UNIQUE (company_id, banco_cuenta_id);
    END IF;
END$$;

-- -----------------------------------------------------------------------------
-- 2. ban_ws_credencial
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ban_ws_credencial (
    credencial_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id        bigint NOT NULL REFERENCES public.cfg_company (company_id),
    banco             varchar(10)  NOT NULL,  -- idBancoWS del contrato ('001','002','777'…)
    nombre            varchar(100),           -- descriptivo (DAVIVIENDA, BANPAIS…)
    llave             varchar(64),            -- llave vigente (reales: 26–42 chars, MAYÚSCULAS)
    vigencia          date,                   -- INFORMATIVA (el contrato no la valida)
    banco_cuenta_id   bigint,                 -- ban_cuenta destino de los depósitos del canal
    activo            boolean NOT NULL DEFAULT true,
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        varchar(100) NOT NULL DEFAULT CURRENT_USER,
    updated_at        timestamptz,
    updated_by        varchar(100),
    CONSTRAINT uq_ban_ws_credencial_company_banco UNIQUE (company_id, banco),
    CONSTRAINT fk_ban_ws_credencial_cuenta FOREIGN KEY (company_id, banco_cuenta_id)
        REFERENCES public.ban_cuenta (company_id, banco_cuenta_id)
);

CREATE INDEX IF NOT EXISTS ix_ban_ws_credencial_banco_llave
    ON public.ban_ws_credencial (banco, llave)
    WHERE activo;

COMMENT ON TABLE public.ban_ws_credencial IS
'F8: credenciales del WS bancario (contrato SIMAFI congelado). Equivalente de bdsimafi.recolector: el banco autentica con banco+key por query string y la fila resuelve el tenant y la cuenta bancaria destino. La vigencia es informativa (el WS viejo nunca la validó — semántica replicada).';

-- -----------------------------------------------------------------------------
-- 3. ban_ws_pago (bitácora + idempotencia del canal)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ban_ws_pago (
    pago_id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            bigint NOT NULL REFERENCES public.cfg_company (company_id),
    banco                 varchar(10) NOT NULL,
    referencia            varchar(40) NOT NULL,
    clave                 varchar(20) NOT NULL,   -- clave del abonado (cliente_maestro.maestro_cliente_clave)
    tipo                  varchar(1)  NOT NULL DEFAULT 'S',  -- 'S' servicios / 'O' otros
    monto                 numeric(18,2) NOT NULL,
    fecha_registro        date NOT NULL,
    hora_registro         time,
    fecha_efectiva        date,
    sucursal              varchar(30),
    cajero                varchar(20),
    banco_cuenta_id       bigint,
    ban_kardex_id         bigint,
    ban_kardex_reverso_id bigint,
    poliza_id             bigint,                 -- NULL si quedó encolada (con_partida_pendiente)
    status_id             smallint NOT NULL DEFAULT 1,       -- 1=APLICADO, 2=REVERSADO
    reversado_at          timestamptz,
    reversado_por         varchar(100),
    created_at            timestamptz NOT NULL DEFAULT now(),
    created_by            varchar(100) NOT NULL DEFAULT CURRENT_USER,
    CONSTRAINT uq_ban_ws_pago_company_referencia UNIQUE (company_id, referencia),
    CONSTRAINT ck_ban_ws_pago_status CHECK (status_id IN (1, 2)),
    CONSTRAINT fk_ban_ws_pago_cuenta FOREIGN KEY (company_id, banco_cuenta_id)
        REFERENCES public.ban_cuenta (company_id, banco_cuenta_id)
);

CREATE INDEX IF NOT EXISTS ix_ban_ws_pago_company_clave
    ON public.ban_ws_pago (company_id, clave);

COMMENT ON TABLE public.ban_ws_pago IS
'F8: bitácora e idempotencia del WS bancario (equivalente de bdsimafi.pagos_bancos). Una fila por referencia aplicada; status_id 1=APLICADO 2=REVERSADO (estados numéricos). La referencia es única por empresa: replay del mismo pago = misma respuesta sin duplicar; una referencia reversada no se puede volver a pagar.';

-- -----------------------------------------------------------------------------
-- 4. Índice para localizar las transacciones de un pago WS
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS ix_transaccion_abonado_wsbanco
    ON public.transaccion_abonado (company_id, docuaplicar)
    WHERE trans_aplicar LIKE 'WSBANCO:%';

-- -----------------------------------------------------------------------------
-- 5. fn_ban_ws_cliente / fn_ban_ws_pendientes — fuente única de la consulta
-- -----------------------------------------------------------------------------
-- Datos de cabecera del abonado para la consulta del WS.
CREATE OR REPLACE FUNCTION public.fn_ban_ws_cliente(
    p_company_id bigint,
    p_clave varchar
) RETURNS TABLE (
    clave varchar,
    nombre varchar,
    direccion varchar
)
LANGUAGE sql
STABLE
AS $function$
    SELECT cm.maestro_cliente_clave,
           btrim(cm.maestro_cliente_nombre),
           btrim(COALESCE(cd.detalle_cliente_direccion, ''))
    FROM public.cliente_maestro cm
    LEFT JOIN LATERAL (
        SELECT d.detalle_cliente_direccion
        FROM public.cliente_detalle d
        WHERE d.maestro_cliente_id = cm.maestro_cliente_id
        ORDER BY d.detalle_cliente_id
        LIMIT 1
    ) cd ON true
    WHERE cm.company_id = p_company_id
      AND cm.maestro_cliente_clave = btrim(p_clave);
$function$;

-- Líneas pendientes del abonado en orden FIFO (factura más antigua primero).
-- Contrato: un <detalle> por línea con saldo ≠ 0; totalMora = SUM(saldo).
-- El saldo de línea replica la semántica de AbonoService (F4):
-- COALESCE(montovalor_saldo, montovalor, 0).
CREATE OR REPLACE FUNCTION public.fn_ban_ws_pendientes(
    p_company_id bigint,
    p_clave varchar
) RETURNS TABLE (
    factura_id bigint,
    numrecibo integer,
    numfactura varchar,
    fechaemision date,
    fechavence date,
    categoria_servicio_id integer,
    con_medicion boolean,
    detalle_id bigint,
    codigo varchar,
    tiposervicio varchar,
    descripcion varchar,
    saldo numeric
)
LANGUAGE sql
STABLE
AS $function$
    SELECT f.id,
           f.numrecibo,
           f.numfactura,
           f.fechaemision,
           f.fechavence,
           f.categoria_servicio_id,
           f.con_medicion,
           d.id,
           d.codigo,
           d.tiposervicio,
           d.descripcion,
           COALESCE(d.montovalor_saldo, d.montovalor, 0)
    FROM public.factura f
    JOIN public.factura_detalle d ON d.factura_id = f.id
    WHERE f.company_id = p_company_id
      AND f.clientecodigo = btrim(p_clave)
      AND f.estado IN ('A', 'B')
      AND COALESCE(d.montovalor_saldo, d.montovalor, 0) <> 0
    ORDER BY f.fechaemision, f.numrecibo, d.id;
$function$;

COMMENT ON FUNCTION public.fn_ban_ws_pendientes(bigint, varchar) IS
'F8: líneas pendientes del abonado para el WS bancario (FIFO). Fuente única: la consumen la consulta del WS y la validación de monto de sp_ban_ws_pagar — mantenerla única garantiza consulta == pago.';

-- -----------------------------------------------------------------------------
-- 6. sp_ban_ws_pagar
-- -----------------------------------------------------------------------------
-- Códigos de retorno (el controller los mapea a los <mensaje> EXACTOS del
-- contrato): OK, IDEMPOTENTE, REFERENCIA_REVERSADA, SIN_REGISTRO,
-- SIN_PENDIENTES, MONTO_NO_COINCIDE.
CREATE OR REPLACE FUNCTION public.sp_ban_ws_pagar(
    p_company_id bigint,
    p_banco varchar,
    p_referencia varchar,
    p_clave varchar,
    p_monto numeric,
    p_fecha_registro date,
    p_hora_registro time DEFAULT NULL,
    p_fecha_efectiva date DEFAULT NULL,
    p_sucursal varchar DEFAULT NULL,
    p_cajero varchar DEFAULT NULL,
    p_banco_cuenta_id bigint DEFAULT NULL,
    p_tipo varchar DEFAULT 'S',
    p_validar_monto boolean DEFAULT true,
    p_usuario text DEFAULT 'wsbanco'
) RETURNS TABLE (
    status text,
    pago_id bigint,
    poliza_id bigint,
    ban_kardex_id bigint,
    total_pendiente numeric
)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_referencia varchar := btrim(p_referencia);
    v_clave varchar := btrim(p_clave);
    v_usuario text := COALESCE(NULLIF(btrim(p_usuario), ''), 'wsbanco');
    v_existente record;
    v_total numeric;
    v_pago_id bigint;
    v_cuenta_id bigint;
    v_kardex_id bigint;
    v_saldo_kardex numeric;
    v_poliza_id bigint;
    v_config record;
    v_cuenta_banco bigint;
    v_lineas jsonb;
    v_descripcion text;
    v_saldo_cliente numeric;
    v_periodo varchar(6);
    v_factura record;
    v_cliente_info record;
    v_restante numeric;
BEGIN
    IF v_referencia IS NULL OR v_referencia = '' THEN
        RAISE EXCEPTION 'sp_ban_ws_pagar: referencia vacía.';
    END IF;
    IF p_monto IS NULL OR p_monto <= 0 THEN
        RAISE EXCEPTION 'sp_ban_ws_pagar: monto inválido (%).', p_monto;
    END IF;

    -- Serializa por referencia dentro del tenant (idempotencia bajo concurrencia).
    PERFORM pg_advisory_xact_lock(
        hashtextextended('ban_ws_pago:' || p_company_id::text || ':' || v_referencia, 0));

    SELECT * INTO v_existente
    FROM public.ban_ws_pago p
    WHERE p.company_id = p_company_id AND p.referencia = v_referencia;

    IF FOUND THEN
        IF v_existente.status_id = 1 THEN
            -- Replay del mismo pago: misma respuesta, cero duplicación.
            RETURN QUERY SELECT 'IDEMPOTENTE'::text, v_existente.pago_id,
                v_existente.poliza_id, v_existente.ban_kardex_id, v_existente.monto;
            RETURN;
        END IF;
        -- Referencia reversada: el WS viejo la rechazaba (intención de
        -- existeReferencia(ref,'R') en Control.PagarServicios).
        RETURN QUERY SELECT 'REFERENCIA_REVERSADA'::text, v_existente.pago_id,
            NULL::bigint, NULL::bigint, NULL::numeric;
        RETURN;
    END IF;

    -- Cliente y pendientes (fuente única fn_ban_ws_pendientes).
    SELECT cm.ciclos_id, cm.maestro_cliente_indicativo_ruta, cm.maestro_cliente_secuencia,
           cm.maestro_cliente_tiene_medidor
    INTO v_cliente_info
    FROM public.cliente_maestro cm
    WHERE cm.company_id = p_company_id AND cm.maestro_cliente_clave = v_clave;

    IF NOT FOUND THEN
        RETURN QUERY SELECT 'SIN_REGISTRO'::text, NULL::bigint, NULL::bigint, NULL::bigint, NULL::numeric;
        RETURN;
    END IF;

    DROP TABLE IF EXISTS _ws_pendientes;
    CREATE TEMP TABLE _ws_pendientes ON COMMIT DROP AS
    SELECT * FROM public.fn_ban_ws_pendientes(p_company_id, v_clave);

    SELECT COALESCE(SUM(w.saldo), 0) INTO v_total FROM _ws_pendientes w;

    IF v_total <= 0 THEN
        RETURN QUERY SELECT 'SIN_PENDIENTES'::text, NULL::bigint, NULL::bigint, NULL::bigint, v_total;
        RETURN;
    END IF;

    -- Contrato /pago/servicios: el monto debe ser EXACTAMENTE el total pendiente.
    IF p_validar_monto AND round(p_monto, 2) <> round(v_total, 2) THEN
        RETURN QUERY SELECT 'MONTO_NO_COINCIDE'::text, NULL::bigint, NULL::bigint, NULL::bigint, v_total;
        RETURN;
    END IF;

    -- Cuenta bancaria destino: parámetro explícito o la de la credencial.
    v_cuenta_id := p_banco_cuenta_id;
    IF v_cuenta_id IS NULL THEN
        SELECT c.banco_cuenta_id INTO v_cuenta_id
        FROM public.ban_ws_credencial c
        WHERE c.company_id = p_company_id AND c.banco = btrim(p_banco) AND c.activo;
    END IF;

    INSERT INTO public.ban_ws_pago (
        company_id, banco, referencia, clave, tipo, monto,
        fecha_registro, hora_registro, fecha_efectiva, sucursal, cajero,
        banco_cuenta_id, status_id, created_by)
    VALUES (
        p_company_id, btrim(p_banco), v_referencia, v_clave, COALESCE(p_tipo, 'S'), round(p_monto, 2),
        p_fecha_registro, p_hora_registro, p_fecha_efectiva,
        NULLIF(btrim(p_sucursal), ''), NULLIF(btrim(p_cajero), ''),
        v_cuenta_id, 1, v_usuario)
    RETURNING ban_ws_pago.pago_id INTO v_pago_id;

    -- Derrame FIFO sobre las líneas (mismo orden y clamp que AbonoService F4):
    -- aplicado = LEAST(saldo, restante acumulado); solo líneas con saldo > 0.
    DROP TABLE IF EXISTS _ws_aplicacion;
    CREATE TEMP TABLE _ws_aplicacion ON COMMIT DROP AS
    WITH orden AS (
        SELECT w.*,
               SUM(w.saldo) OVER (ORDER BY w.fechaemision, w.numrecibo, w.detalle_id
                                  ROWS UNBOUNDED PRECEDING) AS acumulado
        FROM _ws_pendientes w
        WHERE w.saldo > 0
    )
    SELECT o.*,
           GREATEST(0::numeric, LEAST(o.saldo, round(p_monto, 2) - (o.acumulado - o.saldo))) AS aplicado
    FROM orden o;

    UPDATE public.factura_detalle d
    SET montovalor_saldo = a.saldo - a.aplicado
    FROM _ws_aplicacion a
    WHERE d.id = a.detalle_id AND a.aplicado > 0;

    -- Saldo del cliente para la corrida de transacciones (igual que AbonoService).
    SELECT COALESCE(s.saldo_actual, 0) INTO v_saldo_cliente
    FROM public.sp_obtener_cliente_saldo(p_company_id, v_clave) s;
    v_saldo_cliente := COALESCE(v_saldo_cliente, 0);

    SELECT COALESCE(
        (SELECT lpad(pc.anio::text, 4, '0') || lpad(pc.mes::text, 2, '0')
         FROM public.adm_periodo_comercial pc
         WHERE pc.company_id = p_company_id AND pc.status_id = 1
         ORDER BY pc.anio DESC, pc.mes DESC
         LIMIT 1),
        to_char(p_fecha_registro, 'YYYYMM'))
    INTO v_periodo;

    -- Por factura (FIFO): estado B/C + transaccion_abonado 202 con banco.
    FOR v_factura IN
        SELECT a.factura_id, a.numrecibo, a.numfactura,
               SUM(a.aplicado) AS aplicado
        FROM _ws_aplicacion a
        WHERE a.aplicado > 0
        GROUP BY a.factura_id, a.numrecibo, a.numfactura, a.fechaemision
        ORDER BY a.fechaemision, a.numrecibo
    LOOP
        v_restante := (
            SELECT COALESCE(SUM(COALESCE(d.montovalor_saldo, d.montovalor, 0)), 0)
            FROM public.factura_detalle d
            WHERE d.factura_id = v_factura.factura_id
              AND COALESCE(d.montovalor_saldo, d.montovalor, 0) > 0);

        UPDATE public.factura f
        SET estado = CASE WHEN v_restante <= 0 THEN 'C' ELSE 'B' END,
            fechapago = CASE WHEN v_restante <= 0 THEN p_fecha_registro ELSE f.fechapago END,
            recolectora = CASE WHEN v_restante <= 0 THEN btrim(p_banco) ELSE f.recolectora END,
            usuario = v_usuario
        WHERE f.id = v_factura.factura_id AND f.company_id = p_company_id;

        v_saldo_cliente := v_saldo_cliente - v_factura.aplicado;

        INSERT INTO public.transaccion_abonado (
            company_id, cliente_clave, recibo, tipotransaccion, fecha_docu, tipo_partida,
            banco, descripcion, debitos, creditos, saldo, tipo_servicio, periodo, tasa,
            estado, fecha_registro, ciclo, ruta, secuencia, tiene_med, usuario,
            saldo_detalle, docuaplicar, trans_aplicar)
        VALUES (
            p_company_id, v_clave, v_factura.numrecibo, '202', p_fecha_registro, '002',
            btrim(p_banco),
            'Pago WS banco ' || btrim(p_banco) || ' Ref:' || v_referencia || ' :Recibo # :' || v_factura.numrecibo,
            0, v_factura.aplicado, v_saldo_cliente, 'E', v_periodo, '0',
            'C', p_fecha_registro,
            v_cliente_info.ciclos_id::text,
            v_cliente_info.maestro_cliente_indicativo_ruta,
            v_cliente_info.maestro_cliente_secuencia,
            CASE WHEN v_cliente_info.maestro_cliente_tiene_medidor THEN 'S' ELSE 'N' END,
            v_usuario, v_factura.aplicado, v_pago_id, 'WSBANCO:' || v_pago_id);
    END LOOP;

    -- Movimiento bancario (kardex DEP) si hay cuenta destino configurada.
    v_descripcion := 'Pago WS banco ' || btrim(p_banco) || ' clave ' || v_clave || ' ref ' || v_referencia;
    IF v_cuenta_id IS NOT NULL THEN
        CALL public.sp_ban_kardex_registrar_movimiento(
            p_company_id, v_cuenta_id, 0, 'DEP', p_fecha_registro,
            v_descripcion::varchar, v_referencia, 1::numeric, round(p_monto, 2),
            v_usuario::varchar, v_kardex_id, v_saldo_kardex);
    END IF;

    -- Comprobante contable por configuración (F4): Debe banco / Haber CxC analítica.
    SELECT cfg.modo_cxc, cfg.activo_bancos INTO v_config
    FROM public.con_integracion_config cfg
    WHERE cfg.company_id = p_company_id;

    IF FOUND AND v_config.activo_bancos THEN
        SELECT COALESCE(
            (SELECT bc.cont_account_id FROM public.ban_cuenta bc
             WHERE bc.company_id = p_company_id AND bc.banco_cuenta_id = v_cuenta_id
               AND bc.cont_account_id IS NOT NULL AND bc.cont_account_id > 0),
            public.fn_con_resolver_cuenta(p_company_id, 'BANCO_DEFAULT', NULL, NULL, NULL))
        INTO v_cuenta_banco;

        -- Haberes CxC por cuenta resuelta (modo de la config, snapshot de la
        -- factura) redondeados por cuenta; el Debe es la suma de esos redondeos
        -- (regla F4: nunca redondear la suma cruda de un lado).
        WITH resuelto AS (
            SELECT public.fn_con_resolver_cuenta_modo(
                       p_company_id, 'CXC', v_config.modo_cxc, s.servicio_id,
                       a.categoria_servicio_id, a.con_medicion) AS cuenta_id,
                   a.aplicado
            FROM _ws_aplicacion a
            LEFT JOIN LATERAL (
                SELECT sv.servicio_id
                FROM public.adm_servicio sv
                WHERE sv.company_id = p_company_id
                  AND upper(btrim(sv.codigo)) = upper(btrim(COALESCE(NULLIF(a.tiposervicio, ''), a.codigo, '')))
                ORDER BY sv.servicio_id
                LIMIT 1
            ) s ON true
            WHERE a.aplicado > 0
        ), haberes AS (
            SELECT r.cuenta_id, round(SUM(r.aplicado), 2) AS monto
            FROM resuelto r
            GROUP BY r.cuenta_id
            HAVING round(SUM(r.aplicado), 2) > 0
        )
        SELECT jsonb_insert(
                   COALESCE(jsonb_agg(
                       jsonb_build_object(
                           'account_id', h.cuenta_id,
                           'debe', 0,
                           'haber', h.monto,
                           'descripcion', v_descripcion)
                       ORDER BY h.cuenta_id), '[]'::jsonb),
                   '{0}',
                   jsonb_build_object(
                       'account_id', v_cuenta_banco,
                       'debe', (SELECT round(SUM(h2.monto), 2) FROM haberes h2),
                       'haber', 0,
                       'descripcion', v_descripcion))
        INTO v_lineas
        FROM haberes h;

        v_poliza_id := public.sp_con_generar_comprobante_config(
            p_company_id, 'BANCOS', 'PGB', v_pago_id, 'WSB-' || v_referencia,
            p_fecha_registro, v_descripcion, v_usuario, v_lineas);

        IF v_poliza_id IS NOT NULL AND v_kardex_id IS NOT NULL THEN
            UPDATE public.ban_kardex k
            SET partida_cuenta_id = v_poliza_id
            WHERE k.company_id = p_company_id AND k.ban_kardex_id = v_kardex_id;
        END IF;
    END IF;

    UPDATE public.ban_ws_pago p
    SET ban_kardex_id = v_kardex_id,
        poliza_id = v_poliza_id
    WHERE p.pago_id = v_pago_id;

    RETURN QUERY SELECT 'OK'::text, v_pago_id, v_poliza_id, v_kardex_id, v_total;
END;
$function$;

COMMENT ON FUNCTION public.sp_ban_ws_pagar IS
'F8: pago del WS bancario (contrato SIMAFI congelado). Idempotente por (company, referencia) con advisory lock; valida monto == total pendiente (contrato /pago/servicios); FIFO sobre factura_detalle; transaccion_abonado 202 por factura; kardex DEP + comprobante BANCOS/PGB por config (encola sin período). Códigos: OK, IDEMPOTENTE, REFERENCIA_REVERSADA, SIN_REGISTRO, SIN_PENDIENTES, MONTO_NO_COINCIDE.';

-- -----------------------------------------------------------------------------
-- 7. sp_ban_ws_reversar
-- -----------------------------------------------------------------------------
-- Códigos: OK, NO_EXISTE, YA_REVERSADA.
CREATE OR REPLACE FUNCTION public.sp_ban_ws_reversar(
    p_company_id bigint,
    p_referencia varchar,
    p_usuario text DEFAULT 'wsbanco'
) RETURNS TABLE (
    status text,
    pago_id bigint,
    poliza_reverso_id bigint,
    ban_kardex_reverso_id bigint
)
LANGUAGE plpgsql
AS $function$
DECLARE
    v_referencia varchar := btrim(p_referencia);
    v_usuario text := COALESCE(NULLIF(btrim(p_usuario), ''), 'wsbanco');
    v_pago record;
    v_trans record;
    v_factura record;
    v_restante numeric;
    v_total_factura numeric;
    v_saldo_restaurado numeric;
    v_kardex_rev bigint;
    v_saldo_kardex numeric;
    v_poliza_rev bigint;
BEGIN
    PERFORM pg_advisory_xact_lock(
        hashtextextended('ban_ws_pago:' || p_company_id::text || ':' || v_referencia, 0));

    SELECT * INTO v_pago
    FROM public.ban_ws_pago p
    WHERE p.company_id = p_company_id AND p.referencia = v_referencia
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN QUERY SELECT 'NO_EXISTE'::text, NULL::bigint, NULL::bigint, NULL::bigint;
        RETURN;
    END IF;

    IF v_pago.status_id <> 1 THEN
        RETURN QUERY SELECT 'YA_REVERSADA'::text, v_pago.pago_id, NULL::bigint, NULL::bigint;
        RETURN;
    END IF;

    -- Restituir por transacción (una por factura, FIFO por ide): el derrame
    -- inverso replica ReversarAbonoAsync (max restituible por línea =
    -- montovalor - montovalor_saldo, en orden de detalle).
    FOR v_trans IN
        SELECT t.ide, t.recibo, t.creditos
        FROM public.transaccion_abonado t
        WHERE t.company_id = p_company_id
          AND t.docuaplicar = v_pago.pago_id
          AND t.trans_aplicar = 'WSBANCO:' || v_pago.pago_id
          AND t.estado = 'C'
        ORDER BY t.ide
    LOOP
        SELECT f.id INTO v_factura
        FROM public.factura f
        WHERE f.company_id = p_company_id AND f.numrecibo = v_trans.recibo::integer;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'sp_ban_ws_reversar: no existe la factura del recibo % (pago %).',
                v_trans.recibo, v_pago.pago_id;
        END IF;

        WITH lineas AS (
            SELECT d.id,
                   COALESCE(d.montovalor, 0) - COALESCE(d.montovalor_saldo, 0) AS restituible,
                   SUM(COALESCE(d.montovalor, 0) - COALESCE(d.montovalor_saldo, 0))
                       OVER (ORDER BY d.id ROWS UNBOUNDED PRECEDING) AS acumulado
            FROM public.factura_detalle d
            WHERE d.factura_id = v_factura.id
              AND COALESCE(d.montovalor, 0) - COALESCE(d.montovalor_saldo, 0) > 0
        ), aplicar AS (
            SELECT l.id,
                   GREATEST(0::numeric,
                       LEAST(l.restituible, COALESCE(v_trans.creditos, 0) - (l.acumulado - l.restituible))) AS restituir
            FROM lineas l
        )
        UPDATE public.factura_detalle d
        SET montovalor_saldo = COALESCE(d.montovalor_saldo, 0) + a.restituir
        FROM aplicar a
        WHERE d.id = a.id AND a.restituir > 0;

        SELECT COALESCE(SUM(COALESCE(d.montovalor_saldo, 0)), 0),
               COALESCE(SUM(COALESCE(d.montovalor, 0)), 0)
        INTO v_saldo_restaurado, v_total_factura
        FROM public.factura_detalle d
        WHERE d.factura_id = v_factura.id;

        UPDATE public.factura f
        SET estado = CASE WHEN v_saldo_restaurado >= v_total_factura THEN 'A' ELSE 'B' END,
            fechapago = CASE WHEN v_saldo_restaurado >= v_total_factura THEN NULL ELSE f.fechapago END,
            recolectora = CASE WHEN v_saldo_restaurado >= v_total_factura THEN NULL ELSE f.recolectora END,
            usuario = v_usuario
        WHERE f.id = v_factura.id AND f.company_id = p_company_id;

        UPDATE public.transaccion_abonado t
        SET estado = 'A',
            usuario = v_usuario,
            descripcion = 'REVERSADO WS: ref ' || v_referencia
        WHERE t.ide = v_trans.ide;
    END LOOP;

    -- Contramovimiento de kardex (si el pago registró movimiento).
    IF v_pago.ban_kardex_id IS NOT NULL THEN
        CALL public.sp_ban_kardex_anular_movimiento_recalcular(
            p_company_id, v_pago.banco_cuenta_id, v_pago.ban_kardex_id,
            ('Reversión WS ref ' || v_referencia)::varchar, v_usuario::varchar,
            v_kardex_rev, v_saldo_kardex);
    END IF;

    -- Reverso del comprobante por documento (o descarte de la pendiente viva).
    v_poliza_rev := public.sp_con_revertir_comprobante_config(
        p_company_id, 'BANCOS', ARRAY['PGB']::varchar[], v_pago.pago_id, v_usuario);

    UPDATE public.ban_ws_pago p
    SET status_id = 2,
        reversado_at = now(),
        reversado_por = v_usuario,
        ban_kardex_reverso_id = v_kardex_rev
    WHERE p.pago_id = v_pago.pago_id;

    RETURN QUERY SELECT 'OK'::text, v_pago.pago_id, v_poliza_rev, v_kardex_rev;
END;
$function$;

COMMENT ON FUNCTION public.sp_ban_ws_reversar IS
'F8: reversión del WS bancario por referencia. Restituye saldos de factura_detalle (derrame inverso de ReversarAbonoAsync), anula las transacciones 202 del pago, contramovimiento de kardex y reverso del comprobante BANCOS/PGB. Códigos: OK, NO_EXISTE, YA_REVERSADA.';

-- -----------------------------------------------------------------------------
-- 8. Migración de llaves (plantilla — NO ejecutar aquí)
-- -----------------------------------------------------------------------------
-- Las llaves reales NO van al repo. En la ventana de cutover se extraen del
-- MySQL de SIMAFI y se cargan con este patrón (idempotente por (company, banco)):
--
--   -- En MySQL (bdsimafi):
--   --   SELECT idBancoWS, descripcion, llave, vigencia
--   --   FROM recolector WHERE idBancoWS IS NOT NULL AND llave IS NOT NULL;
--
--   INSERT INTO public.ban_ws_credencial
--       (company_id, banco, nombre, llave, vigencia, banco_cuenta_id, activo, created_by)
--   VALUES
--       (:company_id, :banco, :nombre, :llave, :vigencia, :banco_cuenta_id, true, 'migracion-f8')
--   ON CONFLICT (company_id, banco) DO UPDATE
--       SET llave = EXCLUDED.llave,
--           vigencia = EXCLUDED.vigencia,
--           nombre = EXCLUDED.nombre,
--           banco_cuenta_id = EXCLUDED.banco_cuenta_id,
--           activo = true,
--           updated_at = now(),
--           updated_by = 'migracion-f8';
--
-- Bancos con llave vigente en producción SIMAFI al 2026-07-04 (verificado):
-- 001, 002, 005, 006, 015, 022, 028, 045, 050, 051, 070, 555, 777.
-- El banco_cuenta_id (cuenta destino de los depósitos) se asigna con el área
-- contable al cargar las llaves.
