-- =============================================================================
-- App Lectores (Flutter) — Fase L3: backend propio apc.MobileApi
-- Fecha: 2026-07-05
-- Plan: app_lectores/docs/PLAN_EJECUCION_2026-07.md (fases L0–L12, decisiones A4/A6)
--
-- La app Flutter nueva NO consume el WS WCF viejo (queda para la app Java): usa
-- una API REST/JSON moderna (apc.MobileApi) que reusa los MISMOS SPs V3. Este
-- script crea SOLO la capa de credenciales/sesión de esa API — los SPs de datos
-- (sp_medidores_por_ruta_ws, sp_adm_generar_snapshot_offline_cliente_lectura,
-- sp_lectura_v3, sp_informacion_ciclo, CAI sync) ya existen y NO se tocan.
--
-- Decisión de auth (A6 — multitenancy por credencial desde el día 0):
--   usuarioapc (tabla del WS viejo) NO tiene company_id → no puede resolver el
--   tenant. Se crean tablas nuevas multitenant, SEMBRADAS desde usuarioapc (se
--   reusan los lectores existentes de la empresa APC), con el mismo patrón que
--   ban_ws_credencial de F8: la credencial resuelve la empresa en cada request.
--
--   1. adm_lector_credencial — cuenta del lector (multitenant). La clave se
--      guarda hasheada (bcrypt vía pgcrypto), NO en claro como usuarioapc.clave.
--   2. adm_lector_sesion — sesión por dispositivo: token bearer emitido en el
--      login, con expiración y revocación (logout). El token resuelve el tenant
--      y la ruta del lector en el middleware — nunca por parámetro del cliente.
--   3. Migración idempotente usuarioapc → adm_lector_credencial (company 2 = APC).
--
-- Idempotente. El WS viejo y usuarioapc quedan intactos (paridad app Java).
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- 1. adm_lector_credencial — cuenta del lector (multitenant)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.adm_lector_credencial (
    credencial_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      bigint NOT NULL REFERENCES public.cfg_company (company_id),
    codigo          varchar(25)  NOT NULL,  -- login del lector (≙ usuarioapc.usuario)
    clave_hash      text         NOT NULL,  -- bcrypt (pgcrypto crypt/gen_salt('bf'))
    lector_nombre   varchar(100),
    ruta            varchar(6),             -- ruta asignada (≙ usuarioapc.ruta)
    codciclo        integer,                -- ciclo por defecto del lector
    activo          boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      varchar(100) NOT NULL DEFAULT CURRENT_USER,
    updated_at      timestamptz,
    updated_by      varchar(100)
);

-- Unicidad del login por empresa, case-insensitive (usuarioapc mezcla mayúsc.).
CREATE UNIQUE INDEX IF NOT EXISTS uq_adm_lector_credencial_company_codigo
    ON public.adm_lector_credencial (company_id, lower(codigo));

COMMENT ON TABLE public.adm_lector_credencial IS
'L3 app_lectores: cuenta del lector para la API móvil apc.MobileApi (multitenant, patrón ban_ws_credencial). La clave se guarda hasheada (bcrypt). Sembrada desde usuarioapc; el WS viejo y usuarioapc quedan intactos para la app Java.';

-- -----------------------------------------------------------------------------
-- 2. adm_lector_sesion — sesión por dispositivo (token bearer)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.adm_lector_sesion (
    sesion_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      bigint NOT NULL REFERENCES public.cfg_company (company_id),
    credencial_id   bigint NOT NULL REFERENCES public.adm_lector_credencial (credencial_id),
    token           varchar(128) NOT NULL,  -- opaco (hex de RandomNumberGenerator)
    dispositivo     varchar(120),           -- id/nombre del dispositivo (informativo)
    emitida_at      timestamptz NOT NULL DEFAULT now(),
    expira_at       timestamptz NOT NULL,
    revocada_at     timestamptz,            -- logout / rotación
    CONSTRAINT uq_adm_lector_sesion_token UNIQUE (token)
);

-- Búsqueda del middleware: token vigente (no revocado ni expirado).
CREATE INDEX IF NOT EXISTS ix_adm_lector_sesion_vigente
    ON public.adm_lector_sesion (token)
    WHERE revocada_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_adm_lector_sesion_credencial
    ON public.adm_lector_sesion (credencial_id);

COMMENT ON TABLE public.adm_lector_sesion IS
'L3 app_lectores: sesión de dispositivo de la API móvil. El token bearer se emite en el login y resuelve el tenant (company_id) y la ruta del lector — nunca por parámetro del cliente (A6). Expira y se revoca en logout.';

-- -----------------------------------------------------------------------------
-- 3. Migración usuarioapc → adm_lector_credencial (APC = company_id 2)
--    Idempotente: solo inserta lectores que aún no existen (por codigo, ci).
--    La clave en claro de usuarioapc se hashea con bcrypt al sembrar.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    v_company_id bigint := 2;  -- APC (única empresa con lectores en siad_v3)
BEGIN
    IF EXISTS (SELECT 1 FROM public.cfg_company WHERE company_id = v_company_id) THEN
        INSERT INTO public.adm_lector_credencial
            (company_id, codigo, clave_hash, lector_nombre, ruta, codciclo, activo, created_by)
        SELECT
            v_company_id,
            btrim(u.usuario),
            crypt(coalesce(u.clave, ''), gen_salt('bf')),
            u.nombre,
            u.ruta,
            u.codciclo,
            (upper(coalesce(u.estado, 'A')) = 'A'),
            'l3-seed-usuarioapc'
        FROM public.usuarioapc u
        WHERE u.usuario IS NOT NULL
          AND btrim(u.usuario) <> ''
          AND NOT EXISTS (
              SELECT 1 FROM public.adm_lector_credencial c
              WHERE c.company_id = v_company_id
                AND lower(c.codigo) = lower(btrim(u.usuario))
          );
    END IF;
END$$;
