-- =============================================================================
-- Estado de Flujos de Efectivo (metodo directo) segun Manual de Contabilidad
-- Regulatoria ERSAPS. Comparativo ejercicio actual vs ejercicio anterior.
--
-- Piezas:
--   1. Tabla public.con_configuracion_flujo_efectivo: lineas del reporte por
--      empresa. Cada linea mapea una o varias cuentas (subarbol del plan) que
--      actuan como CONTRAPARTIDA de los movimientos de efectivo.
--      - actividad: 0=OPERACION, 1=INVERSION, 2=FINANCIACION,
--                   9=EFECTIVO (define las cuentas de efectivo y equivalentes;
--                     no se imprime como linea).
--      - tipo_linea: 0=cobro, 1=pago, 2=etiqueta (fila sin monto, p.ej. 'Menos:').
--   2. Funcion public.rep_estado_flujo_efectivo(p_company_id, p_fecha_desde,
--      p_fecha_hasta): clasifica cada partida contable que toca cuentas de
--      efectivo; las contrapartidas (credito - debito) se asignan a la linea
--      configurada mas especifica (con preferencia por el tipo que coincide con
--      el signo del movimiento). Las contrapartidas sin linea configurada caen
--      en 'Otros cobros/pagos de efectivo no clasificados' dentro de OPERACION,
--      de modo que el neto SIEMPRE cuadra con la variacion real del efectivo.
--
-- La funcion incluye los datos de la empresa en uso (cfg_company +
-- con_empresa_configuracion) siguiendo el patron de rep_estado_resultados.
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.con_configuracion_flujo_efectivo (
    config_flujo_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    numero_linea smallint NOT NULL,
    actividad smallint NOT NULL,
    tipo_linea smallint NOT NULL DEFAULT 0,
    codigo_cuenta character varying(30),
    descripcion_linea character varying(200),
    nivel_indentacion smallint NOT NULL DEFAULT 0,
    mostrar_subtotal boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by character varying(100) NOT NULL DEFAULT 'sistema',
    updated_at timestamp with time zone,
    updated_by character varying(100),
    CONSTRAINT ck_con_cfg_flujo_actividad CHECK (actividad IN (0, 1, 2, 9)),
    CONSTRAINT ck_con_cfg_flujo_tipo_linea CHECK (tipo_linea IN (0, 1, 2))
);

CREATE INDEX IF NOT EXISTS ix_con_cfg_flujo_company_linea
    ON public.con_configuracion_flujo_efectivo (company_id, actividad, numero_linea);

COMMENT ON TABLE public.con_configuracion_flujo_efectivo
IS 'Configuracion por empresa de las lineas del Estado de Flujos de Efectivo ERSAPS. actividad: 0 operacion, 1 inversion, 2 financiacion, 9 cuentas de efectivo. tipo_linea: 0 cobro, 1 pago, 2 etiqueta.';

DROP FUNCTION IF EXISTS public.rep_estado_flujo_efectivo(bigint, date, date);

CREATE FUNCTION public.rep_estado_flujo_efectivo(
    p_company_id bigint,
    p_fecha_desde date,
    p_fecha_hasta date
)
RETURNS TABLE(
    empresa_id bigint,
    empresa_codigo text,
    empresa_nombre text,
    empresa_nombre_legal text,
    empresa_rtn text,
    empresa_email text,
    empresa_telefono text,
    empresa_direccion text,
    seccion_orden integer,
    seccion_nombre text,
    linea_orden integer,
    tipo_linea smallint,
    codigo_cuenta character varying,
    descripcion text,
    descripcion_mostrar text,
    nivel_indentacion smallint,
    mostrar_subtotal boolean,
    monto numeric,
    monto_neto numeric,
    monto_anterior numeric,
    monto_neto_anterior numeric
)
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_fecha_desde_anterior date;
    v_fecha_hasta_anterior date;
BEGIN
    IF COALESCE(p_company_id, 0) <= 0 THEN
        RAISE EXCEPTION 'El parametro p_company_id es obligatorio.';
    END IF;
    IF p_fecha_desde IS NULL OR p_fecha_hasta IS NULL THEN
        RAISE EXCEPTION 'Los parametros p_fecha_desde y p_fecha_hasta son obligatorios.';
    END IF;
    IF p_fecha_hasta < p_fecha_desde THEN
        RAISE EXCEPTION 'La fecha hasta no puede ser menor que la fecha desde.';
    END IF;
    IF NOT EXISTS (
        SELECT 1
        FROM public.cfg_company co
        WHERE co.company_id = p_company_id
    ) THEN
        RAISE EXCEPTION 'No existe cfg_company.company_id=%.', p_company_id;
    END IF;
    IF NOT EXISTS (
        SELECT 1
        FROM public.con_configuracion_flujo_efectivo f
        WHERE f.company_id = p_company_id
          AND f.actividad = 9
          AND f.codigo_cuenta IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'No hay cuentas de efectivo configuradas (actividad=9) en con_configuracion_flujo_efectivo para company_id=%.', p_company_id;
    END IF;

    v_fecha_desde_anterior := (p_fecha_desde - INTERVAL '1 year')::date;
    v_fecha_hasta_anterior := (p_fecha_hasta - INTERVAL '1 year')::date;

    RETURN QUERY
    WITH RECURSIVE plan AS
    (
        SELECT c.account_id, c.parent_account_id, c.code
        FROM public.con_plan_cuentas c
        WHERE c.company_id = p_company_id
          AND COALESCE(upper(c.status), 'ACTIVO') NOT IN ('INACTIVO', 'INACTIVE')
    ),
    empresa AS
    (
        SELECT
            co.company_id AS empresa_id,
            co.code::text AS empresa_codigo,
            co.commercial_name::text AS empresa_nombre,
            co.legal_name::text AS empresa_nombre_legal,
            ec.id_fiscal_valor::text AS empresa_rtn,
            co.email::text AS empresa_email,
            co.phone::text AS empresa_telefono,
            co.address::text AS empresa_direccion
        FROM public.cfg_company co
        LEFT JOIN public.con_empresa_configuracion ec
          ON ec.company_id = co.company_id
        WHERE co.company_id = p_company_id
    ),
    configuracion AS
    (
        SELECT
            f.config_flujo_id,
            f.numero_linea,
            f.actividad,
            f.tipo_linea,
            f.codigo_cuenta,
            NULLIF(regexp_replace(COALESCE(f.codigo_cuenta, ''), '[./\s-]', '', 'g'), '') AS codigo_normalizado,
            COALESCE(NULLIF(btrim(f.descripcion_linea), ''), COALESCE(f.codigo_cuenta, ''))::text AS descripcion,
            COALESCE(f.nivel_indentacion, 0)::smallint AS nivel_indentacion,
            f.mostrar_subtotal
        FROM public.con_configuracion_flujo_efectivo f
        WHERE f.company_id = p_company_id
    ),
    config_raices AS
    (
        SELECT
            cfg.config_flujo_id,
            cfg.actividad,
            cfg.tipo_linea,
            cfg.numero_linea,
            length(cfg.codigo_normalizado) AS especificidad,
            pl.account_id
        FROM configuracion cfg
        JOIN plan pl
          ON regexp_replace(COALESCE(pl.code, ''), '[./\s-]', '', 'g') = cfg.codigo_normalizado
        WHERE cfg.codigo_normalizado IS NOT NULL
    ),
    subarbol AS
    (
        SELECT cr.config_flujo_id, cr.actividad, cr.tipo_linea, cr.numero_linea, cr.especificidad, cr.account_id
        FROM config_raices cr
        UNION ALL
        SELECT s.config_flujo_id, s.actividad, s.tipo_linea, s.numero_linea, s.especificidad, ch.account_id
        FROM subarbol s
        JOIN plan ch ON ch.parent_account_id = s.account_id
    ),
    cuentas_efectivo AS
    (
        SELECT DISTINCT s.account_id
        FROM subarbol s
        WHERE s.actividad = 9
    ),
    legs AS
    (
        SELECT
            h.poliza_id,
            CASE
                WHEN h.poliza_date::date BETWEEN p_fecha_desde AND p_fecha_hasta THEN 0
                ELSE 1
            END AS periodo,
            d.account_id,
            SUM(COALESCE(d.credit_amount, 0) - COALESCE(d.debit_amount, 0))::numeric(18,2) AS neto
        FROM public.con_partida_hdr h
        JOIN public.con_partida_dtl d
          ON d.company_id = h.company_id
         AND d.poliza_id = h.poliza_id
        WHERE h.company_id = p_company_id
          AND h.status = 1
          AND h.type_id <> 27
          AND (
              h.poliza_date::date BETWEEN p_fecha_desde AND p_fecha_hasta
              OR h.poliza_date::date BETWEEN v_fecha_desde_anterior AND v_fecha_hasta_anterior
          )
        GROUP BY 1, 2, 3
    ),
    polizas_efectivo AS
    (
        SELECT DISTINCT l.poliza_id, l.periodo
        FROM legs l
        JOIN cuentas_efectivo ce ON ce.account_id = l.account_id
    ),
    contrapartidas AS
    (
        SELECT l.poliza_id, l.periodo, l.account_id, l.neto
        FROM legs l
        JOIN polizas_efectivo pe
          ON pe.poliza_id = l.poliza_id
         AND pe.periodo = l.periodo
        WHERE NOT EXISTS (
            SELECT 1
            FROM cuentas_efectivo ce
            WHERE ce.account_id = l.account_id
        )
          AND l.neto <> 0
    ),
    clasificadas AS
    (
        SELECT
            cp.periodo,
            cp.neto,
            mejor.actividad AS actividad_linea,
            mejor.numero_linea
        FROM contrapartidas cp
        LEFT JOIN LATERAL (
            SELECT s.actividad, s.numero_linea
            FROM subarbol s
            WHERE s.account_id = cp.account_id
              AND s.actividad IN (0, 1, 2)
            ORDER BY
                s.especificidad DESC,
                CASE
                    WHEN (cp.neto >= 0 AND s.tipo_linea = 0)
                      OR (cp.neto < 0 AND s.tipo_linea = 1) THEN 0
                    ELSE 1
                END,
                s.numero_linea
            LIMIT 1
        ) mejor ON TRUE
    ),
    acumulados_linea AS
    (
        SELECT
            cl.actividad_linea AS actividad,
            cl.numero_linea,
            COALESCE(SUM(cl.neto) FILTER (WHERE cl.periodo = 0), 0)::numeric(18,2) AS neto_actual,
            COALESCE(SUM(cl.neto) FILTER (WHERE cl.periodo = 1), 0)::numeric(18,2) AS neto_anterior
        FROM clasificadas cl
        WHERE cl.numero_linea IS NOT NULL
        GROUP BY cl.actividad_linea, cl.numero_linea
    ),
    no_clasificadas AS
    (
        SELECT
            CASE WHEN cl.neto >= 0 THEN 0 ELSE 1 END AS tipo_linea,
            COALESCE(SUM(cl.neto) FILTER (WHERE cl.periodo = 0), 0)::numeric(18,2) AS neto_actual,
            COALESCE(SUM(cl.neto) FILTER (WHERE cl.periodo = 1), 0)::numeric(18,2) AS neto_anterior
        FROM clasificadas cl
        WHERE cl.numero_linea IS NULL
        GROUP BY 1
    ),
    lineas_config AS
    (
        SELECT
            cfg.actividad,
            cfg.numero_linea,
            MIN(cfg.tipo_linea) AS tipo_linea,
            MIN(cfg.codigo_cuenta) AS codigo_cuenta,
            MIN(cfg.descripcion) AS descripcion,
            MIN(cfg.nivel_indentacion) AS nivel_indentacion,
            bool_or(cfg.mostrar_subtotal) AS mostrar_subtotal
        FROM configuracion cfg
        WHERE cfg.actividad IN (0, 1, 2)
        GROUP BY cfg.actividad, cfg.numero_linea
    ),
    base AS
    (
        SELECT
            (lc.actividad::integer + 1) * 10 AS seccion_orden,
            CASE lc.actividad
                WHEN 0 THEN 'ACTIVIDADES DE OPERACION'
                WHEN 1 THEN 'ACTIVIDADES DE INVERSION'
                ELSE 'ACTIVIDADES DE FINANCIACION'
            END::text AS seccion_nombre,
            lc.numero_linea::integer AS linea_orden,
            lc.tipo_linea::smallint AS tipo_linea,
            lc.codigo_cuenta::character varying AS codigo_cuenta,
            lc.descripcion,
            concat(repeat('  ', GREATEST(lc.nivel_indentacion::integer, 0)), lc.descripcion)::text AS descripcion_mostrar,
            lc.nivel_indentacion,
            lc.mostrar_subtotal,
            CASE
                WHEN lc.tipo_linea = 2 THEN NULL::numeric(18,2)
                WHEN lc.tipo_linea = 1 THEN (COALESCE(al.neto_actual, 0) * -1)::numeric(18,2)
                ELSE COALESCE(al.neto_actual, 0)::numeric(18,2)
            END AS monto,
            CASE
                WHEN lc.tipo_linea = 2 THEN NULL::numeric(18,2)
                ELSE COALESCE(al.neto_actual, 0)::numeric(18,2)
            END AS monto_neto,
            CASE
                WHEN lc.tipo_linea = 2 THEN NULL::numeric(18,2)
                WHEN lc.tipo_linea = 1 THEN (COALESCE(al.neto_anterior, 0) * -1)::numeric(18,2)
                ELSE COALESCE(al.neto_anterior, 0)::numeric(18,2)
            END AS monto_anterior,
            CASE
                WHEN lc.tipo_linea = 2 THEN NULL::numeric(18,2)
                ELSE COALESCE(al.neto_anterior, 0)::numeric(18,2)
            END AS monto_neto_anterior
        FROM lineas_config lc
        LEFT JOIN acumulados_linea al
          ON al.actividad = lc.actividad
         AND al.numero_linea = lc.numero_linea

        UNION ALL

        SELECT
            10 AS seccion_orden,
            'ACTIVIDADES DE OPERACION'::text,
            CASE WHEN nc.tipo_linea = 0 THEN 88 ELSE 89 END,
            nc.tipo_linea::smallint,
            NULL::character varying,
            CASE
                WHEN nc.tipo_linea = 0 THEN 'Otros cobros de efectivo no clasificados'
                ELSE 'Otros pagos de efectivo no clasificados'
            END::text,
            CASE
                WHEN nc.tipo_linea = 0 THEN 'Otros cobros de efectivo no clasificados'
                ELSE 'Otros pagos de efectivo no clasificados'
            END::text,
            0::smallint,
            false,
            CASE
                WHEN nc.tipo_linea = 1 THEN (nc.neto_actual * -1)::numeric(18,2)
                ELSE nc.neto_actual
            END,
            nc.neto_actual,
            CASE
                WHEN nc.tipo_linea = 1 THEN (nc.neto_anterior * -1)::numeric(18,2)
                ELSE nc.neto_anterior
            END,
            nc.neto_anterior
        FROM no_clasificadas nc
        WHERE nc.neto_actual <> 0 OR nc.neto_anterior <> 0
    ),
    totales AS
    (
        SELECT
            b.seccion_orden,
            COALESCE(SUM(b.monto_neto), 0)::numeric(18,2) AS total_actual,
            COALESCE(SUM(b.monto_neto_anterior), 0)::numeric(18,2) AS total_anterior
        FROM base b
        GROUP BY b.seccion_orden
    ),
    calculadas AS
    (
        SELECT
            s.seccion_orden,
            CASE s.seccion_orden
                WHEN 10 THEN 'ACTIVIDADES DE OPERACION'
                WHEN 20 THEN 'ACTIVIDADES DE INVERSION'
                ELSE 'ACTIVIDADES DE FINANCIACION'
            END::text AS seccion_nombre,
            90 AS linea_orden,
            3::smallint AS tipo_linea,
            NULL::character varying AS codigo_cuenta,
            CASE s.seccion_orden
                WHEN 10 THEN 'Aumento (disminucion) del Efectivo y Equivalente de Efectivo provenientes de las Actividades de Operacion'
                WHEN 20 THEN 'Aumento (disminucion) del Efectivo y Equivalente de Efectivo provenientes de las Actividades de Inversion'
                ELSE 'Aumento (disminucion) del Efectivo y Equivalente de Efectivo provenientes de las Actividades de Financiacion'
            END::text AS descripcion,
            CASE s.seccion_orden
                WHEN 10 THEN 'Aumento (disminucion) del Efectivo y Equivalente de Efectivo provenientes de las Actividades de Operacion'
                WHEN 20 THEN 'Aumento (disminucion) del Efectivo y Equivalente de Efectivo provenientes de las Actividades de Inversion'
                ELSE 'Aumento (disminucion) del Efectivo y Equivalente de Efectivo provenientes de las Actividades de Financiacion'
            END::text AS descripcion_mostrar,
            0::smallint AS nivel_indentacion,
            true AS mostrar_subtotal,
            COALESCE(t.total_actual, 0) AS monto,
            COALESCE(t.total_actual, 0) AS monto_neto,
            COALESCE(t.total_anterior, 0) AS monto_anterior,
            COALESCE(t.total_anterior, 0) AS monto_neto_anterior
        FROM (VALUES (10), (20), (30)) AS s(seccion_orden)
        LEFT JOIN totales t ON t.seccion_orden = s.seccion_orden

        UNION ALL

        SELECT
            40,
            'AUMENTO (DISMINUCION) NETO DEL EFECTIVO Y EQUIVALENTE DE EFECTIVO'::text,
            1,
            3::smallint,
            NULL::character varying,
            'AUMENTO (DISMINUCION) NETO DEL EFECTIVO Y EQUIVALENTE DE EFECTIVO'::text,
            ''::text,
            0::smallint,
            true,
            COALESCE(SUM(t.total_actual), 0)::numeric(18,2),
            COALESCE(SUM(t.total_actual), 0)::numeric(18,2),
            COALESCE(SUM(t.total_anterior), 0)::numeric(18,2),
            COALESCE(SUM(t.total_anterior), 0)::numeric(18,2)
        FROM totales t
    )
    SELECT
        e.empresa_id,
        e.empresa_codigo,
        e.empresa_nombre,
        e.empresa_nombre_legal,
        e.empresa_rtn,
        e.empresa_email,
        e.empresa_telefono,
        e.empresa_direccion,
        q.seccion_orden,
        q.seccion_nombre,
        q.linea_orden,
        q.tipo_linea,
        q.codigo_cuenta,
        q.descripcion,
        q.descripcion_mostrar,
        q.nivel_indentacion,
        q.mostrar_subtotal,
        q.monto,
        q.monto_neto,
        q.monto_anterior,
        q.monto_neto_anterior
    FROM (
        SELECT
            b.seccion_orden,
            b.seccion_nombre,
            b.linea_orden,
            b.tipo_linea,
            b.codigo_cuenta,
            b.descripcion,
            b.descripcion_mostrar,
            b.nivel_indentacion,
            b.mostrar_subtotal,
            b.monto,
            b.monto_neto,
            b.monto_anterior,
            b.monto_neto_anterior
        FROM base b

        UNION ALL

        SELECT
            c.seccion_orden,
            c.seccion_nombre,
            c.linea_orden,
            c.tipo_linea,
            c.codigo_cuenta,
            c.descripcion,
            c.descripcion_mostrar,
            c.nivel_indentacion,
            c.mostrar_subtotal,
            c.monto,
            c.monto_neto,
            c.monto_anterior,
            c.monto_neto_anterior
        FROM calculadas c
    ) q
    CROSS JOIN empresa e
    ORDER BY
        q.seccion_orden,
        q.linea_orden,
        q.codigo_cuenta NULLS LAST;
END;
$function$;

COMMENT ON FUNCTION public.rep_estado_flujo_efectivo(bigint, date, date)
IS 'Estado de flujos de efectivo ERSAPS (metodo directo) comparativo por empresa, con datos de la empresa en uso. Clasifica contrapartidas de partidas que tocan cuentas de efectivo segun con_configuracion_flujo_efectivo.';

COMMIT;
