-- public.prv_tipoproveedor definition

-- Drop table

-- DROP TABLE public.prv_tipoproveedor;

CREATE TABLE public.prv_tipoproveedor (
	cod_tipoproveedor int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(150) NOT NULL,
	observaciones varchar(500) NULL,
	rowid uuid DEFAULT gen_random_uuid() NULL
);

-- Permissions

ALTER TABLE public.prv_tipoproveedor OWNER TO postgres;
GRANT ALL ON TABLE public.prv_tipoproveedor TO postgres;