SELECT TOP (1000) [ID_Account]
      ,[ID_Parent]
      ,[Descrip]
      ,[ID_AccountRef]
      ,[DescripShort]
      ,[siLevel]
      ,[boMovement]
      ,[boBudget]
      ,[Activity]
      ,[TypeAcct]
      ,[TypeHAC]
      ,[boCostCenter]
      ,[boThird]
      ,[boTaxBase]
      ,[ID_Export]
      ,[ID_Fit]
      ,[ColumOffset]
      ,[boBank]
      ,[boCurrency]
      ,[ID_Currency]
      ,[Budget]
      ,[LastBudget]
      ,[BudPercent]
      ,[boAmount]
      ,[boStatus]
      ,[dtDate]
      ,[ID_Correc]
  FROM [MD_CONTAB].[dbo].[C01Account]
