USE [MD_CONTAB]
GO

/****** Object:  Table [dbo].[C01BlSheet]    Script Date: 10/12/2025 13:16:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[C01BlSheet](
	[siPeriod] [smallint] NOT NULL,
	[NLine] [smallint] NOT NULL,
	[siClass] [tinyint] NOT NULL,
	[ID_Account] [varchar](24) NOT NULL,
 CONSTRAINT [C01BlSheet0] PRIMARY KEY CLUSTERED 
(
	[siPeriod] ASC,
	[siClass] ASC,
	[NLine] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[C01BlSheet] ADD  DEFAULT ((0)) FOR [siPeriod]
GO

ALTER TABLE [dbo].[C01BlSheet] ADD  DEFAULT ((0)) FOR [NLine]
GO

ALTER TABLE [dbo].[C01BlSheet] ADD  DEFAULT ((0)) FOR [siClass]
GO

ALTER TABLE [dbo].[C01BlSheet]  WITH CHECK ADD  CONSTRAINT [C01BlSheetFK01] FOREIGN KEY([ID_Account])
REFERENCES [dbo].[C01Account] ([ID_Account])
GO

ALTER TABLE [dbo].[C01BlSheet] CHECK CONSTRAINT [C01BlSheetFK01]
GO

ALTER TABLE [dbo].[C01BlSheet]  WITH CHECK ADD  CONSTRAINT [C01BlSheetFK02] FOREIGN KEY([siPeriod])
REFERENCES [dbo].[C01Periods] ([siPeriod])
GO

ALTER TABLE [dbo].[C01BlSheet] CHECK CONSTRAINT [C01BlSheetFK02]
GO

ALTER TABLE [dbo].[C01BlSheet]  WITH CHECK ADD CHECK  (([siClass]>=(1) AND [siClass]<=(8)))
GO


