USE [MD_CONTAB]
GO

/****** Object:  Table [dbo].[C01Detail]    Script Date: 10/12/2025 13:35:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[C01Detail](
	[ID_Detail] [varchar](8) NOT NULL,
	[Descrip] [varchar](80) NOT NULL,
	[Descrip2] [varchar](80) NULL,
	[Descrip3] [varchar](80) NULL,
 CONSTRAINT [C01Detail0] PRIMARY KEY CLUSTERED 
(
	[ID_Detail] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[C01Detail] ADD  DEFAULT ('REGISTRO NUEVO') FOR [Descrip]
GO

ALTER TABLE [dbo].[C01Detail] ADD  DEFAULT ('REGISTRO NUEVO') FOR [Descrip2]
GO

ALTER TABLE [dbo].[C01Detail] ADD  DEFAULT ('REGISTRO NUEVO') FOR [Descrip3]
GO


