USE [MD_CONTAB]
GO

/****** Object:  Table [dbo].[C01RpFolders]    Script Date: 10/12/2025 13:44:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[C01RpFolders](
	[folderid] [int] IDENTITY(1,1) NOT NULL,
	[foldername] [varchar](60) NOT NULL,
	[parentid] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[foldername] ASC,
	[parentid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


