USE [MD_CONTAB]
GO

/****** Object:  Table [dbo].[CGEXNU]    Script Date: 10/12/2025 13:52:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CGEXNU](
	[CodAutr] [varchar](15) NOT NULL,
	[CodCnx] [varchar](15) NOT NULL,
	[CodCmpy] [varchar](15) NOT NULL,
	[Estado] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CodAutr] ASC,
	[CodCnx] ASC,
	[CodCmpy] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CGEXNU] ADD  DEFAULT ((0)) FOR [Estado]
GO


