USE [MD_CONTAB]
GO

/****** Object:  Table [dbo].[CGNIVL]    Script Date: 10/12/2025 13:52:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CGNIVL](
	[CodNivl] [int] NOT NULL,
	[Descrip] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CodNivl] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CGNIVL] ADD  DEFAULT ((0)) FOR [CodNivl]
GO


