USE [MD_CONTAB]
GO

/****** Object:  Table [dbo].[SCProperty]    Script Date: 10/12/2025 14:06:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SCProperty](
	[siType] [smallint] NOT NULL,
	[Descrip] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[siType] ASC,
	[Descrip] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


