USE [MD_CONTAB]
GO

/****** Object:  Table [dbo].[TaxIdent]    Script Date: 10/12/2025 14:07:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TaxIdent](
	[idTaxIdent] [int] NOT NULL,
	[Descrip] [varchar](80) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idTaxIdent] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


