namespace SIAD.Core.DTOs.Contabilidad;

public record PlanCuentaDto(
    long AccountId,
    long? ParentAccountId,
    string Code,
    string Name,
    string AccountType,
    string? Category,
    short Level,
    bool AllowsPosting,
    string Status,
    string? Description,
    string? CurrencyCode,
    string? ShortDescription,
    string? ExternalReference,
    bool AllowsBudget,
    bool AllowsCostCenter,
    bool AllowsThird,
    bool AllowsBank,
    bool IsTaxBase,
    bool AllowsAmount,
    bool AllowsMultiCurrency,
    decimal? BudgetAmount,
    string CreatedBy = "SYSTEM",
    string? UpdatedBy = null);
