CREATE TABLE IF NOT EXISTS public.rep_catalogo_informe (
    informe_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    codigo character varying(80) NOT NULL,
    nombre character varying(150) NOT NULL,
    descripcion character varying(500) NULL,
    categoria character varying(50) NOT NULL,
    tipo_origen character varying(30) NOT NULL,
    ruta character varying(200) NOT NULL,
    consulta_clave character varying(80) NULL,
    icono_css_class character varying(80) NULL,
    orden integer NOT NULL DEFAULT 0,
    permite_exportar boolean NOT NULL DEFAULT FALSE,
    permite_imprimir boolean NOT NULL DEFAULT FALSE,
    is_active boolean NOT NULL DEFAULT TRUE,
    filtros_schema_json text NULL,
    metadata_json text NULL,
    created_at timestamp with time zone NOT NULL,
    created_by character varying(100) NOT NULL,
    updated_at timestamp with time zone NULL,
    updated_by character varying(100) NULL,
    CONSTRAINT fk_rep_catalogo_informe_company
        FOREIGN KEY (company_id)
        REFERENCES public.cfg_company(company_id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_rep_catalogo_informe_company_id_codigo
    ON public.rep_catalogo_informe(company_id, codigo);

CREATE UNIQUE INDEX IF NOT EXISTS ix_rep_catalogo_informe_company_id_ruta
    ON public.rep_catalogo_informe(company_id, ruta);
