-- =============================================================================
-- Bitácora de maestros: auditoría de acciones de usuario sobre tablas maestras.
-- Fecha: 2026-07-17
-- Regla DB Mirror: aplicar en siad_v3_restore (localhost) y en el servidor (prod).
-- IDEMPOTENTE: CREATE TABLE IF NOT EXISTS + índices IF NOT EXISTS. No borra ni
-- modifica datos existentes.
-- =============================================================================
BEGIN;

-- Esquema alineado con SIAD.Core/Entities/bitacora_maestros.cs y el mapeo de
-- SiadDbContext.Auditoria.cs (el borrador anterior de este script tenía otra
-- forma de tabla — id/registro_desc/cambios/ip — que el código nunca usó).
CREATE TABLE IF NOT EXISTS public.bitacora_maestros (
    bitacora_maestro_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company_id          BIGINT       NULL,
    modulo              VARCHAR(80)  NOT NULL,   -- módulo funcional: 'almacen', 'clientes', ...
    tabla               VARCHAR(128) NOT NULL,   -- nombre físico de la tabla auditada
    entidad             VARCHAR(256) NOT NULL,   -- nombre de la entidad CLR
    registro_id         VARCHAR(500) NULL,       -- PK del registro afectado (string: soporta int/uuid/compuesta)
    accion              VARCHAR(30)  NOT NULL,   -- 'CREAR' | 'EDITAR' | 'ELIMINAR'
    descripcion         VARCHAR(500) NOT NULL,   -- descriptor legible, best-effort
    valores_anteriores  JSONB        NULL,
    valores_nuevos      JSONB        NULL,
    fecha               TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    usuario             VARCHAR(256) NOT NULL,   -- User.Identity.Name ?? 'system'
    CONSTRAINT bitacora_maestro_pkey PRIMARY KEY (bitacora_maestro_id),
    CONSTRAINT fk_bitacora_maestros_company FOREIGN KEY (company_id)
        REFERENCES public.cfg_company(company_id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_bitacora_maestros_company_fecha ON public.bitacora_maestros (company_id, fecha);
CREATE INDEX IF NOT EXISTS ix_bitacora_maestros_modulo_tabla  ON public.bitacora_maestros (modulo, tabla);

CREATE TABLE IF NOT EXISTS public.bitacora_maestro_config (
    id                  SERIAL PRIMARY KEY,
    company_id          BIGINT       NOT NULL,
    entidad             VARCHAR(100) NOT NULL,   -- nombre de TABLA, del catálogo AuditableMaestros
    habilitado          BOOLEAN      NOT NULL DEFAULT TRUE,
    audita_crear        BOOLEAN      NOT NULL DEFAULT TRUE,
    audita_editar       BOOLEAN      NOT NULL DEFAULT TRUE,
    audita_eliminar     BOOLEAN      NOT NULL DEFAULT TRUE,
    usuariocreacion     VARCHAR(100) NULL,
    fechacreacion       TIMESTAMP WITHOUT TIME ZONE NULL,
    usuariomodificacion VARCHAR(100) NULL,
    fechamodificacion   TIMESTAMP WITHOUT TIME ZONE NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_bitacora_maestro_config_company_entidad
    ON public.bitacora_maestro_config (company_id, entidad);

COMMENT ON TABLE public.bitacora_maestros IS 'Auditoría append-only de acciones de usuario sobre tablas maestras.';
COMMENT ON TABLE public.bitacora_maestro_config IS 'Configura, por empresa, qué entidades maestras se auditan.';

COMMIT;
