CREATE TABLE IF NOT EXISTS public.rep_reporte_layout
(
    report_layout_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    informe_id bigint NOT NULL,
    version_num integer NOT NULL,
    estado varchar(20) NOT NULL,
    layout_xml text NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by varchar(100) NOT NULL,
    updated_at timestamp without time zone NULL,
    updated_by varchar(100) NULL,
    published_at timestamp without time zone NULL,
    published_by varchar(100) NULL,
    CONSTRAINT ck_rep_reporte_layout_estado CHECK (estado IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT fk_rep_reporte_layout_company FOREIGN KEY (company_id) REFERENCES public.cfg_company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_rep_reporte_layout_informe FOREIGN KEY (informe_id) REFERENCES public.rep_catalogo_informe (informe_id) ON DELETE CASCADE,
    CONSTRAINT uq_rep_reporte_layout_version UNIQUE (company_id, informe_id, version_num)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_rep_reporte_layout_draft
    ON public.rep_reporte_layout (company_id, informe_id)
    WHERE estado = 'DRAFT';

CREATE UNIQUE INDEX IF NOT EXISTS ux_rep_reporte_layout_published
    ON public.rep_reporte_layout (company_id, informe_id)
    WHERE estado = 'PUBLISHED';

INSERT INTO public.rep_catalogo_informe
(
    company_id,
    codigo,
    nombre,
    descripcion,
    categoria,
    tipo_origen,
    ruta,
    consulta_clave,
    icono_css_class,
    orden,
    permite_exportar,
    permite_imprimir,
    is_active,
    created_at,
    created_by
)
SELECT
    company.company_id,
    'bancos-transacciones',
    'Transacciones Bancarias',
    'Plantilla base para migrar el reporte legacy de transacciones bancarias a diseño web.',
    'Contabilidad',
    'REPORT',
    '/informes/reportes/bancos-transacciones/viewer',
    NULL,
    'bi bi-bank',
    20,
    true,
    true,
    true,
    now(),
    'reporteria-bootstrap'
FROM public.cfg_company company
WHERE NOT EXISTS
(
    SELECT 1
    FROM public.rep_catalogo_informe report
    WHERE report.company_id = company.company_id
      AND report.codigo = 'bancos-transacciones'
);
