using System.Collections.Generic;

namespace SIAD.Core.Constants;

public static class PermissionEndpointCatalog
{
    public sealed record EndpointPermissionDefinition(
        string Module,
        string Option,
        string Resource,
        PermissionAction Action,
        string HttpMethod,
        string Route)
    {
        public string Permission => PermissionKeyBuilder.BuildPermission(Module, Resource, Action);
        public string DisplayName => $"{HttpMethod} {Route}";
    }

    public static readonly EndpointPermissionDefinition[] Ventas =
    [
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.EmisionLectura,
            Resource: "emision_lectura__facturacion_emision_lectura_bloque",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/facturacion/emision-lectura/bloque"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.EmisionLectura,
            Resource: "emision_lectura__facturacion_emision_lectura",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/facturacion/emision-lectura"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.EmisionLectura,
            Resource: "emision_lectura__facturacion_emision_lectura_preview",
            Action: PermissionAction.View,
            HttpMethod: "POST",
            Route: "api/facturacion/emision-lectura/preview"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/CaptacionPagos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_arqueos",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/arqueos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_arqueos_paged",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/arqueos/paged"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_bancos",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/bancos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_cajas",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/cajas"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_clientes",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/clientes"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_miscelaneos",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/miscelaneos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_miscelaneos_paged",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/miscelaneos/paged"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_miscelaneos_registrar",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/CaptacionPagos/miscelaneos/registrar"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_miscelaneos_reverso",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/CaptacionPagos/miscelaneos/reverso"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_miscelaneos_recibo_detalle",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/miscelaneos/{recibo}/detalle"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_periodo_actual",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/periodo-actual"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_posteo_manual",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/CaptacionPagos/posteo-manual"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_posteo_manual_reverso",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/CaptacionPagos/posteo-manual/reverso"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_reverso",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/CaptacionPagos/reverso"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_saldos_manual_clienteclave",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/saldos-manual/{clienteClave}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_search_term",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/search/{term}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_numfactura",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/{numFactura}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CaptacionPagos,
            Resource: "captacion_pagos__captacionpagos_numfactura_existe",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/CaptacionPagos/{numFactura}/existe"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/Clientes"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_foto_medidor_ide_imagen",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/foto-medidor/{ide:int}/imagen"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_search",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/search"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_search_paged",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/search-paged"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_id",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/{id:int}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_id",
            Action: PermissionAction.Edit,
            HttpMethod: "PUT",
            Route: "api/Clientes/{id:int}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_id_estado_cuenta",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/{id:int}/estado-cuenta"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_id_foto_medidor",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/{id:int}/foto-medidor"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_id_foto_medidor_header",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/{id:int}/foto-medidor/header"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_id_historico_consumo",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/{id:int}/historico-consumo"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_id_historico_consumo_paged",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/{id:int}/historico-consumo/paged"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_id_movimientos",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/{id:int}/movimientos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_id_movimientos_paged",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/{id:int}/movimientos/paged"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_id_tarifas",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Clientes/{id:int}/tarifas"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Clientes,
            Resource: "clientes__clientes_clave_no_cortable",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/Clientes/{clave}/no-cortable"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Cobranza,
            Resource: "cobranza__cobranza_clientes_clave_bloqueo",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Cobranza/clientes/{clave}/bloqueo"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Cobranza,
            Resource: "cobranza__cobranza_clientes_clave_saldos",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Cobranza/clientes/{clave}/saldos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Cobranza,
            Resource: "cobranza__cobranza_numero_letras",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Cobranza/numero-letras"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Cobranza,
            Resource: "cobranza__cobranza_planes",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Cobranza/planes"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Cobranza,
            Resource: "cobranza__cobranza_planes",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/Cobranza/planes"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Cobranza,
            Resource: "cobranza__cobranza_planes_calcular",
            Action: PermissionAction.View,
            HttpMethod: "POST",
            Route: "api/Cobranza/planes/calcular"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.Cobranza,
            Resource: "cobranza__cobranza_planes_correlativo",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/Cobranza/planes/{correlativo}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.FacturacionMiscelaneos,
            Resource: "facturacion_miscelaneos__facturacion_miscelaneos_categorias",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/facturacion/miscelaneos/categorias"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.FacturacionMiscelaneos,
            Resource: "facturacion_miscelaneos__facturacion_miscelaneos_clientes",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/facturacion/miscelaneos/clientes"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.FacturacionMiscelaneos,
            Resource: "facturacion_miscelaneos__facturacion_miscelaneos_clientes_clave",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/facturacion/miscelaneos/clientes/{clave}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.FacturacionMiscelaneos,
            Resource: "facturacion_miscelaneos__facturacion_miscelaneos_recibos",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/facturacion/miscelaneos/recibos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.FacturacionMiscelaneos,
            Resource: "facturacion_miscelaneos__facturacion_miscelaneos_recibos_numero",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/facturacion/miscelaneos/recibos/{numero:int}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.NotasCreditoDebito,
            Resource: "notas_credito_debito__facturacion_notas",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/facturacion/notas"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.NotasCreditoDebito,
            Resource: "notas_credito_debito__facturacion_notas_clientes",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/facturacion/notas/clientes"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.NotasCreditoDebito,
            Resource: "notas_credito_debito__facturacion_notas_clientes_clave",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/facturacion/notas/clientes/{clave}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.NotasCreditoDebito,
            Resource: "notas_credito_debito__facturacion_notas_clientes_clave_configuracion",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/facturacion/notas/clientes/{clave}/configuracion"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.NotasCreditoDebito,
            Resource: "notas_credito_debito__facturacion_notas_motivos",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/facturacion/notas/motivos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.NotasCreditoDebito,
            Resource: "notas_credito_debito__facturacion_notas_motivos_id",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/facturacion/notas/motivos/{id:int}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.PeriodosComerciales,
            Resource: "periodos_comerciales__ventas_periodos_comerciales_companyid",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/ventas/periodos-comerciales/{companyId}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.PeriodosComerciales,
            Resource: "periodos_comerciales__ventas_periodos_comerciales_companyid_ciclos_periodocicloid_rutas",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/ventas/periodos-comerciales/{companyId}/ciclos/{periodoCicloId}/rutas"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.PeriodosComerciales,
            Resource: "periodos_comerciales__ventas_periodos_comerciales_companyid_periodocomercialid_checklist",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/ventas/periodos-comerciales/{companyId}/{periodoComercialId}/checklist"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.PeriodosComerciales,
            Resource: "periodos_comerciales__ventas_periodos_comerciales_companyid_abrir",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/ventas/periodos-comerciales/{companyId}/abrir"),
        // Fase B apertura-ciclo-único (2026-07-15): preview/sugerencia de la
        // apertura integral y deshacer apertura.
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.PeriodosComerciales,
            Resource: "periodos_comerciales__ventas_periodos_comerciales_companyid_abrir_preview",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/ventas/periodos-comerciales/{companyId}/abrir/preview"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.PeriodosComerciales,
            Resource: "periodos_comerciales__ventas_periodos_comerciales_companyid_abrir_sugerencia",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/ventas/periodos-comerciales/{companyId}/abrir/sugerencia"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.PeriodosComerciales,
            Resource: "periodos_comerciales__ventas_periodos_comerciales_companyid_ciclos_periodocicloid_deshacer",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/ventas/periodos-comerciales/{companyId}/ciclos/{periodoCicloId}/deshacer"),
        // Fase C: planilla del ciclo (reemplaza la consulta del Auxiliar de
        // Lectura eliminado).
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.PeriodosComerciales,
            Resource: "periodos_comerciales__ventas_periodos_comerciales_companyid_ciclos_periodocicloid_planilla",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/ventas/periodos-comerciales/{companyId}/ciclos/{periodoCicloId}/planilla"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.PeriodosComerciales,
            Resource: "periodos_comerciales__ventas_periodos_comerciales_companyid_ciclos_periodocicloid_cerrar",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/ventas/periodos-comerciales/{companyId}/ciclos/{periodoCicloId}/cerrar"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.PeriodosComerciales,
            Resource: "periodos_comerciales__ventas_periodos_comerciales_companyid_periodocomercialid_cerrar",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/ventas/periodos-comerciales/{companyId}/{periodoComercialId}/cerrar"),

        // Condiciones de lectura (app_lectores 2026-07-06): ABM del catálogo por
        // empresa. GET lista tipos + condiciones; POST persiste el conjunto.
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CondicionesLectura,
            Resource: "condiciones_lectura__ventas_condiciones_lectura_companyid",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/ventas/condiciones-lectura/{companyId}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CondicionesLectura,
            Resource: "condiciones_lectura__ventas_condiciones_lectura_companyid",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/ventas/condiciones-lectura/{companyId}"),

        // Calendario de facturación (Fase A apertura-ciclo-único 2026-07-14):
        // fechas por año/mes/ciclo (calendariopro). GET años/año; POST guarda
        // el año o copia un año a otro.
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CalendarioFacturacion,
            Resource: "calendario_facturacion__ventas_calendario_facturacion_companyid_anios",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/ventas/calendario-facturacion/{companyId}/anios"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CalendarioFacturacion,
            Resource: "calendario_facturacion__ventas_calendario_facturacion_companyid_anio",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/ventas/calendario-facturacion/{companyId}/{anio}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CalendarioFacturacion,
            Resource: "calendario_facturacion__ventas_calendario_facturacion_companyid_anio",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/ventas/calendario-facturacion/{companyId}/{anio}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Ventas,
            Option: PermissionResources.Ventas.CalendarioFacturacion,
            Resource: "calendario_facturacion__ventas_calendario_facturacion_companyid_copiar",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/ventas/calendario-facturacion/{companyId}/copiar"),
    ];

    public static readonly EndpointPermissionDefinition[] Contabilidad =
    [
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.Integracion,
            Resource: "integracion__contabilidad_integracion_companyid",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/contabilidad/integracion/{companyId}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.Integracion,
            Resource: "integracion__contabilidad_integracion_companyid",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/contabilidad/integracion/{companyId}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.Integracion,
            Resource: "integracion__contabilidad_integracion_companyid_validacion",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/contabilidad/integracion/{companyId}/validacion"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.Integracion,
            Resource: "integracion__contabilidad_integracion_companyid_perfil_perfil",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/contabilidad/integracion/{companyId}/perfil/{perfil}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.Integracion,
            Resource: "integracion__contabilidad_integracion_companyid_servicios",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/contabilidad/integracion/{companyId}/servicios"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.Integracion,
            Resource: "integracion__contabilidad_integracion_companyid_cuentas_posteables",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/contabilidad/integracion/{companyId}/cuentas-posteables"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.Integracion,
            Resource: "integracion__contabilidad_integracion_categorias",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/contabilidad/integracion/categorias"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.LoteFacturacion,
            Resource: "integracion__contabilidad_lote_facturacion_companyid_preview",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/contabilidad/lote-facturacion/{companyId}/preview"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.LoteFacturacion,
            Resource: "integracion__contabilidad_lote_facturacion_companyid_generar",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/contabilidad/lote-facturacion/{companyId}/generar"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.LoteFacturacion,
            Resource: "integracion__contabilidad_lote_facturacion_companyid_historial",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/contabilidad/lote-facturacion/{companyId}/historial"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.LoteFacturacion,
            Resource: "integracion__contabilidad_lote_facturacion_companyid_pendientes",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/contabilidad/lote-facturacion/{companyId}/pendientes"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Contabilidad,
            Option: PermissionResources.Contabilidad.Saldos,
            Resource: "saldos__contabilidad_saldos_companyid_verificacion",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/contabilidad/saldos/{companyId}/verificacion"),
    ];

    /// <summary>
    /// Carga inicial de existencias y ajustes de inventario (2026-07-30).
    /// <para>
    /// Los endpoints de <c>cerrar</c> y <c>reabrir</c> NO están aquí a propósito: van
    /// protegidos con <c>[ModuleAuthorize(PermissionModules.Configuracion)]</c> <b>sin
    /// recurso</b>, porque un sub-recurso dentro de <c>inventario</c> sería un
    /// superconjunto de <c>module.inventario.*</c> y no restringiría a nadie. Sacarlos del
    /// módulo es la única palanca que sí restringe con el <c>ModuleAuthorize</c> actual.
    /// </para>
    /// </summary>
    public static readonly EndpointPermissionDefinition[] Inventario =
    [
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.CargaInicial,
            Resource: "carga_inicial__almacen_carga_inicial_pendientes",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/carga-inicial/pendientes"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.CargaInicial,
            Resource: "carga_inicial__almacen_carga_inicial_simular",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/carga-inicial/simular"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.CargaInicial,
            Resource: "carga_inicial__almacen_carga_inicial_ejecutar",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/almacen/carga-inicial/ejecutar"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.CargaInicial,
            Resource: "carga_inicial__almacen_carga_inicial_costo_manual",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/almacen/carga-inicial/costo-manual"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Ajustes,
            Resource: "ajustes__almacen_ajustes",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/almacen/ajustes"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Ajustes,
            Resource: "ajustes__almacen_ajustes",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/ajustes"),

        // Catálogo de conceptos de movimiento de almacén (2026-08-01).
        // 'desactivar' es POST pero se cataloga como Edit: cambia el estado de un concepto
        // existente, no crea uno nuevo (mismo criterio que la anulación de recepciones).
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.ConceptosMovimiento,
            Resource: "conceptos_movimiento__almacen_conceptos_movimiento",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/conceptos-movimiento"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.ConceptosMovimiento,
            Resource: "conceptos_movimiento__almacen_conceptos_movimiento",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/almacen/conceptos-movimiento"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.ConceptosMovimiento,
            Resource: "conceptos_movimiento__almacen_conceptos_movimiento",
            Action: PermissionAction.Edit,
            HttpMethod: "PUT",
            Route: "api/almacen/conceptos-movimiento/{id:int}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.ConceptosMovimiento,
            Resource: "conceptos_movimiento__almacen_conceptos_movimiento_desactivar",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/almacen/conceptos-movimiento/{id:int}/desactivar"),

        // Documento de movimiento de almacén (2026-08-03).
        // 'anular' es POST pero se cataloga como Edit: cambia el estado de un documento
        // existente y postea su reversa; no crea uno nuevo.
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Movimientos,
            Resource: "movimientos__almacen_movimientos",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/movimientos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Movimientos,
            Resource: "movimientos__almacen_movimientos_id",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/movimientos/{id:int}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Movimientos,
            Resource: "movimientos__almacen_movimientos",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/almacen/movimientos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Movimientos,
            Resource: "movimientos__almacen_movimientos_anular",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/almacen/movimientos/{id:int}/anular"),

        // Traslado entre bodegas (2026-08-04, Fase 5). 'recibir' y 'anular' son POST pero se
        // catalogan como Edit: cambian el estado de un traslado existente, no crean uno nuevo.
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Traslados,
            Resource: "traslados__almacen_traslados",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/traslados"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Traslados,
            Resource: "traslados__almacen_traslados_id",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/traslados/{id:int}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Traslados,
            Resource: "traslados__almacen_traslados",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/almacen/traslados"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Traslados,
            Resource: "traslados__almacen_traslados_recibir",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/almacen/traslados/{id:int}/recibir"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Traslados,
            Resource: "traslados__almacen_traslados_anular",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/almacen/traslados/{id:int}/anular"),

        // Documento de requisición (2026-08-04, Fase 6). 'aprobar'/'rechazar' se catalogan como
        // View: el permiso real de aprobar (module.inventario.requisiciones.aprobar) lo verifica el
        // controller a partir de los claims (decisión: quien tenga el permiso, aprueba).
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Requisiciones,
            Resource: "requisiciones__almacen_requisiciones_documentos",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/requisiciones/documentos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Requisiciones,
            Resource: "requisiciones__almacen_requisiciones_documentos_id",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/requisiciones/documentos/{id:int}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Requisiciones,
            Resource: "requisiciones__almacen_requisiciones_documentos",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/almacen/requisiciones/documentos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Requisiciones,
            Resource: "requisiciones__almacen_requisiciones_documentos_id",
            Action: PermissionAction.Edit,
            HttpMethod: "PUT",
            Route: "api/almacen/requisiciones/documentos/{id:int}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Requisiciones,
            Resource: "requisiciones__almacen_requisiciones_documentos_enviar",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/almacen/requisiciones/documentos/{id:int}/enviar"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Requisiciones,
            Resource: "requisiciones__almacen_requisiciones_documentos_aprobar",
            Action: PermissionAction.View,
            HttpMethod: "POST",
            Route: "api/almacen/requisiciones/documentos/{id:int}/aprobar"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Requisiciones,
            Resource: "requisiciones__almacen_requisiciones_documentos_rechazar",
            Action: PermissionAction.View,
            HttpMethod: "POST",
            Route: "api/almacen/requisiciones/documentos/{id:int}/rechazar"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Requisiciones,
            Resource: "requisiciones__almacen_requisiciones_documentos_anular",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/almacen/requisiciones/documentos/{id:int}/anular"),

        // Documento de descargo (2026-08-04, Fase 6): la entrega real (postea).
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Descargos,
            Resource: "descargos__almacen_descargos_documentos",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/descargos/documentos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Descargos,
            Resource: "descargos__almacen_descargos_documentos_id",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/almacen/descargos/documentos/{id:int}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Descargos,
            Resource: "descargos__almacen_descargos_documentos",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/almacen/descargos/documentos"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Inventario,
            Option: PermissionResources.Inventario.Descargos,
            Resource: "descargos__almacen_descargos_documentos_anular",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/almacen/descargos/documentos/{id:int}/anular"),
    ];

    public static readonly EndpointPermissionDefinition[] Configuracion =
    [
        // Catálogo de formatos fiscales (2026-08-22): máscara del No. de factura (SAR) y del CAI
        // que se transcriben del proveedor. 'desactivar' es POST pero se cataloga como Edit:
        // cambia el estado de un formato existente, no crea uno nuevo (mismo criterio que los
        // conceptos de movimiento). El endpoint 'lookup' NO se cataloga a propósito: vive en otro
        // controlador con [Authorize] a secas, porque quien captura una recepción de compra puede
        // no tener acceso al módulo Configuración y sin él no podría ni teclear la factura.
        new EndpointPermissionDefinition(
            Module: PermissionModules.Configuracion,
            Option: PermissionResources.Configuracion.FormatosFiscales,
            Resource: "formatos_fiscales__mantenimientos_formatos_fiscales",
            Action: PermissionAction.View,
            HttpMethod: "GET",
            Route: "api/mantenimientos/formatos-fiscales"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Configuracion,
            Option: PermissionResources.Configuracion.FormatosFiscales,
            Resource: "formatos_fiscales__mantenimientos_formatos_fiscales",
            Action: PermissionAction.Create,
            HttpMethod: "POST",
            Route: "api/mantenimientos/formatos-fiscales"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Configuracion,
            Option: PermissionResources.Configuracion.FormatosFiscales,
            Resource: "formatos_fiscales__mantenimientos_formatos_fiscales",
            Action: PermissionAction.Edit,
            HttpMethod: "PUT",
            Route: "api/mantenimientos/formatos-fiscales/{id:int}"),
        new EndpointPermissionDefinition(
            Module: PermissionModules.Configuracion,
            Option: PermissionResources.Configuracion.FormatosFiscales,
            Resource: "formatos_fiscales__mantenimientos_formatos_fiscales_desactivar",
            Action: PermissionAction.Edit,
            HttpMethod: "POST",
            Route: "api/mantenimientos/formatos-fiscales/{id:int}/desactivar"),
    ];

    public static IEnumerable<EndpointPermissionDefinition> All => [.. Ventas, .. Contabilidad, .. Inventario, .. Configuracion];
}
